### ISSUE TITLE
After doing zoom, it does not show any layer

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#26291]
Author Name: **Mario FF** (Mario FF)
Original Redmine Issue: [18401](https://issues.qgis.org/issues/18401)
Affected QGIS version: 3.0.0
Redmine category:map_canvas

---
Project with raster ASC, WMS and SHP layers. Sometimes, once you zoom, when trying to refresh map, it doesn't show anything. pProgresion bar of statusbar keeps "running" but nothing is showed.

Once it is broken, if you load any other project, it does not represent any map info

---

- [qgisTEST.zip](https://issues.qgis.org/attachments/download/12432/qgisTEST.zip) (Mario FF)

**Comment by gioman** [comment]
Whatever the issue was this seems long fixed now. Please reopen if necessary.

**Comment by bhlevca** [comment]
The problem still exists in QGIS version | 3.36.2-Maidenhead
