### ISSUE TITLE
"Classify" button in graduated symbology may make too small a range

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27420]
Author Name: **Ryan Desmond** (@rddesmond)
Original Redmine Issue: [19593](https://issues.qgis.org/issues/19593)
Affected QGIS version: 3.2.1
Redmine category:symbology

---
Auto-classified ranges that are created on the graduated symbology preference panel may not include features at the extremes of the field used for the ranges.

## Procedure

1. Load the attached [points.geojson](https://issues.qgis.org/attachments/download/13107/points.geojson) into QGIS
1. Open the layer properties / symbology
## Select "Classify" to generate 5 classes from the data
1. Hit "Okay" to return to the main view

![symbology_properties.png](https://issues.qgis.org/attachments/download/13109/symbology_properties.png)

## Expected

When looking at the correct location on the map, all 6 points are visible.  Points are located at (0,0) (10,0) (20,0) (30,0) (40,0) (50,0).

## Actual

When looking at the correct location on the map, only 4 points are visible.  The points with the lowest and highest values are outside of the generated categories and are not displayed.  See the attached image (which has a duplicate of the initial layer to show text where the points should be.)

![points_displayed_in_qgis.png](https://issues.qgis.org/attachments/download/13108/points_displayed_in_qgis.png)

---

- [points.geojson](https://issues.qgis.org/attachments/download/13107/points.geojson) (Ryan Desmond)
- [points_displayed_in_qgis.png](https://issues.qgis.org/attachments/download/13108/points_displayed_in_qgis.png) (Ryan Desmond)
- [symbology_properties.png](https://issues.qgis.org/attachments/download/13109/symbology_properties.png) (Ryan Desmond)

**Comment by kannes** [comment]
This seems like quite a major bug to me, leading to a lying map.

I encountered it today with another, polygonal dataset:

1. Load 
[attrw.gpkg.zip](https://github.com/qgis/QGIS/files/3416943/attrw.gpkg.zip)
2. Create a graduated style
3. Classify by "criminal cases"
4. Use any mode

![Untitled](https://user-images.githubusercontent.com/7661092/61628666-3fa54600-ac83-11e9-85aa-8a62bfc50a3e.png)

- The lowest class limit value will be shown as `39.69`.
- The polygon with the id `82` will not be shown, there is a gap in the map
- Said polygon has the value `39.686286257693055`

Manually setting a slightly lower minimum value such as `39.686` will make the feature appear in the map. But the Values list will again show `39.69` and if you doubleclick it, show and subsequently again use `39.69` as value.

There seems to be a round() somewhere where it absolutely should not be. :)

**Comment by gioman** [comment]
> There seems to be a round() somewhere where it absolutely should not be. :)

and on the old LTR (2.18) does not happen.

**Comment by alexbruy** [comment]
Seems fixed in master

**Comment by kannes** [comment]
Only partially. For Pretty Breaks, Logarithmic Scale and Equal Interval I still get the blank polygon.

Please re-open.

**Comment by nyalldawson** [comment]
this is **not** an easy fix :stuck_out_tongue_closed_eyes:

**Comment by kannes** [comment]
You're the best, @nyalldawson
