### ISSUE TITLE
QGIS3: 3 bugs in ArcGIS Feature Server when using Data Source Manager

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#27635]
Author Name: **Tobias Wendorff** (Tobias Wendorff)
Original Redmine Issue: [19811](https://issues.qgis.org/issues/19811)
Affected QGIS version: 3.5(master)
Redmine category:web_services_clients/arcgis
Assignee: Sandro Mani

---
I've found three bugs when loading data from ArcGIS Feature Server.

1. When adding a filter using "Build query", the filter isn't used at all. I've checked it with a proxy: the filter is ignored. Using OGR on command-line, the same query works (tried on several MapFeature servers)-
2. When adding a filter using "Build query", the BBOX gets fixed to the current screen extent. "Cache Feature" or "Only request features overlapping the current view extent" on or off doesn't change anything.
3. The filter cannot be removed. The empty "Expresstion String Builder" can't be closed with "okay" (when there's no filter, the button is grayed out)... filter workaround: "TRUE"

**Comment by roya0045** [comment]
@nyalldawson in your rework of this provider, do you know if some of these elements were solved? I'm mostly curious about the active get request for disabled layers.

**Comment by nyalldawson** [comment]
@roya0045 1-4 have been, because the non-implemented query query button was removed.

5 is not clear enough -- if Tobias means "scrolling in the attribute table", then naturally the features will be downloaded regardless of the layer's visibility.

**Comment by nyalldawson** [comment]
@gioman I suggest we close this one and request new tickets be filed for any issues still outstanding -- this ticket is a mess of multiple reports without much information.

**Comment by gioman** [comment]
> @gioman I suggest we close this one and request new tickets be filed for any issues still outstanding -- this ticket is a mess of multiple reports without much information.

agree. 

Please file new separate tickets for any remaining issue.

**Comment by carlansgu** [comment]
I cant find the "allow filtering of AFS layers on server side" - where is this request? I still have this problem, I can't use filtering or query bilder on ArcGIS Feature Service layers in QGIS. I would like to know if there are any solutions on this or if it is Esri that don´t allow this filtering? I dont understand....
