### ISSUE TITLE
Unable to add new features in QGIS for PostGIS table using sequence for gid.  Not providing nextval('sequencename'::regclass) in editor form or attribute table

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29489]
Author Name: **David Mancini** (@weifageo)
Original Redmine Issue: [21673](https://issues.qgis.org/issues/21673)
Affected QGIS version: 3.6.0
Redmine category:data_provider/postgis

---
Last Friday I encountered a new error that I've never seen before.  When editing a new PostGIS table in QGIS 3.6.0 I'm unable to save my edits as the 'gid' column auto populates it's value as NULL. This behaviour seems to occur when drawing a new spatial feature, as well as when copy and pasting new features from a separate shapefile without 'gid' column.

There error received is as follows.
Could not commit changes to layer tablename

Errors: ERROR: 1 feature(s) not added.
  
  Provider errors:
      PostGIS error while adding features: ERROR:  null value in column "gid" violates not-null constraint
    DETAIL:  Failing row contains (null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 0106000020E6100000010000000103000000010000000400000060015885FD2F...).

Looking into the database the table is using gid SERIAL PRIMARY KEY to define the "gid" column.  I've tried dropping and re-adding the "gid" column, creating new tables, even manually creating a sequence and manually defining a new gid column as gid integer NOT NULL DEFAULT nextval('"sequencename"'::regclass) but no luck.

The strange thing is other tables within our PostgreSQL/PostGIS database do respond properly, providing the nextval('sequencename'::regclass) within the editor form and attribute table when creating new features or copy and pasting features in from another source.

I looked into our database and it is reporting itself as 
PostgreSQL 9.4.19 on x86_64-unknown-linux-gnu, compiled by gcc (Debian 4.9.2-10+deb8u1) 4.9.2, 64-bit
POSTGIS="2.1.4 r12966" GEOS="3.4.2-CAPI-1.8.2 r3921" PROJ="Rel. 4.8.0, 6 March 2012" GDAL="GDAL 1.10.1, released 2013/08/26" LIBXML="2.9.1" LIBJSON="UNKNOWN" TOPOLOGY RASTER

I suspect that the database may have recently been upgraded to this version 9.4.19 which maybe related to this new glitch.  Older tables in our database seem to function properly, recreating those same database tables using new tablenames seems to run into this new glitch.

When searching online I came across an older ticket - Bug report #27391 which seems to describe the same behaviour.  As described in this post, tables that do function properly seem to identify the 'gid' column as a 'Text Edit' widget type, whereas the new tables that are broken seem to identify 'gid' column as a 'Range' widget type.  Looking at the database both tables were created the same manner using gid SERIAL PRIMARY KEY.  However, somehow QGIS is detecting a difference between these two tables.

This issues seems is not only limited to the latest QGIS 3.6.0, I also tried QGIS 2.18.21 and the results are the same (some older tables provide nextval('sequencename'::regclass) and newer tables remain NULL.  Without the ability for the database to auto-increment a gid column using a sequence properly, it makes our database significantly harder to use within QGIS.  This issue seems to be affecting more users so I decided to file a new issue to see if any others have been able to find a suitable solution.

I've attached some screenshots for your reference.  It seems that either QGIS, the PostgreSQL database or the way in which SERIAL columns are being communicated from one to the other has somehow changed recently, but I'm not sure as to where the change exists or how to resolve the behaviour.  I'm hoping someone with more knowledge of the inner workings of QGIS and the PostGIS layer management will have some more understanding of what is happening here.  This is the strangest behaviour I have ever come across in my 10 years of working with PostgreSQL/PostGIS and I'm absolutely stumped.

---

- [working_gid_sequence.png](https://issues.qgis.org/attachments/download/14669/working_gid_sequence.png) (David Mancini)
- [not_working_gid_sequence.png](https://issues.qgis.org/attachments/download/14670/not_working_gid_sequence.png) (David Mancini)
- [working_editor_form.png](https://issues.qgis.org/attachments/download/14671/working_editor_form.png) (David Mancini)
- [not_working_editor_form.png](https://issues.qgis.org/attachments/download/14672/not_working_editor_form.png) (David Mancini)
- [working_table_definition.png](https://issues.qgis.org/attachments/download/14673/working_table_definition.png) (David Mancini)
- [not_working_table_definition.png](https://issues.qgis.org/attachments/download/14674/not_working_table_definition.png) (David Mancini)

**Comment by sylviaobk** [comment]
Hi David,

try this:
select 'myschema.test'::regclass::oid;

If the result is bigger than 2147483647 (integer) I get the bug. On a different server where oid is small enough the serial - datatype is ok.

**Comment by paolabfor** [comment]
Hi @gioman, 
we have the same problem. Could you please tell me if there are any news about this bug?
Thanks in advance

**Comment by sylviaobk** [comment]
Hi gioman, 
the bug was fixed in 3.4.9

**Comment by paolabfor** [comment]
Thanks @sylviaobk, I have installed the 3.4.11 and the bug still exists.

**Comment by sylviaobk** [comment]
Did you try 3.4.9?

**Comment by paolabfor** [comment]
Sorry, I didn't try the 3.4.9 because I supposed that the 3.4.11 already contains the fixes for previous bugs. 
Do you think there are any regressions?

**Comment by sylviaobk** [comment]
I would give it a try

**Comment by gioman** [comment]
>  we have the same problem. Could you please tell me if there are any news about this bug?

@paolabfor no issues here on 3.4.12. What is the SQL definition of your table? Can you share a sample project?

**Comment by paolabfor** [comment]
Hi @gioman,
here the attachment with the steps to create the error and the structure of the table.
[Postgis_bug.pdf](https://github.com/qgis/QGIS/files/3641035/Postgis_bug.pdf)

**Comment by gioman** [comment]
>  here the attachment with the steps to create the error and the structure of the table.

@paolabfor can you please add those steps here as a comment? you can add images and format code where necessary, thanks!

**Comment by paolabfor** [comment]
This is the structure of the table and the sequence of gid field.
```
outbreaks
(
  gid integer NOT NULL DEFAULT nextval('outbreaks_gid_seq'::regclass),
  localid character varying(254),
  code character varying(254),
  disease character varying(254),
  animalno integer,
  species character varying(254),
  production character varying(254),
  year integer,
  ...
  hrid character varying(254),
  geom geometry,
  CONSTRAINT outbreaks_pkey PRIMARY KEY (gid),
  CONSTRAINT enforce_dims_geom CHECK (st_ndims(geom) = 2),
  CONSTRAINT enforce_geotype_geom CHECK (geometrytype(geom) = 'POINT'::text OR geom IS NULL),
  CONSTRAINT enforce_srid_geom CHECK (st_srid(geom) = 4326)
);

CREATE SEQUENCE public.outbreaks_gid_seq
  INCREMENT 1
  MINVALUE 1
  ...;
ALTER TABLE public.outbreaks_gid_seq
```

The steps are:
I copied the point feature created on outbreak_2019_9_23 layer to paste it on layer outbreaks_point (that is a PostGIS table).
![immagine](https://user-images.githubusercontent.com/53217629/65409480-1c645780-dde8-11e9-8c6d-96dec2a01cee.png)

![immagine](https://user-images.githubusercontent.com/53217629/65409492-25552900-dde8-11e9-9f7e-861d8e2ce45e.png)

**gid** field in outbreaks_point is a sequence.
![immagine](https://user-images.githubusercontent.com/53217629/65409510-3140eb00-dde8-11e9-9443-834568c05502.png)

The value that appears  in gid field is: `nextval('outbreaks_point_gid_seq'::regclass)`

When I saved the layer I have a Commit errors:
![immagine](https://user-images.githubusercontent.com/53217629/65409572-4f0e5000-dde8-11e9-814b-c3d13f82a4fe.png)
This is the error:

```
Could not commit changes to layer outbreaks_point

Errors: ERROR: 1 feature(s) not added.
Provider errors:
PostGIS error while adding features: ERROR: invalid input syntax for integer: ""
LINE 1: ...fromwkb($1::bytea,4326),'A','A','No','Bluetongue','','Cattle...
^
```

**Comment by gioman** [comment]
@paolabfor questions:

is outbreak_2019_9_23 a postgis layer?
is the structure of identical outbreak_2019_9_23 to outbreaks_point?
the sql you posted is about a table called outbreaks, not outbreaks_points, irrelevant?

**Comment by gioman** [comment]
> The steps are:
@paolabfor 
no issues here, following your steps and data structure.

**Comment by paolabfor** [comment]
@gioman 

> is outbreak_2019_9_23 a postgis layer?

No, outbreak_2019_9_23 is a layer with the same structure (except for gid column) to outbreak_point.
outbreak and outbreak_point is the same layer.

**Comment by gioman** [comment]
>  QGIS 3.4.12 it works.

this means is fixed.
