### ISSUE TITLE
Topological editing not working when the data CRS is different from project CRS

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29648]
Author Name: **Sabin Kolarov** (Sabin Kolarov)
Original Redmine Issue: [21833](https://issues.qgis.org/issues/21833)
Affected QGIS version: 3.6.1
Redmine category:digitising

---
When the data CRS is different from project CRS the Topological Editing mode is not working. It is selecting only the vertex of the current line.
When data CRS and project CRS are the same, the tool works correctly. 

This bug was introduced in 3.4.5 and is also in 3.6.1.

**Comment by gioman** [comment]
Still true on master.

**Comment by haubourg** [comment]
ping @lbartoletti  Are you aware of this? This is highly critical IMO.

**Comment by gioman** [comment]
> This is highly critical IMO

it is indeed. I have also find another issue (I think is unreported, checking now): when digitizing a new line with snapping active is *not* possible to snap to the first vertex, so is not possible to digitize closed lines. The only workaround is to finish drawing the not closed line, then with the node tool move the last vertex and snap it to the first.

**Comment by haubourg** [comment]
@dsavary @ponceta do you confirm in your environnement ?

**Comment by ponceta** [comment]
@haubourg From what I saw just when using both swiss projections in QGIS, I would not recommend any edit on different projection systems in the same QGIS projects at all, at least for high precision works. This is not really a use case here. But this is indeed critical for QGIS.

**Comment by domlysz** [comment]
This problem still exists in 3.14, it took me a while to understand what's wrong because my project was defined to EPSG: 2154 and my layer to IGNF: LAMB93 but these two projections have exactly the same parameters !

**Comment by gioman** [comment]
Any chance to have this important bug fixed in the new round of supported bug fixing?

**Comment by lbartoletti** [comment]
I'll try

**Comment by Marty** [comment]
Just ran into this on QGIS 3.16.3.

**Comment by eshattow** [comment]
> > This is highly critical IMO
> 
> it is indeed. I have also find another issue (I think is unreported, checking now): when digitizing a new line with snapping active is _not_ possible to snap to the first vertex, so is not possible to digitize closed lines. The only workaround is to finish drawing the not closed line, then with the node tool move the last vertex and snap it to the first.

I'm experiencing this in 3.42.2; use case is that I want to snap to first vertex and use advanced digitizing mode to create a next line of some set distance parallel to an existing line in the project. What happens is the first vertex enters and the advanced construction mode is referencing some location very very far away. If instead of snapping I zoom in very carefully to start the first vertex, everything is normal. UX problem is: Snapping breaks advanced construction mode for the first vertex.

**Comment by lbartoletti** [comment]
Fixed by https://github.com/qgis/QGIS/pull/48853

**Comment by agiudiceandrea** [comment]
@lbartoletti, it seems this issue is still occurring: see https://github.com/qgis/QGIS/issues/51245.

**Comment by firefoxlover** [comment]
this bug is not fixed at all. my FR would be a popup that warns about different CRS, to make the layer inherit the Projects one

https://github.com/qgis/QGIS/issues/55540

**Comment by tobwen** [comment]
Still an issue in 3.40

**Comment by strk** [comment]
> Still an issue in 3.40

It's supposed to be fixed in 3.40.1 according to https://github.com/qgis/QGIS/pull/59346 -- do you have a more detailed version number ?

**Comment by strk** [comment]
@lbartoletti I'm reopening this, please let us know what to do with it

**Comment by agiudiceandrea** [comment]
@strk, actually https://github.com/qgis/QGIS/pull/59346 has been merged in release-3_40 branch on the 25th of November, so the fix will be available in QGIS 3.40.2 (while it is currently available in QGIS 3.41.0-Master).

**Comment by cpegel** [comment]
Can confirm this is (finally) fixed in QGIS 3.40.2.
