### ISSUE TITLE
Qt Designer with QGIS 3.4.8 custom widgets crashes when QWebEngineView is clicked

### ISSUE THREAD

**Issue by kylefelipe** [qgis/QGIS#30065]
Hi!
I have a issue with Qt Designer installed with QGis 3.4.8 (Standalone).
When try to use QWebEngineWidget to make a custom form, Qt Designer just close.

S.O: windows 7 Professional
QGIS: 3.4.8

**Comment by elpaso** [comment]
Would you be able to test current master? This bug may have been recently fixed by @nyalldawson

**Comment by pascatl** [comment]
I've tested with 3.7.0 (current master) installed with OSGeo4W, running with Qt 5.11.2. 
The Qt Designer is still crashing on trying to select the QWebEngineView widget

**Comment by kylefelipe** [comment]
@elpaso Using S.O windows i can't,  in the company we use only LTR versions, but testing this on Debian (qgis3.4) it works fine.

**Comment by elpaso** [comment]
@kylefelipe sorry I misread your bug report, I do not think that this issue is related with the recent fixes.

**Comment by rmarzocchi84** [comment]
when I try to import QWebEngineView

` from PyQt5.QtWebEngineWidgets import QWebEngineView
`


On Ubuntu 18.04 QGIS 3.4.11 compiled with 5.9.X the error is:
` ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'
`

On windows QGIS 3.4.X compiled with Qt5.11.X
`ImportError: QtWebEngineWidgets must be imported before a QCoreApplication instance is created
`

**Comment by rmarzocchi84** [comment]
Perhaps related to https://github.com/qgis/QGIS/issues/26048

**Comment by kylefelipe** [comment]
> when I try to import QWebEngineView
> 
> `from PyQt5.QtWebEngineWidgets import QWebEngineView`
> 
> On Ubuntu 18.04 QGIS 3.4.11 compiled with 5.9.X the error is:
> `ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'`
> 
> On windows QGIS 3.4.X compiled with Qt5.11.X
> `ImportError: QtWebEngineWidgets must be imported before a QCoreApplication instance is created `

I'm using QT Creator, to make custom forms to QGis, and webkit is not avaliable on it.

**Comment by gioman** [comment]
@kylefelipe is this still relevant in recent QGIS releases?

**Comment by kylefelipe** [comment]
I will try again

**Comment by kylefelipe** [comment]
I will try again
