### ISSUE TITLE
SRS transformation failures with PROJ 6.1.0

### ISSUE THREAD

**Issue by marisn** [qgis/QGIS#30569]
Steps to reproduce:
add multiple data sources (in my example – three ESRI Shapefiles) with different SRS'es.

Actual result:
> No transform available between EPSG:3059 and EPSG:4326
> No transform available between EPSG:3059 and EPSG:25884

Expected result:
no error.

Valgrind output contains usual chatter about Python, still there is something interesting during exiting from QGIS, (Invalid write of size 4 in pj_ctx_set_errno) still it has nothing to do with this issue.

Plain debug output is a bit more interesting (from 3.9, still the same issue is also observable in 3.8.0):

> src/core/providers/ogr/qgsogrprovider.cpp:1277 : (extent) [9ms] Starting get extent
> src/core/providers/ogr/qgsogrprovider.cpp:1321 : (extent) [7ms] Finished get extent
> src/core/providers/ogr/qgsogrprovider.cpp:1277 : (extent) [176ms] Starting get extent
> src/core/providers/ogr/qgsogrprovider.cpp:1321 : (extent) [1ms] Finished get extent
> src/core/qgscoordinatetransform_p.cpp:234 : (initialize) [410ms] Coordinate transformation failed to initialize!
> src/core/providers/ogr/qgsogrprovider.cpp:1277 : (extent) [3ms] Starting get extent
> src/core/providers/ogr/qgsogrprovider.cpp:1321 : (extent) [1ms] Finished get extent
> src/gui/qgsmapcanvas.cpp:506 : (refresh) [96ms] CANVAS refresh already scheduled
> src/core/qgscoordinatetransform.cpp:749 : (transformCoords) [901ms] Projection failed emitting invalid transform signal: forward transform of
> (inf, inf)
> (inf, inf)
> .....
> (inf, inf)
> (inf, inf)
> PROJ: +proj=pipeline +step +proj=unitconvert +xy_in=deg +xy_out=rad +step +proj=tmerc +lat_0=0 +lon_0=24 +k=0.9996 +x_0=500000 +y_0=0 +ellps=GRS80
> Error: latitude or longitude exceeded limits
> src/core/qgscoordinatetransform.cpp:750 : (transformCoords) [5ms] throwing exception
> src/core/qgscoordinatetransform.cpp:571 : (transformBoundingBox) [32ms] rethrowing exception
> src/gui/qgsmapcanvas.cpp:393 : (setDestinationCrs) [36ms] Transform error caught: forward transform of
> (inf, inf)
> (inf, inf)
> ....
> (inf, inf)
> (inf, inf)
> PROJ: +proj=pipeline +step +proj=unitconvert +xy_in=deg +xy_out=rad +step +proj=tmerc +lat_0=0 +lon_0=24 +k=0.9996 +x_0=500000 +y_0=0 +ellps=GRS80
> Error: latitude or longitude exceeded limits
> src/gui/qgsmapcanvas.cpp:405 : (setDestinationCrs) [13ms] refreshing after destination CRS changed
> src/gui/qgsmapcanvas.cpp:506 : (refresh) [1ms] CANVAS refresh already scheduled
> src/core/qgscoordinatetransform_p.cpp:282 : (proj_logger) [1162ms] proj_create_operations: At least one of the operation lacks a source and/or target CRS
> src/core/qgscoordinatetransform_p.cpp:234 : (initialize) [3424ms] Coordinate transformation failed to initialize!
> src/core/qgsmaprendererparalleljob.cpp:64 : (start) [50ms] QThreadPool max thread count is 2
> src/gui/qgsmapcanvas.cpp:512 : (refresh) [60ms] CANVAS refresh scheduling
> src/core/qgsmessagelog.cpp:29 : (logMessage) [415ms] 2019-07-05T22:15:57 Ziņas[2] No transform available between EPSG:3059 and EPSG:4326
> src/core/qgsmessagelog.cpp:29 : (logMessage) [539ms] 2019-07-05T22:15:58 Ziņas[2] No transform available between EPSG:3059 and EPSG:25884
> src/gui/qgsmapcanvas.cpp:731 : (stopRendering) [318ms] CANVAS stop rendering!
> src/core/qgsmaprendererparalleljob.cpp:115 : (cancelWithoutBlocking) [255ms] PARALLEL cancel at status 1
> src/core/qgsmaprendererparalleljob.cpp:64 : (start) [5400ms] QThreadPool max thread count is 2
> src/core/qgsmaprendererparalleljob.cpp:210 : (renderLayersFinished) [12809ms] PARALLEL layers finished
> src/core/qgsmaprenderercustompainterjob.cpp:338 : (drawLabeling) [296ms] [thread:0x9c85b9d0] Draw labeling took (seconds): 0.21
> src/core/qgsvectorlayerrenderer.cpp:281 : (drawRenderer) [452ms] [thread:0x9c5a60c0] Drawing of vector layer From_25884_to_3059_2ca512d3_8aa3_4d40_9f51_31e437e7ef2a canceled.

QGIS versija | 3.9.0-Master | QGIS koda revīzija | ad8174eeca
-- | -- | -- | --
Kompilēts priekš Qt | 5.12.3 | Darbina ar Qt | 5.12.3
Kompilēts priekš GDAL/OGR | 2.4.1 | Darbina ar GDAL/OGR | 2.4.1
Kompilēts priekš GEOS | 3.7.0-CAPI-1.11.0 | Darbina ar GEOS | 3.7.0-CAPI-1.11.0 673b9939
PostgreSQL klienta versija | 10.9 | SpatiaLite versija | 5.0.0-beta1
QWT versija | 6.1.3 | QScintilla2 versija | 2.11.1
Compiled against PROJ | 6.1.0 | Running against PROJ | Rel. 6.1.0, May 15th, 2019
Šī QGIS kopija raksta atkļūdošanas informāciju.
OS Version | Gentoo/Linux |   |

**Comment by nyalldawson** [comment]
I believe this one is already fixed -- can you try with the current master version? (I can't find a reference to ad8174eeca )

**Comment by marisn** [comment]
> I believe this one is already fixed -- can you try with the current master version? (I can't find a reference to ad8174eeca )

Sorry for late reply, it takes almost whole day to recompile QGIS. No, the issue is not fixed, it is still present. Tested with: f3dcd8211ec2fa8e636003ffe9936dae2eb8eb24

**Comment by nyalldawson** [comment]
What does

    projinfo -s EPSG:3059 -t EPSG:4326

output?

**Comment by marisn** [comment]
```
projinfo -s EPSG:3059 -t EPSG:4326
Candidate operations found: 1
-------------------------------------
Operation n°1:

unknown id, Inverse of Latvian Transverse Mercator + LKS92 to WGS 84 (1), 1 m, Latvia

PROJ string:
+proj=pipeline +step +proj=axisswap +order=2,1 +step +inv +proj=tmerc +lat_0=0 +lon_0=24 +k=0.9996 +x_0=500000 +y_0=-6000000 +ellps=GRS80 +step +proj=unitconvert +xy_in=rad +xy_out=deg +step +proj=axisswap +order=2,1

WKT2_2018 string:
CONCATENATEDOPERATION["Inverse of Latvian Transverse Mercator + LKS92 to WGS 84 (1)",
    SOURCECRS[
        PROJCRS["LKS92 / Latvia TM",
            BASEGEOGCRS["LKS92",
                DATUM["Latvia 1992",
                    ELLIPSOID["GRS 1980",6378137,298.257222101,
                        LENGTHUNIT["metre",1]]],
                PRIMEM["Greenwich",0,
                    ANGLEUNIT["degree",0.0174532925199433]],
                ID["EPSG",4661]],
            CONVERSION["Latvian Transverse Mercator",
                METHOD["Transverse Mercator",
                    ID["EPSG",9807]],
                PARAMETER["Latitude of natural origin",0,
                    ANGLEUNIT["degree",0.0174532925199433],
                    ID["EPSG",8801]],
                PARAMETER["Longitude of natural origin",24,
                    ANGLEUNIT["degree",0.0174532925199433],
                    ID["EPSG",8802]],
                PARAMETER["Scale factor at natural origin",0.9996,
                    SCALEUNIT["unity",1],
                    ID["EPSG",8805]],
                PARAMETER["False easting",500000,
                    LENGTHUNIT["metre",1],
                    ID["EPSG",8806]],
                PARAMETER["False northing",-6000000,
                    LENGTHUNIT["metre",1],
                    ID["EPSG",8807]]],
            CS[Cartesian,2],
                AXIS["northing (X)",north,
                    ORDER[1],
                    LENGTHUNIT["metre",1]],
                AXIS["easting (Y)",east,
                    ORDER[2],
                    LENGTHUNIT["metre",1]],
            ID["EPSG",3059]]],
    TARGETCRS[
        GEOGCRS["WGS 84",
            DATUM["World Geodetic System 1984",
                ELLIPSOID["WGS 84",6378137,298.257223563,
                    LENGTHUNIT["metre",1]]],
            PRIMEM["Greenwich",0,
                ANGLEUNIT["degree",0.0174532925199433]],
            CS[ellipsoidal,2],
                AXIS["geodetic latitude (Lat)",north,
                    ORDER[1],
                    ANGLEUNIT["degree",0.0174532925199433]],
                AXIS["geodetic longitude (Lon)",east,
                    ORDER[2],
                    ANGLEUNIT["degree",0.0174532925199433]],
            ID["EPSG",4326]]],
    STEP[
        CONVERSION["Inverse of Latvian Transverse Mercator",
            METHOD["Inverse of Transverse Mercator",
                ID["INVERSE(EPSG)",9807]],
            PARAMETER["Latitude of natural origin",0,
                ANGLEUNIT["degree",0.0174532925199433],
                ID["EPSG",8801]],
            PARAMETER["Longitude of natural origin",24,
                ANGLEUNIT["degree",0.0174532925199433],
                ID["EPSG",8802]],
            PARAMETER["Scale factor at natural origin",0.9996,
                SCALEUNIT["unity",1],
                ID["EPSG",8805]],
            PARAMETER["False easting",500000,
                LENGTHUNIT["metre",1],
                ID["EPSG",8806]],
            PARAMETER["False northing",-6000000,
                LENGTHUNIT["metre",1],
                ID["EPSG",8807]],
            ID["INVERSE(EPSG)",19990]]],
    STEP[
        COORDINATEOPERATION["LKS92 to WGS 84 (1)",
            VERSION["Vzd-Lva"],
            SOURCECRS[
                GEOGCRS["LKS92",
                    DATUM["Latvia 1992",
                        ELLIPSOID["GRS 1980",6378137,298.257222101,
                            LENGTHUNIT["metre",1]]],
                    PRIMEM["Greenwich",0,
                        ANGLEUNIT["degree",0.0174532925199433]],
                    CS[ellipsoidal,2],
                        AXIS["geodetic latitude (Lat)",north,
                            ORDER[1],
                            ANGLEUNIT["degree",0.0174532925199433]],
                        AXIS["geodetic longitude (Lon)",east,
                            ORDER[2],
                            ANGLEUNIT["degree",0.0174532925199433]],
                    ID["EPSG",4661]]],
            TARGETCRS[
                GEOGCRS["WGS 84",
                    DATUM["World Geodetic System 1984",
                        ELLIPSOID["WGS 84",6378137,298.257223563,
                            LENGTHUNIT["metre",1]]],
                    PRIMEM["Greenwich",0,
                        ANGLEUNIT["degree",0.0174532925199433]],
                    CS[ellipsoidal,2],
                        AXIS["geodetic latitude (Lat)",north,
                            ORDER[1],
                            ANGLEUNIT["degree",0.0174532925199433]],
                        AXIS["geodetic longitude (Lon)",east,
                            ORDER[2],
                            ANGLEUNIT["degree",0.0174532925199433]],
                    ID["EPSG",4326]]],
            METHOD["Geocentric translations (geog2D domain)",
                ID["EPSG",9603]],
            PARAMETER["X-axis translation",0,
                LENGTHUNIT["metre",1],
                ID["EPSG",8605]],
            PARAMETER["Y-axis translation",0,
                LENGTHUNIT["metre",1],
                ID["EPSG",8606]],
            PARAMETER["Z-axis translation",0,
                LENGTHUNIT["metre",1],
                ID["EPSG",8607]],
            OPERATIONACCURACY[1.0],
            ID["EPSG",1958]]],
    USAGE[
        SCOPE["unknown"],
        AREA["Latvia"],
        BBOX[55.67,19.06,58.09,28.24]]]

```

**Comment by nyalldawson** [comment]
Hmm - I'm stumped here. The projinfo output is correct, so qgis should be using the same operation.

**Comment by marisn** [comment]
> Hmm - I'm stumped here. The projinfo output is correct, so qgis should be using the same operation.

I did some more testing – the bug is not present if I add layers one by one in a slow way. If I add multiple layers simultaneously, it fails most of time. Thus this error message starts to look interesting, as I do not get it when there is no failure:
> src/core/qgscoordinatetransform_p.cpp:234 : (initialize) [410ms] Coordinate transformation failed to initialize!

Here is a log with QGIS_DEBUG=5. I'm just adding three shapefiles at the same time. Unfortunately I can not upload log the file to GitHub, thus it is here: http://www.gisnet.lv/~marisn/qgis_run.log

**Comment by nyalldawson** [comment]
Can you share the layers themselves?

**Comment by marisn** [comment]
Sure. Here they are: http://www.gisnet.lv/~marisn/QGIS_issue_30569.tar.gz
On my system it is enough to just open a project file containing any several layers with different CRS'es.

**Comment by nyalldawson** [comment]
@marisn 

I can only reproduce this when QGIS is using an older srs.db (generated using proj4). Can you remove all srs.db files and retest?

**Comment by marisn** [comment]
> @marisn
> 
> I can only reproduce this when QGIS is using an older srs.db (generated using proj4). Can you remove all srs.db files and retest?

At first I did `rm -rf /path/to/qgis/install && make clean`;
Then I compiled QGIS with proj 4.9.3 => no issues at all.
Then I repeated rm && make clean and compiled with proj 6.1.0 => fails as per this bug.
Then I did `find /path/to/qgis/install -name srs.db` and rm'ed the file => still the same failure.
Testing was done with 9345e9ea1a6092a4b2a89e2eb24aa78032733429

I can do some more tests, but I don't have ideas what exactly to try. Is it possible to compile QGIS to run in a single thread?

**Comment by marisn** [comment]
Unfortunately I still can reproduce the issue with 6d3b1574b4f90d61a55017b49714ff42d8ffdf71

I was trying to create a test case but my C++ knowledge is too weak to do so thus a helping hand would be right on time. I was trying following code, but sPoly is not transformed and thus it fails:
```
diff --git a/tests/src/core/testqgscoordinatetransform.cpp b/tests/src/core/testqgscoordinatetransform.cpp
index ebc8bf706e..31c243b1f4 100644
--- a/tests/src/core/testqgscoordinatetransform.cpp
+++ b/tests/src/core/testqgscoordinatetransform.cpp
@@ -17,6 +17,8 @@
 #include "qgscoordinatetransform.h"
 #include "qgsapplication.h"
 #include "qgsrectangle.h"
+#include "qgsgeometry.h"
+#include "qgspolygon.h"
 #include "qgscoordinatetransformcontext.h"
 #include "qgsproject.h"
 #include <QObject>
@@ -40,6 +42,7 @@ class TestQgsCoordinateTransform: public QObject
     void scaleFactor_data();
     void transform_data();
     void transform();
+    void transformLKS();
 
   private:
 
@@ -328,6 +331,22 @@ void TestQgsCoordinateTransform::transform_data()
       << QgsCoordinateReferenceSystem::fromEpsgId( 4326 )
       << QgsCoordinateReferenceSystem::fromEpsgId( 4164 )
       << 145.510966 <<  -37.961741 << static_cast< int >( QgsCoordinateTransform::ReverseTransform ) <<  145.512750 <<  -37.961375 << 0.0001;
+  QTest::newRow( "From LKS92/TM to Baltic93/TM" )
+      << QgsCoordinateReferenceSystem::fromEpsgId( 3059 )
+      << QgsCoordinateReferenceSystem::fromEpsgId( 25884 )
+      << 725865.850 << 198519.947 << static_cast< int >( QgsCoordinateTransform::ForwardTransform ) << 725865.850 << 6198519.947 << 0.001;
+  QTest::newRow( "From LKS92/TM to Baltic93/TM (reverse)" )
+      << QgsCoordinateReferenceSystem::fromEpsgId( 3059 )
+      << QgsCoordinateReferenceSystem::fromEpsgId( 25884 )
+      << 725865.850 << 6198519.947 << static_cast< int >( QgsCoordinateTransform::ReverseTransform ) << 725865.850 << 198519.947 << 0.001;
+  QTest::newRow( "From LKS92/TM to WGS84" )
+      << QgsCoordinateReferenceSystem::fromEpsgId( 3059 )
+      << QgsCoordinateReferenceSystem::fromEpsgId( 4326 )
+      << 725865.850 << 198519.947 << static_cast< int >( QgsCoordinateTransform::ForwardTransform ) << 27.61113711 << 55.87910378 << 0.00000001;
+  QTest::newRow( "From LKS92/TM to WGS84 (reverse)" )
+      << QgsCoordinateReferenceSystem::fromEpsgId( 3059 )
+      << QgsCoordinateReferenceSystem::fromEpsgId( 4326 )
+      << 27.61113711 << 55.87910378 << static_cast< int >( QgsCoordinateTransform::ReverseTransform ) << 725865.850 << 198519.947 << 0.001;
 
 }
 
@@ -392,5 +411,29 @@ void TestQgsCoordinateTransform::transformBoundingBox()
   QVERIFY( errorObtained );
 }
 
+void TestQgsCoordinateTransform::transformLKS()
+{
+  QgsCoordinateReferenceSystem LKS92;
+  LKS92.fromEpsgId( 3059 );
+  QgsCoordinateReferenceSystem Baltic93;
+  Baltic93.fromEpsgId( 25884 );
+  QgsCoordinateReferenceSystem WGS84;
+  WGS84.fromEpsgId( 4326 );
+
+  QgsCoordinateTransform Lks2Balt( LKS92, Baltic93, QgsProject::instance() );
+  QgsCoordinateTransform Lks2Wgs( LKS92, WGS84, QgsProject::instance() );
+
+  QPolygonF sPoly = QgsGeometry::fromWkt( QStringLiteral( "Polygon (( 725865.850 198519.947, 363511.181 263208.769, 717694.697 333650.333, 725865.850 198519.947 ))" ) ).asQPolygonF();
+
+  Lks2Balt.transformPolygon( sPoly, QgsCoordinateTransform::ForwardTransform );
+    
+  QGSCOMPARENEAR( sPoly.at( 0 ).x(), 725865.850, 0.001 );
+  QGSCOMPARENEAR( sPoly.at( 0 ).y(), 6198519.947, 0.001 );
+  QGSCOMPARENEAR( sPoly.at( 1 ).x(), 363511.181, 0.001 );
+  QGSCOMPARENEAR( sPoly.at( 1 ).y(), 6263208.769, 0.001 );
+  QGSCOMPARENEAR( sPoly.at( 2 ).x(), 717694.697, 0.001 );
+  QGSCOMPARENEAR( sPoly.at( 2 ).y(), 6333650.333, 0.001 );
+}
+
 QGSTEST_MAIN( TestQgsCoordinateTransform )
 #include "testqgscoordinatetransform.moc"
```

**Comment by nyalldawson** [comment]
@marisn Try this:


```
QgsCoordinateReferenceSystem LKS92 = QgsCoordinateReferenceSystem::fromEpsgId( 3059 );
  QVERIFY( LKS92.isValid() );
  QgsCoordinateReferenceSystem Baltic93 = QgsCoordinateReferenceSystem::fromEpsgId( 25884 );
  QVERIFY( Baltic93.isValid() );
  QgsCoordinateReferenceSystem WGS84 = QgsCoordinateReferenceSystem::fromEpsgId( 4326 );
  QVERIFY( WGS84.isValid() );

  QgsCoordinateTransform Lks2Balt( LKS92, Baltic93, QgsProject::instance() );
  QVERIFY( Lks2Balt.isValid() );
  QgsCoordinateTransform Lks2Wgs( LKS92, WGS84, QgsProject::instance() );
  QVERIFY( Lks2Wgs.isValid() );

  QPolygonF sPoly = QgsGeometry::fromWkt( QStringLiteral( "Polygon (( 725865.850 198519.947, 363511.181 263208.769, 717694.697 333650.333, 725865.850 198519.947 ))" ) ).asQPolygonF();

  Lks2Balt.transformPolygon( sPoly, QgsCoordinateTransform::ForwardTransform );

  QGSCOMPARENEAR( sPoly.at( 0 ).x(), 725865.850, 0.001 );
  QGSCOMPARENEAR( sPoly.at( 0 ).y(), 6198519.947, 0.001 );
  QGSCOMPARENEAR( sPoly.at( 1 ).x(), 363511.181, 0.001 );
  QGSCOMPARENEAR( sPoly.at( 1 ).y(), 6263208.769, 0.001 );
  QGSCOMPARENEAR( sPoly.at( 2 ).x(), 717694.697, 0.001 );
  QGSCOMPARENEAR( sPoly.at( 2 ).y(), 6333650.333, 0.001 );
```

For reference: both tests pass for me on master.

**Comment by marisn** [comment]
@nyalldawson Thanks for teh codes. Unfortunately I was not able to come up with unit test that would cause failure but I still observe failure when adding Shapefiles to an empty project. I did a lot of hand banging and came up with (almost) nothing. I will downgrade my system to Proj 4.9.3 and hope the issue will solve itself in the future.

Here is summary of my findings (tested with Proj 6.1.1 GCC 9.1.0 qtcore 5.12.4 QGIS 051e315a69c5ca57c1c4d99c2e3529592abf300b).
When I add three shapefiles, first one processed is EPSG:25884, then comes EPSG:3059 and then EPSG:4326. In such order the EPSG:3059 always fails. If I add one by one, everything is fine thus the requirement to add all three simultaneously (timing sensitive bug).

There are two identical calls to `QgsCoordinateTransformPrivate::calculateTransforms` with source being EPSG:3059 and destination EPSG:4326. Although both seem to be identical, second one fails. First call originates in datumtransformdialog and succeeds. Second call originates in `QgsMapSettings::layerExtentToOutputExtent` and fails.
I can't provide line numbers as I have added gazzilion of printf's to code + I'm on a mobile internet and thus browsing github is PITA.

Here are comments on second call:
Layer EPSG_3059 has extent: minX:506109.246784 minY:310663.323739 maxX:506678.715609 maxY:311100.971076
QgsMapSettings::layerTransform l->crs:EPSG:3059 dest_crs:EPSG:4326
QgsCoordinateTransformPrivate::calculateTransforms s:EPSG:3059 d:EPSG:4326
QgsCoordinateTransform::QgsCoordinateTransform bypass `setFromCache` call and always go for `d->initialize()` <--- setFromCache does not affect outcome as it fails in either case
QgsCoordinateTransformPrivate::threadLocalProjData goes to: `if ( !transform ) // fallback on default proj pathway`
--->PROJ land starts here
CoordinateOperationFactory::Private::createOperations(LKS92 / Latvia TM (EPSG:3059),WGS 84 (EPSG:4326))
CoordinateOperationFactory::Private::createOperations `if (context.context->getAuthorityFactory() &&`
CoordinateOperationFactory::Private::createOperations findOpsInRegistryDirect res.size:0
CoordinateOperationFactory::Private::createOperations !sourceCRS->_isEquivalentTo(targetCRS.get())
CoordinateOperationFactory::Private::createOperations resFromInverse.size:0
CoordinateOperationFactory::Private::createOperations !sameGeodeticDatum &&
CoordinateOperationFactory::Private::createOperations !sameGeodeticDatum &&. resWithIntermediate.size:0
CoordinateOperationFactory::Private::createOperations doFilterAndCheckPerfectOp
CoordinateOperationFactory::Private::createOperations `if (derivedSrc) {` res.size:0
---> So far res is empty. Call to: `auto opFirst = derivedSrc->derivingConversion()->inverse();`
Conversion::inverse methodEPSGCode:9807
Conversion::inverse InverseConversion::create
InverseConversion::create forward=0
---> Call complete: `auto opFirst = derivedSrc->derivingConversion()->inverse();`
CoordinateOperationFactory::Private::createOperations derivedSrc opFirst s=1 t=1
-----------------------------------------------------------------------------------------------^^^^^^^^
---> source and target both are nullptr although they shouldn't!
---> the rest doesn't matter as `res` already contains operation with CRS's being nullptr
---> Call to: ```auto opsSecond = 
            createOperations(derivedSrc->baseCRS(), targetCRS, context);```
CoordinateOperationFactory::Private::createOperations(LKS92 (EPSG:4661),WGS 84 (EPSG:4326))
CoordinateOperationFactory::Private::createOperations context.context->getAuthorityFactory() &&
CoordinateOperationFactory::Private::createOperations findOpsInRegistryDirect res.size:1
CoordinateOperationFactory::Private::createOperations !sourceCRS->_isEquivalentTo(targetCRS.get())
CoordinateOperationFactory::Private::createOperations resFromInverse.size:0
CoordinateOperationFactory::Private::createOperations context.context->getAuthorityFactory() geodSrc && geodDst
CoordinateOperationFactory::Private::createOperations geodSrc && geodDst && !derivedSrc && !derivedDst
CoordinateOperationFactory::Private::createOperations geogSrc && geogDst
CoordinateOperationFactory::Private::createOperationsGeogToGeog not src_pm.getSIValue() s=0 t=0
createBallparkGeographicOffset Ballpark geographic offset from LKS92 to WGS 84
createBallparkGeographicOffset 2d
ConcatenatedOperation::createComputeMetadata
ConcatenatedOperation::createComputeMetadata Single s=0 t=0
---> Call complete: ```auto opsSecond = 
            createOperations(derivedSrc->baseCRS(), targetCRS, context);```
CoordinateOperationFactory::Private::createOperations derivedSrc opSecond s=0 t=0
---> Call to: ```res.emplace_back(ConcatenatedOperation::createComputeMetadata(
                    {opFirst, opSecond}, !allowEmptyIntersection));```
ConcatenatedOperation::createComputeMetadata
ConcatenatedOperation::createComputeMetadata hasBallparkTransformation:0 s=1 t=1
ConcatenatedOperation::createComputeMetadata hasBallparkTransformation:0 s=0 t=0
ConcatenatedOperation::create i:0 s=1 t=1
---> As operationsIn[i]->sourceCRS() and operationsIn[i]->targetCRS() both are null pointes, we go directly to:
    ```if (l_sourceCRS == nullptr || l_targetCRS == nullptr) {
            throw InvalidOperation("At least one of the operation lacks a "
                                   "source and/or target CRS");
        }```
Exception bubbles up to proj_create_operations.

Here is output of the first call (without comments). Note – it is identical to the second call with one exception -> `auto opFirst = derivedSrc->derivingConversion()->inverse();` has not resulted in src or target being nullptr.
CoordinateOperationFactory::Private::createOperations(LKS92 / Latvia TM (EPSG:3059),WGS 84 (EPSG:4326))
CoordinateOperationFactory::Private::createOperations context.context->getAuthorityFactory() &&
CoordinateOperationFactory::Private::createOperations findOpsInRegistryDirect res.size:0
CoordinateOperationFactory::Private::createOperations !sourceCRS->_isEquivalentTo(targetCRS.get())
CoordinateOperationFactory::Private::createOperations resFromInverse.size:0
CoordinateOperationFactory::Private::createOperations !sameGeodeticDatum &&
CoordinateOperationFactory::Private::createOperations !sameGeodeticDatum &&. resWithIntermediate.size:0
CoordinateOperationFactory::Private::createOperations doFilterAndCheckPerfectOp
CoordinateOperationFactory::Private::createOperations derivedSrc res.size:0
Conversion::inverse methodEPSGCode:9807
Conversion::inverse InverseConversion::create
InverseConversion::create forward=0
CoordinateOperationFactory::Private::createOperations derivedSrc opFirst s=0 t=0
CoordinateOperationFactory::Private::createOperations(LKS92 (EPSG:4661),WGS 84 (EPSG:4326))
CoordinateOperationFactory::Private::createOperations context.context->getAuthorityFactory() &&
CoordinateOperationFactory::Private::createOperations findOpsInRegistryDirect res.size:1
CoordinateOperationFactory::Private::createOperations !sourceCRS->_isEquivalentTo(targetCRS.get())
CoordinateOperationFactory::Private::createOperations resFromInverse.size:0
CoordinateOperationFactory::Private::createOperations context.context->getAuthorityFactory() geodSrc && geodDst
CoordinateOperationFactory::Private::createOperations geodSrc && geodDst && !derivedSrc && !derivedDst
CoordinateOperationFactory::Private::createOperations geogSrc && geogDst
CoordinateOperationFactory::Private::createOperationsGeogToGeog not src_pm.getSIValue() s=0 t=0
createBallparkGeographicOffset Ballpark geographic offset from LKS92 to WGS 84
createBallparkGeographicOffset 2d
ConcatenatedOperation::createComputeMetadata
ConcatenatedOperation::createComputeMetadata Single s=0 t=0
CoordinateOperationFactory::Private::createOperations derivedSrc opSecond s=0 t=0
ConcatenatedOperation::createComputeMetadata
ConcatenatedOperation::createComputeMetadata hasBallparkTransformation:0 s=0 t=0
ConcatenatedOperation::createComputeMetadata hasBallparkTransformation:0 s=0 t=0
ConcatenatedOperation::create i:0 s=0 t=0
ConcatenatedOperation::create i:1 s=0 t=0
ConcatenatedOperation::createComputeMetadata complete. op=0
CoordinateOperationFactory::Private::createOperations derivedSrc opSecond s=0 t=0
ConcatenatedOperation::createComputeMetadata
ConcatenatedOperation::createComputeMetadata hasBallparkTransformation:0 s=0 t=0
ConcatenatedOperation::createComputeMetadata hasBallparkTransformation:1 s=0 t=0
ConcatenatedOperation::create i:0 s=0 t=0
ConcatenatedOperation::create i:1 s=0 t=0
ConcatenatedOperation::createComputeMetadata complete. op=0
CoordinateOperationFactory::Private::createOperations derivedSrc return res.size:2
ConcatenatedOperation::createComputeMetadata
ConcatenatedOperation::createComputeMetadata hasBallparkTransformation:0 s=0 t=0
ConcatenatedOperation::createComputeMetadata hasBallparkTransformation:0 s=0 t=0
ConcatenatedOperation::createComputeMetadata hasBallparkTransformation:0 s=0 t=0
ConcatenatedOperation::create i:0 s=0 t=0
ConcatenatedOperation::create i:1 s=0 t=0
ConcatenatedOperation::create i:2 s=0 t=0
ConcatenatedOperation::create i:3 s=0 t=0
ConcatenatedOperation::createComputeMetadata complete. op=0

**Comment by rouault** [comment]
I've not followed this thread closely but as a remainder: a PROJ context must be used by one single thread at a time. If this is followed, I can't think of where there would be thread-safety issues in PROJ

**Comment by saberraz** [comment]
I am having the same issue for:
```
No transform is available between EPSG:3035 [ETRS89-extended / LAEA Europe] and EPSG:5514 [S-JTSK / Krovak East North].
proj_create_operations: At least one of the operation lacks a source and/or target CRS
```
Attached is my projinfo for the two CRSs.
[projonfo.txt](https://github.com/qgis/QGIS/files/3708235/projonfo.txt)

Here is my build:
![image](https://user-images.githubusercontent.com/2649047/66496659-2c9c5800-eab3-11e9-9c35-26daad8dcbb5.png)

And link to the project:

**Comment by dicorynia** [comment]
Hi
Same problem with QGIS 3.10.0 with a project created with 3.6.0 :
"No transform available between EPSG:3035 and EPSG:2154" and the (raster) layer in 3035 does not reproject in 2154 (the project's projection)

````

Version de QGIS
3.10.0-A Coruña
Révision du code
6ffa89eb3e
Compilé avec Qt
5.11.2
Utilisant Qt
5.11.2
Compilé avec GDAL/OGR
3.0.2
Utilisé avec GDAL/OGR
3.0.2
Compilé avec GEOS
3.8.0-CAPI-1.13.1
Utilisé avec GEOS
3.8.0-CAPI-1.13.1 
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
Version du client PostgreSQL
11.5
Version de SpatiaLite
4.3.0
Version de QWT
6.1.3
Version de QScintilla2
2.10.8
Compilé avec PROJ
6.2.1
Fonctionne avec PROJ
Rel. 6.2.1, November 1st, 2019
OS Version
Windows 7 SP 1 (6.1)
````

**Comment by happydeb** [comment]
Okay, see my resolved issue 33009 it may be related.

**Comment by happydeb** [comment]
@marisn  There is also this #32969 @Bernd_Vogelgesang  Snapping not possible with new project with new layer, related?

And @Gioman #32977 @PedroVenancio  "topological editing" only works if layer CRS and project CRS match. And the issue I wrote #33009 33009 Basemaps don't load on project open. 3.11  has a new popup asking me to transform layers, btw, GeoCRS and projected, so I had to change the CRS of my project,.

Changing the project CRS initiates the new 3.11 popup that says to transform my layers, but they are just transformed not reprojected, and I don't want to convert a projected layer to a geographic one. 

So I convert my layer to geographic and now snapping and splitting works! My client may not know the difference and I HAVE to finish this project (and sleep) but I think this may be more than my usual "user error". As I said before, I only know how to drive QGIS not fix it.

I have all the error logs if you want/need to see them. Stuff about resolving "bounding box" for the background layer and transform error can't normalize between projected and geographic CRSs.
Any hand holding to get me through this and into using this new upgrade which I desperately need (it has the ability to rasterize my geotagged photos as points with direction markers!) will be great. 

Apparently I cannot can not uninstall 3.10 due new way of installing the upgrade in Windows with OSGeo4Whatever... (3.10.0-2-Setup) or I would have gone to 3.6 or 3.8 which is supposed to have the needed photo feature upgrade.

@nyalldawson I'm sorry but I don't understand #1736 or what to do about it.

Thanks!

**Comment by gioman** [comment]
> Changing the project CRS initiates the new 3.11 popup that says to transform my layers, but they are just transformed not reprojected, and I don't want to convert a projected layer to a geographic one.

...
...
...

@happydeb stick to 3.4, in QGIS 3.10 there have been major changes in the projections managament/handling and this has issues that need to be addressed.

**Comment by saberraz** [comment]
@gioman this is also affecting QGIS 3.4.13 under Windows (it is now using proj 6.x). So, the only option is to downgrade to 3.4.12

**Comment by gioman** [comment]
>  this is also affecting QGIS 3.4.13 under Windows (it is now using proj 6.x). So, the only option is to downgrade to 3.4.12

@saberraz JC...

**Comment by saberraz** [comment]
QGIS 3.4.12 (green polygon EPSG:27700 BG in EPSG:3857):
![image](https://user-images.githubusercontent.com/2649047/69413948-aa39c180-0d09-11ea-9660-92e9f8718b70.png)

Same layers in QGIS 3.4.13:
![image (8)](https://user-images.githubusercontent.com/2649047/69414003-c5a4cc80-0d09-11ea-970e-8c6b3150018a.png)

**Comment by gioman** [comment]
> Same layers in QGIS 3.4.13:

so basically we are now shipping a LTR on windows that is mostly useless?

**Comment by saberraz** [comment]
Pretty much. With LTR, we should stick with the same major versions of libraries through its lifecycle (e.g. gdal 2.x and proj 5.x for QGIS 3.4 in this case). We have hardly any testers for QGIS master on Windows. Doubt anyone actually tests qgis-ltr-dev releases on Windows.

**Comment by gioman** [comment]
@saberraz we should raise the issue on the dev list? psc? ping some developer here?

**Comment by saberraz** [comment]
Good idea...but I guess it is extra work for package managers to build multiple versions of QGIS with multiple versions of dependencies.

**Comment by DelazJ** [comment]
> Doubt anyone actually tests qgis-ltr-dev releases on Windows

I do 😄 . But installation is broken since last release (http://osgeo-org.1560.x6.nabble.com/New-QGIS-windows-packages-was-GeoPDF-creation-greyed-out-tp5421559p5421637.html)

**Comment by gioman** [comment]
> Good idea...but I guess it is extra work for package managers to build multiple versions of QGIS with multiple versions of dependencies.

well at least on the download page the standalone installer link could point to 3.4.12 until this is solved.

**Comment by saberraz** [comment]
> I do 

hehehe, a brave move. I just see it in the package manager and make sure not to tick it instead of qgis-ltr or qgis-dev!

**Comment by nyalldawson** [comment]
Upstream issue - see https://github.com/OSGeo/PROJ/pull/1746
