### ISSUE TITLE
QGIS crashes when exporting high resolution print layout

### ISSUE THREAD

**Issue by Juddium** [qgis/QGIS#31100]
## User Feedback

Trying to export a large image (Arch D) at a high DPI (3000)

## Report Details

*Crash ID*: 239af1d404f999d627cb4429527369bc2ee36e69

*Stack Trace*
<pre>
memmove :
QVectorPath::convertToPainterPath :
QVectorPath::convertToPainterPath :
QVectorPath::convertToPainterPath :
QVectorPath::convertToPainterPath :
QVectorPath::convertToPainterPath :
QRasterPaintEngine::rasterBuffer :
QRasterPaintEngine::rasterBuffer :
QRasterPaintEngine::fill :
QPaintEngineEx::draw :
QPaintEngineEx::drawPath :
QgsFillSymbolLayer::_renderPolygon :
QgsSimpleFillSymbolLayer::renderPolygon :
QgsFillSymbol::renderPolygonUsingLayer :
QgsFillSymbol::renderPolygon :
QgsLayoutItemPage::draw :
QgsLayoutItem::paint :
QGraphicsScene::dragMoveEvent :
QGraphicsItem::dragMoveEvent :
QGraphicsEffectSource::draw :
QgsLayoutEffect::draw :
QGraphicsScene::drawItems :
QGraphicsScene::drawItems :
QGraphicsScene::render :
QgsLayoutExporter::renderRegion :
QgsLayoutExporter::renderRegionToImage :
QgsLayoutExporter::renderPageToImage :
QgsLayoutExporter::createImage :
QgsLayoutExporter::exportToImage :
QgsVertexEditorModel::flags :
QMetaObject::activate :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
DispatchMessageW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.8.1-Zanzibar
QGIS code revision: dcd95cc648
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763

**Comment by roya0045** [comment]
You might be running out of memory, at least this is what the log says.

Now I doubt this is a qgis issue if you are hitting the limit of your system.

**Comment by Juddium** [comment]
How much does it need? I have 16Gb with nothing else going on in the background and it still crashes like this

**Comment by gioman** [comment]
I must say that this reminds me very well that this issue if affecting us  since... I can remember (so at least 10 years). Usually with the same project/data/configs printing/exporting on Linux works as expected. You may want to give it a try to check is still the case.

**Comment by Juddium** [comment]
I actually did try it on Linux Mint 19; for whatever reason, QGIS only used about 1gb of memory when exporting and would complain instantly whenever I tried to increase the DPI of being out of memory. On Windows I can export the configuration at about 1500 DPI without crashing (I still need it to be higher), but on Mint I can't get above 1000 DPI without out-of-memory warnings.

I set up dual booting specifically to get QGIS to work properly 😛 couldn't for the life of me find why QGIS limited its ram usage.

**Comment by nextstopsun** [comment]
I've got same bug with QGIS 3.x on Linux, Mac OS and Windows. 
Tried on machines with lots of RAM.
I'm exporting at 300 - 600 dpi (not at 3000), but sizes of Layouts are bigger (i.e. 280x280cm). So pixel-wise it's quite a big raster.  
QGIS either crashes or leaves a part of exported image blank.
Tried on all versions up to 3.8.1, with PNG, Tiff and PDF export formats. 

I've asked @nyalldawson some time ago about this issue and looks like it's somehow related to Qt. 
Not sure, though.

It'd be great if someone could fix this long-standing bug.

**Comment by Juddium** [comment]
I was able to get a fairly high DPI PDF, unfortunately I need it to be an image format for editing/printing

**Comment by roya0045** [comment]
> I was able to get a fairly high DPI PDF, unfortunately I need it to be an image format for editing/printing

Exporting to jpg or png failed?

**Comment by Juddium** [comment]
Yes, both failed

**Comment by andreasneumann** [comment]
I wouldn't export high resolution output to JPEG anyway.

JPEG has a size limit at 65535x65535 pixels (see https://en.wikipedia.org/wiki/JPEG). In addition, JPEG is a lossy format not well suited for printing.

**Comment by nextstopsun** [comment]
If this is an underlying Qt bug, it'd be great to have an internal "tiling" mechanism that renders image parts and then merges them to get the needed output.

**Comment by Juddium** [comment]
I knew JPEG is a lossy format, however the crash happens with TIFF as well. JPEG and TIFF are the 2 file types my printing software uses (because reasons), so these are the two that I need most to work.

**Comment by LeadNoodle** [comment]
If I do project-> export map as image, and try to export a high res image it just crashes, which I assume is part if this same issue. 3.8, 3.4, and if I remember correctly, numerous versions before. It gets to just below 12GB memory usage before crashing. I have 32GB of RAM with plenty free at the point of crashing. This happens with Tiff or PNG.

**Comment by Juddium** [comment]
As an update, I doubled the RAM I have (from 16GB to 32GB) and tried exporting again at a higher resolution. Same error occurred. After some testing, it appears anything 20000x20000 pixels and higher causes the crash; as long as I drop the DPI enough to stay below that pixel limit it will export without crashing.

**Comment by nyalldawson** [comment]
Fixed upstream in Qt 5.12.4

**Comment by marnec** [comment]
Still having this problem: 
QGIS 3.14.15-Pi 64bit
OS: Windows 10 Professional Version 10.0.19041 Build 19041
Export Image 24.000 X 24.000 > crash
RAM: 32GB
RAM occupied at crash (total: 13GB, qgis: around 4GB)

With an export of a 21.000 x 21.000 image everyhting worked smoothly

**Comment by gioman** [comment]
> Still having this problem:
> QGIS 3.14.15-Pi 64bit

@marnec which still uses QT 5.11

**Comment by marnec** [comment]
Oh ok, thx for the heads up. Do someone has any idea when Qgis will adopt Qt 5.12.4?

**Comment by Kivilahti** [comment]
I have the same issue.  Based on dates, QT fix was done 1 year ago?  Any ETA for qgis?

**Comment by roya0045** [comment]
https://github.com/qgis/QGIS/pull/38869#issuecomment-695755891
