### ISSUE TITLE
CRS for imported MapInfo / ArcGIS file not correct

### ISSUE THREAD

**Issue by ttocsa** [qgis/QGIS#33243]
I have noticed issues when bringing in spatial files created in MapInfo and ArcGIS. 

1. When a mid/mif file is created in MapInfo and the projection set as MGA Zone 56 (GDA 94), and is then brought into QGIS, QGIS sets the CRS as EPSG:5552 - PNG94 / PNGMG94 zone 56

2. When a .shp file is created in ArcGIS in GDA2020_MGA_Zone_56 , in QGIS it sets it again as EPSG:5552 - PNG94 / PNGMG94 zone 56

Note when a .shp file is created in ArcGIS in GDA_1994_MGA_Zone_56 , it is brought into QGIS correctly as EPSG:28356 - GDA94 / MGA zone 56

**Comment by nyalldawson** [comment]
This was a gdal issue -- should be fixed when the next gdal release is made

**Comment by ttocsa** [comment]
I've just upgraded to QGIS 3.10.1 and the issue remains at present.

**Comment by nyalldawson** [comment]
Yes, you need to wait for 3.10.2 which will hopefully include the next round of GDAL releases

**Comment by JuanPufleau** [comment]
I'm using QGIS 3.10.4, and still experiencing the same problem.

**Comment by gioman** [comment]
> I'm using QGIS 3.10.4, and still experiencing the same problem.

@JuanPufleau 

on what platform?

**Comment by nyalldawson** [comment]
It's still waiting on a gdal release
