### ISSUE TITLE
QGIS prompting for datum transformation for first dataset added to map

### ISSUE THREAD

**Issue by nickrsan** [qgis/QGIS#33838]
**Describe the bug**
In QGIS 3.10.0 on Windows 10, I'm getting a new prompt when adding vector data in a coordinate system that's not based on WGS84 asking for the coordinate system transformation. I've tested with a clean profile and with two datasets stored as shapefiles and geopackages. The data I was using uses a NAD83 datum. In each case, upon loading the first dataset, QGIS prompts me to select a datum transformation even though I have the option set in the QGIS options to adopt the coordinate system of the first layer added to the map. My expectation would be that it would not prompt me for a transformation because it would use the coordinate system directly and no datum transformation is needed. The transformation stays attached to the map even though the map's coordinate system correctly adopts the dataset's coordinate system, which seems like it could lead to surprising behavior.

**How to Reproduce**
1. Open new QGIS project
2. Add any vector data not in WGS84 datum
3. Get prompted for datum transformation
4. Fill out and close window, go to project properties and note that coordinate system is correctly set to dataset's coordinate system, but transformation remains attached.

**QGIS and OS versions**

QGIS version | 3.10.0-A Coruña | QGIS code revision | 6ffa89eb3e
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.0.2 | Running against GDAL/OGR | 3.0.2
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.2.1 | Running against PROJ | Rel. 6.2.1, November 1st, 2019
OS Version | Windows 10 (10.0)
Active python plugins | db_manager; MetaSearch; processing

**Comment by nyalldawson** [comment]
This is expected behaviour - there's multiple possible transforms (mathematical operations) to use when projecting between the co-ordinate systems, and qgis needs a user to make the correct choice of these based on their particular project.

**Comment by nickrsan** [comment]
Hi Nyall,

Thanks for the quick response. I would understand that behavior if there was other data in the map, or a manually set coordinate system in the empty map, but this is on a brand new map with no other data. On my profile, QGIS is set to take the coordinate system of the first dataset I add. I don't believe there's anything to transform because the map should be taking on the coordinate system of the data, not trying to reproject the data into another coordinate system. It seems to have set itself as WGS84 and wants me to select a transformation, but shouldn't it be just forgetting about WGS84 and setting the coordinate system of the first dataset I add? I believe this was the behavior in previous versions.

**Comment by nyalldawson** [comment]
Ah, I understand now!

**Comment by gioman** [comment]
> Ah, I understand now!

@nyalldawson he runs 3.10.0, maybe this is something already fixed in 3.10.1?

**Comment by nickrsan** [comment]
@gioman - I considered the same thing  - I looked for recently closed tickets that indicated an intentional change, but didn't see anything. I'll upgrade and confirm it's still an issue, then report back here.

**Comment by gioman** [comment]
>  I'll upgrade and confirm it's still an issue, then report back here.

@nickrsan no need, I have noticed what you describe also on master.

**Comment by nickrsan** [comment]
OK, it occurs in 3.10.2 as well, just tested - same system as above, only changes were to restore original profile and upgrade to 3.10.2. I'm attaching a zipped shapefile that should reproduce the behavior - nothing special about it except that it's in NAD83 GCS - happens with other formats and data as well. Thanks!
[navarro_streams.zip](https://github.com/qgis/QGIS/files/4088748/navarro_streams.zip)

**Comment by nickrsan** [comment]
Oh, just saw your comment about having seen the same thing in master. Well, now we have one more data point anyway :) - thanks!

**Comment by gioman** [comment]
@nickrsan this is fixed in the latest builds, correct?

**Comment by roya0045** [comment]
Feedback?

**Comment by gioman** [comment]
Closing for lack of feedback.
