### ISSUE TITLE
QGIS crashes when reading with browser from GRASS private mapset 

### ISSUE THREAD

**Issue by MonicaRM** [qgis/QGIS#35344]
In the institution I am working we have QGIS version 3.10.2-A Coruña and GRASS GIS 7,8 installed in a linux server. This QGIS installation has also the GRASS plugin installed. But we have been having issues when trying to add a GRASS vector layer from the Qgis browser. If the vector layer is in the Permanent mapset then it goes well, we can add the layer from the Browser but not if the mapset is from a private mapset (the one own by the user). I have a mapset with my name and I can't add to the QGIS  the GRASS data from my mapset, but I created a new mapset and under this is the Permanent mapset and from here I can browse the data. 
I have just problems with vector not with rasters. I am using a windows 10 machine and I connect to the server using X2GO.  
Here comes an example of a vector layer that was added from the permanent mapset without problems
![grass1](https://user-images.githubusercontent.com/11677890/77548731-396d0680-6eaf-11ea-9d53-88b1e3c7e476.jpg)

Here comes an example of a raster layer added from a private mapset, and it went ok
![grass2](https://user-images.githubusercontent.com/11677890/77549881-ad5bde80-6eb0-11ea-9b60-24a589f59400.jpg)

 What could be the problem? Is this a bug?

**Comment by gioman** [comment]
> Is this a bug?

@MonicaRM possibly, please note that at the moment the GRASS plugin is unmaintained (but maybe this is just a QGIS Browser issue, in this case there is a chance it can be fixed).

**Comment by nyalldawson** [comment]
This one may have been fixed in 3.10.4. Can you test?

**Comment by MonicaRM** [comment]
> Is this a bug?
> 
> @MonicaRM possibly, please note that at the moment the GRASS plugin is unmaintained (but maybe this is just a QGIS Browser issue, in this case there is a chance it can be fixed).



> This one may have been fixed in 3.10.4. Can you test?

Thanks for the feedback. I will have to ask IT to install it on the server to test it.

**Comment by MonicaRM** [comment]
> > Is this a bug?
> 
> @MonicaRM possibly, please note that at the moment the GRASS plugin is unmaintained (but maybe this is just a QGIS Browser issue, in this case there is a chance it can be fixed).



> This one may have been fixed in 3.10.4. Can you test?

We were trying with QGIS 3.10.4 and we still see the problem. I found out this issue https://github.com/qgis/QGIS/issues/13007. Probably it hasn't been fixed. Only rasters can be accessed from a not permanent folder not vectors.

**Comment by MonicaRM** [comment]
> > Is this a bug?
> 
> @MonicaRM possibly, please note that at the moment the GRASS plugin is unmaintained (but maybe this is just a QGIS Browser issue, in this case there is a chance it can be fixed).

I think there still a bug there. I was installing the QGIS 3.10.4 and got the same problem.

**Comment by gioman** [comment]
I think the GRASS plugin is likely to be at a crossroad:

once would have been unthinkable to remove it from QGIS, as it gave QGIS the bulk of its analytical power. Now we have processing where we have a ton of native tools and where we can also run most of the GRASS tools. So I think that if the GRASS plugin is half broken and with no maintainer is likely that in the next future it will be in the conversation for removal (if it happens it will be an historic decision for sure).

**Comment by MonicaRM** [comment]
> I think the GRASS plugin is likely to be at a crossroad:
> 
> once would have been unthinkable to remove it from QGIS, as it gave QGIS the bulk of its analytical power. Now we have processing where we have a ton of native tools and where we can also run most of the GRASS tools. So I think that if the GRASS plugin is half broken and with no maintainer is likely that in the next future it will be in the conversation for removal (if it happens it will be an historic decision for sure).

It could have been of great help for those people who are not GRASS oriented but will used the GRASS data already processed.  Of course this needs to be followed but as you said it is not maintained. Thanks for your feedback !

**Comment by gioman** [comment]
> who are not GRASS oriented

who is not GRASS oriented but needs to use GRASS tools can use them in the Processing toolbox as it is **not** nedeed to know anything about the GRASS data model. On the other hand if the necessity is to read GRASS data (locations/mapsets) then QGIS is able to do it from the Browser. I even think that those layers can be used directly as inputs in Processing (but you won't get GRASS vectors/rasters as output).

**Comment by MonicaRM** [comment]
> > who are not GRASS oriented
> 
> who is not GRASS oriented but needs to use GRASS tools can use them in the Processing toolbox as it is **not** nedeed to know anything about the GRASS data model. On the other hand if the necessity is to read GRASS data (locations/mapsets) then QGIS is able to do it from the Browser. I even think that those layers can be used directly as inputs in Processing (but you won't get GRASS vectors/rasters as output).

that is correct. Using the GRASS tools from QGIS is worth it. Yes I am trying to read it from the browser but I get this: /home/XXXXX/username/Mounts/grass/ETRS_33N/g_xxxxx
Permission denied when trying on vectors but not when trying on rasters

**Comment by gioman** [comment]
I have no issues (reading vector data from a GRASS mapset/location) here on QGIS master on Linux.

**Comment by MonicaRM** [comment]
> I have no issues (reading vector data from a GRASS mapset/location) here on QGIS master on Linux.

Is the data you have in the permanent folder that you own? Or you have also different mapsets in the same location? We have location/mapset (not a permanent mapset) and we own just our own mapset. All of our data is saved and organized in a  NFS. But the issue that I can't even get the vectors from my own mapset is critical ( I mean the mapset is under a location but not under the Permanent mapset: /home/XXXXX/username/Mounts/grass/ETRS_33N/g_xxxxx). I can get the vectors from a location with a permanent mapset that i own /home/XXXXX/username/Mounts/grass/Norge_2020/PERMANENT/Fylke_2020/1_polygon

**Comment by gioman** [comment]
> Is the data you have in the permanent folder that you own? Or you have also different mapsets in the same location? We have location/mapset (not a permanent mapset) and we own just our own mapset. All of our data is saved and organized in a NFS. But the issue that I can't even get the vectors from my own mapset is critical ( I mean the mapset is under a location but not under the Permanent mapset: /home/XXXXX/username/Mounts/grass/ETRS_33N/g_xxxxx). I can get the vectors from a location with a permanent mapset that i own /home/XXXXX/username/Mounts/grass/Norge_2020/PERMANENT/Fylke_2020/1_polygon

@MonicaRM can you attach a sample location/mapset?

**Comment by MonicaRM** [comment]
> > Is the data you have in the permanent folder that you own? Or you have also different mapsets in the same location? We have location/mapset (not a permanent mapset) and we own just our own mapset. All of our data is saved and organized in a NFS. But the issue that I can't even get the vectors from my own mapset is critical ( I mean the mapset is under a location but not under the Permanent mapset: /home/XXXXX/username/Mounts/grass/ETRS_33N/g_xxxxx). I can get the vectors from a location with a permanent mapset that i own /home/XXXXX/username/Mounts/grass/Norge_2020/PERMANENT/Fylke_2020/1_polygon
> 
> @MonicaRM can you attach a sample location/mapset?
 I am attaching two samples. 

This one is the structure that crashes (that means that can't be read by qgis) 

<img width="138" alt="mapset_not_readable" src="https://user-images.githubusercontent.com/11677890/81824512-d7875f80-9535-11ea-8401-5f2046749324.PNG">

This one is the one that I can read without problems. But it was me generating the location and the mapset, while the other I was just generating the mapset but not the location. location ETRS_33N and mapset u_monica.ruano

<img width="147" alt="mapset_readable" src="https://user-images.githubusercontent.com/11677890/81824536-deae6d80-9535-11ea-9e94-d4337cd313d0.PNG">

**Comment by gioman** [comment]
>  But it was me

@MonicaRM meaning that was another user (are you on Linux? is the mapset on a shared folder? have you checked the location permissions?) to create the location that cannot be opened?

**Comment by MonicaRM** [comment]
> > But it was me
> 
> @MonicaRM meaning that was another user (are you on Linux? is the mapset on a shared folder? have you checked the location permissions?) to create the location that cannot be opened?
To answer your questions:
no I am not in Linux, I am using a windows based PC. 
The mapset is on a shared NFS system
I have the permissions, I have tested with the GRASS GIS installation we have and I can read vectors and rasters from all mapsets without problem. So this is a barely QGIS issue. I was creating a new location Norge_2020 and  two mapsets of course the Permanent and the u_monica.ruano with the GRASS GIS installation we have.
Some background here:
Almost all users have a windows PC so we connect to a Linux server via X2GO or Putty. In the linux server are installed QGIS,Grass GIS, postgresql, etc. We use a NFS for data saving so is here were the GRASS structure is saved. We rely on the System Administrator to let the users the permissions to read and write here. And my user has the permissions, because when I have tried in the GRASS GIS installation it goes all ok for reading and writing.
This is the explanation of how the QGIS is managing the access to the GRASS data:
In the first picture I was posting, We have access to read those locations and mapsets of general interest for example the location ETRS_33N and mapset u_AdministrativeUnits or location ETRS_33N   mapset u_monica.ruano (this is the user own mapset, you can read and write here). I was not creating this locations of general interests and neither the u_monica.ruano mapset (they were created for me).  In this location we do not have access to the Permanent folder.  There are 3 locations ETRS_33N,ETRS_32N and WGS_4326. But here we do can read rasters but not vectors. That is also very strange.
In the second picture I was posting, is referring to a test I was making. My user could create a new location that I called Norge_2020 and this generated the Permanent mapset folder and then I created a u_monica.ruano mapset also. This to test If I could read both mapsets from the QGIS, and I did without a problem. 

So I am quite sure that the problem is still in how qgis is reading the grass database specifically the vector files because we can read the rasters without problem.

**Comment by neteler** [comment]
> > > Is this a bug?
> > 
> > 
> > @MonicaRM possibly, please note that at the moment the GRASS plugin is unmaintained (but maybe this is just a QGIS Browser issue, in this case there is a chance it can be fixed).
> 
> > This one may have been fixed in 3.10.4. Can you test?
> 
> We were trying with QGIS 3.10.4 and we still see the problem. I found out this issue #13007. Probably it hasn't been fixed. Only rasters can be accessed from a not permanent folder not vectors. I can see that in the QGIS browser this when clicking the properties of a vector layer in the GRASS database the path looks like this:
> /home/XXXXX/username/Mounts/grass/ETRS_33N/g_xxxxx
> Permission denied

Shouldn't this instead point to

/home/XXXXX/username/Mounts/grass/ETRS_33N/g_xxxxx/mymap/head

(as it works for OGR, see https://gdal.org/drivers/vector/grass.html#datasource-name)
?

> While the raster file path looks like this and I don't have problems accessing it:
> /home/XXXXX/username/Mounts/grass/ETRS_33N/g_xxxx/cellhd/skoggrense_100m

Yes, this follows how GDAL expects it for raster maps: https://gdal.org/drivers/raster/grass.html

**Comment by alexbruy** [comment]
Is this still an issue with latest QGIS versions and taking into account what was said in the previous comment?

**Comment by MonicaRM** [comment]
Hi,
Sorry for my delay for replying. I was checking it now and we still have the problem.  We are using the last  LTR Qgis 3.16. We have GRASS GIS 8 installed.

**Comment by alexbruy** [comment]
Last LTR is 3.28 and latest release is 3.32.

**Comment by MonicaRM** [comment]
IT section is the one doing this updates and they want that the work with only LTR, but I am wondering soon will the LTR/PR 3.34 releases. Could you recommend that we wait this new release?

**Comment by jef-n** [comment]
3.10 is meanwhile three LTRs behind (3.16, 3.22 and 3.28).  The new LTR will enter the LTR repos in february (when the following release takes it's place as the latest release; see [release schedule](https://qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule)).

**Comment by MonicaRM** [comment]
Thanks. I will talk with the IT people here to see if we can install version 3.28 to test if the issue fix.
