### ISSUE TITLE
metasearch python error when trying to add a resource that is available as both WMS and WFS

### ISSUE THREAD

**Issue by deRightDirection** [qgis/QGIS#35560]
it is about the metasearch catalog client which is a core plugin of QGIS.

i added the following service: http://nationaalgeoregister.nl/geonetwork/srv/dut/csw 
use keyword "bag" to search for

![image](https://user-images.githubusercontent.com/3999790/78389870-8177e180-75b1-11ea-849c-e626bbbfbd2c.png)

and then i select add data --> wfs

![image](https://user-images.githubusercontent.com/3999790/78389924-a3716400-75b1-11ea-8947-c4d7d66ef28a.png)

and then i got an error

![image](https://user-images.githubusercontent.com/3999790/78390076-e9c6c300-75b1-11ea-90e2-99108f2a3ae7.png)

**Comment by gioman** [comment]
> and then i got an error

@deRightDirection not an issue here on 3.10.4 and 3.12.1 on Windows 10 / OSGeo4W. Try with a new QGIS profile.

**Comment by gioman** [comment]
@deRightDirection sorry confirmed, but it only happens for those results that make available both WMS and WFS services.

**Comment by NyakudyaA** [comment]
> @deRightDirection sorry confirmed, but it only happens for those results that make available both WMS and WFS services.

Tested this in master and it is fixed.
![master-qgis](https://user-images.githubusercontent.com/2510900/80191166-9f1af280-8615-11ea-93bc-74ff874769f8.png)

**Comment by deRightDirection** [comment]
thanks, i tried it out today. But the error message is gone, but it goes immediately into "(not responding)"

I searched for "groningen"

![afbeelding](https://user-images.githubusercontent.com/3999790/82289755-c317ec80-99a5-11ea-8bc6-ae01a4fedad9.png)

selected "Wierden" and clicked on the button "toevoegen" ...

**Comment by gioman** [comment]
I still get the error on master. Can the maintainer of this core tool have a look into this? Who is the maintainer?

**Comment by gioman** [comment]
It is even worse now on the latest 3.10: for a service that only publishes the data as WMS now it also returns an error

```
AttributeError: 'NoneType' object has no attribute 'addRasterLayer' 
Traceback (most recent call last):
  File "C:/OSGEO4~1/apps/qgis-ltr/./python/plugins\MetaSearch\dialogs\maindialog.py", line 757, in add_to_ows
    ows_provider.addRasterLayer.connect(self.iface.addRasterLayer)
AttributeError: 'NoneType' object has no attribute 'addRasterLayer'
```

**Comment by rduivenvoorde** [comment]
I think @tomkralidis is still king of this part of the code :-)

**Comment by gioman** [comment]
@rduivenvoorde thanks! @tomkralidis ping, this is affecting also our LTR release. Tagging as regression as it worked as expected in previous QGIS releases.

**Comment by skampus** [comment]
in the last dev, all it works

OS: Windows 10
Versione di QGIS 3.15.0-Master
Revisione codice QGIS e2fe098e4e

**Comment by gioman** [comment]
> in the last dev, all it works

@skampus just tested too on Windows 10: no python error on QGIS master, but after adding the WMS/WFS connection from Metasearch the WMS/WFS client hangs and after a while throws an error. Trying again to connect to the service works.

Still python error on QGIS LTR.

**Comment by tomkralidis** [comment]
I'll check on this tonight starting with 3.10 branch.

**Comment by tomkralidis** [comment]
PR issued in https://github.com/qgis/QGIS/pull/37637

Once LTR branch works/is covered I'll work my way across branches 3.12 and 3.14 accordingly.
