### ISSUE TITLE
Various zoom actions override fixed scale

### ISSUE THREAD

**Issue by Llaves** [qgis/QGIS#36113]
Various zoom actions (zoom to layer extent, zoom to selected) override a fixed scale. That is to say, if I set the scale to some value, say 1:24000, lock the scale, then zoom to extent, the scale changes, not the magnification. 

Qgis 3.10.4, Windows 7, 64 bit.

**Comment by nyalldawson** [comment]
Please test on master (or 3.12.2). This should already be fixed

**Comment by Llaves** [comment]
I will test this on the master as soon as I have access to enough bandwidth to download the new master. This may be another week. Sorry.

**Comment by Llaves** [comment]
Will this fix be back-ported to 3.10.x LTR? I just checked 3.10.5 and the problem is still there.
Thx

**Comment by Llaves** [comment]
Sorry - this slipped between the cracks. The issue is fixed in 3.16.2. Possibly fixed in something earlier - I didn't try to narrow it down.
