### ISSUE TITLE
Re-Refreshing Oracle connection on browser causes crash

### ISSUE THREAD

**Issue by uclaros** [qgis/QGIS#36512]
**Describe the bug**

In the browser panel, if one tries to refresh an Oracle connection while it is still being refreshed causes QGIS to crash.

**How to Reproduce**
- Open the browser panel
- Right click on an Oracle connection and hit Refresh
- While the generated task is still running, repeat previous step
- Crash

**QGIS and OS versions**
07e38a2196 on Debian testing, Oracle instant client 19.6

**Comment by rduivenvoorde** [comment]
Cannot confirm this one here on 3.14/Windows with Oracle connections. I can click several times on the button (while the 'busy' cursor is visible) and all is ok:


QGIS version | 3.14.0-Pi | QGIS code revision | 9f7028fd23
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020

**Comment by uclaros** [comment]
Revisiting my issues with a *Feedback* label because of the new stale policy:
I can still reproduce this on 5c87f70 on debian testing.
Could someone replace the feedback label with a crash one please?

Here's a stacktrace:
```
2020-12-16T18:27:41.341  QGIS died on signal 11[New LWP 834664]
2020-12-16T18:27:41.341  [New LWP 834665]
2020-12-16T18:27:41.341  [New LWP 834667]
2020-12-16T18:27:41.341  [New LWP 834668]
2020-12-16T18:27:41.341  [New LWP 834669]
2020-12-16T18:27:41.341  [New LWP 834670]
2020-12-16T18:27:41.341  [New LWP 834671]
2020-12-16T18:27:41.341  [New LWP 834672]
2020-12-16T18:27:41.341  [New LWP 834673]
2020-12-16T18:27:41.341  [New LWP 834674]
2020-12-16T18:27:41.341  [New LWP 834677]
2020-12-16T18:27:41.341  [New LWP 834679]
2020-12-16T18:27:41.341  [New LWP 834687]
2020-12-16T18:28:08.207  [Thread debugging using libthread_db enabled]
2020-12-16T18:28:08.207  Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
2020-12-16T18:28:26.497  0x00007fee4bed41c7 in __GI___wait4 (pid=834698, stat_loc=0x7ffdd6f52694, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:27
2020-12-16T18:28:26.498  27     ../sysdeps/unix/sysv/linux/wait4.c: No such file or directory.
2020-12-16T18:28:30.018  [Current thread is 1 (Thread 0x7fee3cf5af40 (LWP 834657))]
2020-12-16T18:28:30.018  #0  0x00007fee4bed41c7 in __GI___wait4 (pid=834698, stat_loc=0x7ffdd6f52694, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:27
2020-12-16T18:28:30.018  #1  0x0000562f4ce46286 in qgisCrash(int) (signal=11) at ../src/app/main.cpp:349
2020-12-16T18:28:30.018          status = 0
2020-12-16T18:28:30.018          pidstr = "--pid=834657\000\352 l\000\332\aP/V\000\000\300&\365\326\375\177\000"
2020-12-16T18:28:30.018          gdbpid = 834698
2020-12-16T18:28:30.018          exename = "/home/uclaros/dev/QGIS/build-master-Debug/output/bin/qgis\000#O\356\177\000\000\000\000\000\000\000\000\000\000\260\020\067O/V\000\000\340\003\000\000\000\000\000\000\000\260\340\036\f\352 l\000\000\000\000\000\000\000\000\300&\365\326\375\177\000\000\340\060\006P/V\000\000\003\000\000\000\000\000\000\000 \000\000\000\000\000\000\000\000\332\aP/V\000\000\000\000\000\000\000\000\000\000\310\001\000\000\032", '\000' <repeats 11 times>, "\310\001\000\000\032\000\000\000\365\000\000\000\340\003\000\000\275\002\000\000\372\003\000\000\200\341\aP/V\000\000"...
2020-12-16T18:28:30.018          len = 57
2020-12-16T18:28:30.018  #2  0x00007fee4be44d30 in <signal handler called> () at /lib/x86_64-linux-gnu/libc.so.6
2020-12-16T18:28:30.018  #3  0x00007fee4e5b2e77 in QMutex::lock() () at /lib/x86_64-linux-gnu/libQt5Core.so.5
2020-12-16T18:28:30.018  #4  0x0000562f4ce50356 in QMutexLocker::QMutexLocker(QBasicMutex*) (this=0x7ffdd6f52cb8, m=0x88) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qmutex.h:233
2020-12-16T18:28:30.018  #5  0x00007fee4d0de800 in QgsProxyProgressTask::finalize(bool) (this=0x0, result=true) at ../src/core/qgsproxyprogresstask.cpp:28
2020-12-16T18:28:30.018          lock = {val = 136}
2020-12-16T18:28:30.018  #6  0x00007fee1f1210b9 in QgsOracleConnectionItem::threadFinished() (this=0x7fee1002a120) at ../src/providers/oracle/qgsoracledataitems.cpp:229
2020-12-16T18:28:30.018          __FUNCTION__ = "threadFinished"
2020-12-16T18:28:30.018  #7  0x00007fee1f128229 in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (QgsOracleConnectionItem::*)()>::call(void (QgsOracleConnectionItem::*)(), QgsOracleConnectionItem*, void**) (f=(void (QgsOracleConnectionItem::*)(class QgsOracleConnectionItem * const)) 0x7fee1f121094 <QgsOracleConnectionItem::threadFinished()>, o=0x7fee1002a120, arg=0x7fed9805cd58) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:152
2020-12-16T18:28:30.018  #8  0x00007fee1f127e3e in QtPrivate::FunctionPointer<void (QgsOracleConnectionItem::*)()>::call<QtPrivate::List<>, void>(void (QgsOracleConnectionItem::*)(), QgsOracleConnectionItem*, void**) (f=(void (QgsOracleConnectionItem::*)(class QgsOracleConnectionItem * const)) 0x7fee1f121094 <QgsOracleConnectionItem::threadFinished()>, o=0x7fee1002a120, arg=0x7fed9805cd58) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:185
2020-12-16T18:28:30.018  #9  0x00007fee1f1276d2 in QtPrivate::QSlotObject<void (QgsOracleConnectionItem::*)(), QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) (which=1, this_=0x562f5213a3a0, r=0x7fee1002a120, a=0x7fed9805cd58, ret=0x0) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qobjectdefs_impl.h:418
2020-12-16T18:28:30.018  #10 0x00007fee4e7b4719 in QObject::event(QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
2020-12-16T18:28:30.018  #11 0x00007fee4f21cccf in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
2020-12-16T18:28:30.018  #12 0x00007fee4f225e10 in QApplication::notify(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
2020-12-16T18:28:30.018  #13 0x00007fee4cd9b673 in QgsApplication::notify(QObject*, QEvent*) (this=0x7ffdd6f53d80, receiver=0x7fee1002a120, event=0x7fed9805cd10) at ../src/core/qgsapplication.cpp:462
2020-12-16T18:28:30.018          done = true
2020-12-16T18:28:30.018          __PRETTY_FUNCTION__ = "virtual bool QgsApplication::notify(QObject*, QEvent*)"
2020-12-16T18:28:30.018  #14 0x00007fee4e787d02 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
2020-12-16T18:28:30.018  #15 0x00007fee4e78a494 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
2020-12-16T18:28:30.018  #16 0x00007fee4e7df273 in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
2020-12-16T18:28:30.018  #17 0x00007fee4459fb8b in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
2020-12-16T18:28:30.018  #18 0x00007fee4459fe38 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
2020-12-16T18:28:31.244  #19 0x00007fee4459feef in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
2020-12-16T18:28:31.244  #20 0x00007fee4e7de8ee in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
2020-12-16T18:28:31.244  #21 0x00007fee4e78689b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
2020-12-16T18:28:31.244  #22 0x00007fee4e78e672 in QCoreApplication::exec() () at /lib/x86_64-linux-gnu/libQt5Core.so.5
2020-12-16T18:28:31.244  #23 0x0000562f4ce4db12 in main(int, char**) (argc=1, argv=0x7ffdd6f55118) at ../src/app/main.cpp:1637
2020-12-16T18:28:31.244          preApplicationLogMessages = {<QList<QString>> = {<QListSpecialMethods<QString>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = -1}, <No data fields>}}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x562f4ec67ce0}, d = 0x562f4ec67ce0}}, <No data fields>}
2020-12-16T18:28:31.244          __FUNCTION__ = "main"
2020-12-16T18:28:31.244          mySnapshotFileName = {static null = {<No data fields>}, d = 0x7fee4e86c860 <QArrayData::shared_null>}
2020-12-16T18:28:31.244          configLocalStorageLocation = {static null = {<No data fields>}, d = 0x562f4ec723b0}
2020-12-16T18:28:31.244          profileName = {static null = {<No data fields>}, d = 0x562f4ec72a30}
2020-12-16T18:28:31.244          mySnapshotWidth = 800
2020-12-16T18:28:31.244          mySnapshotHeight = 600
2020-12-16T18:28:31.244          myHideSplash = false
2020-12-16T18:28:31.244          settingsMigrationForce = false
2020-12-16T18:28:31.244          mySkipVersionCheck = false
2020-12-16T18:28:31.244          hideBrowser = false
2020-12-16T18:28:31.244          myRestoreDefaultWindowState = false
2020-12-16T18:28:31.244          myRestorePlugins = true
2020-12-16T18:28:31.244          myCustomization = true
2020-12-16T18:28:31.244          dxfOutputFile = {static null = {<No data fields>}, d = 0x7fee4e86c860 <QArrayData::shared_null>}
2020-12-16T18:28:31.244          dxfSymbologyMode = QgsDxfExport::SymbolLayerSymbology
2020-12-16T18:28:31.244          dxfScale = 50000
2020-12-16T18:28:31.244          dxfEncoding = {static null = {<No data fields>}, d = 0x562f4ce58b00 <main::{lambda()#2}::operator()() const::qstring_literal>}
2020-12-16T18:28:31.244          dxfMapTheme = {static null = {<No data fields>}, d = 0x7fee4e86c860 <QArrayData::shared_null>}
2020-12-16T18:28:31.244          dxfExtent = {mXmin = 0, mYmin = 0, mXmax = 0, mYmax = 0}
2020-12-16T18:28:31.244          takeScreenShots = false
2020-12-16T18:28:31.244          screenShotsPath = {static null = {<No data fields>}, d = 0x7fee4e86c860 <QArrayData::shared_null>}
2020-12-16T18:28:31.244          screenShotsCategories = 0
2020-12-16T18:28:31.244          myInitialExtent = {static null = {<No data fields>}, d = 0x562f4ce58b40 <main::{lambda()#3}::operator()() const::qstring_literal>}
2020-12-16T18:28:31.244          translationCode = {static null = {<No data fields>}, d = 0x562f4ecadc50}
2020-12-16T18:28:31.244          authdbdirectory = {static null = {<No data fields>}, d = 0x7fee4e86c860 <QArrayData::shared_null>}
2020-12-16T18:28:31.244          pythonfile = {static null = {<No data fields>}, d = 0x7fee4e86c860 <QArrayData::shared_null>}
2020-12-16T18:28:31.244          customizationfile = {static null = {<No data fields>}, d = 0x562f4f29deb0}
2020-12-16T18:28:31.244          globalsettingsfile = {static null = {<No data fields>}, d = 0x562f4ec68aa0}
2020-12-16T18:28:31.244          openClProgramFolder = {static null = {<No data fields>}, d = 0x7fee4e86c860 <QArrayData::shared_null>}
2020-12-16T18:28:31.244          args = {<QList<QString>> = {<QListSpecialMethods<QString>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = -1}, <No data fields>}}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x562f4ec67f80}, d = 0x562f4ec67f80}}, <No data fields>}
2020-12-16T18:28:31.244          myUseGuiFlag = true
2020-12-16T18:28:31.244          rootProfileFolder = {static null = {<No data fields>}, d = 0x562f4ec72420}
2020-12-16T18:28:31.244          manager = {<QObject> = {<No data fields>}, static staticMetaObject = {d = {superdata = {direct = 0x7fee4ea07c40 <QObject::staticMetaObject>}, stringdata = 0x7fee4d7ae360 <qt_meta_stringdata_QgsUserProfileManager>, data = 0x7fee4d7ae3e0 <qt_meta_data_QgsUserProfileManager>, static_metacall = 0x7fee4c80de20 <QgsUserProfileManager::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)>, relatedMetaObjects = 0x0, extradata = 0x0}}, mWatchProfiles = false, mWatcher = std::unique_ptr<class QFileSystemWatcher> = {get() = 0x0}, mRootProfilePath = {static null = {<No data fields>}, d = 0x562f4ec72420}, mUserProfile = std::unique_ptr<class QgsUserProfile> = {get() = 0x0}, mSettings = std::unique_ptr<class QSettings> = {get() = 0x562f4ec657f0}}
2020-12-16T18:28:31.244          profile = 0x562f4ec67c50
2020-12-16T18:28:34.720          profileFolder = {static null = {<No data fields>}, d = 0x562f4ec70fb0}
2020-12-16T18:28:34.720          myApp = {<QApplication> = {<No data fields>}, static staticMetaObject = {d = {superdata = {direct = 0x7fee4f71d5c0 <QApplication::staticMetaObject>}, stringdata = 0x7fee4d79a860 <qt_meta_stringdata_QgsApplication>, data = 0x7fee4d79aa60 <qt_meta_data_QgsApplication>, static_metacall = 0x7fee4c7f39be <QgsApplication::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)>, relatedMetaObjects = 0x0, extradata = 0x0}}, static QGIS_ORGANIZATION_NAME = 0x7fee4d8e754a "QGIS", static QGIS_ORGANIZATION_DOMAIN = 0x7fee4d8e754f "qgis.org", static QGIS_APPLICATION_NAME = 0x7fee4d8e7558 "QGIS3", static mFileOpenEventReceiver31700 = 0x562f4f91fdb0, static mInitialized31700 = true, static mRunningFromBuildDir31700 = true, static sMaxThreads31700 = -1, mIconCache = {d = 0x562f4ec68c80}, mCursorCache = {d = 0x562f4fe101e0}, mQgisTranslator = 0x562f4ed2c660, mQtTranslator = 0x562f4ed32a10, mDataItemProviderRegistry = 0x562f4f56c670, mAuthManager = 0x562f4fa71c00, mApplicationMembers = 0x562f4ed08df0, static sApplicationMembers = 0x0, static sAuthManager = 0x0}
2020-12-16T18:28:34.720          settings = {<QObject> = {<No data fields>}, static staticMetaObject = {d = {superdata = {direct = 0x7fee4ea07c40 <QObject::staticMetaObject>}, stringdata = 0x7fee4d7a9f00 <qt_meta_stringdata_QgsSettings>, data = 0x7fee4d7a9f40 <qt_meta_data_QgsSettings>, static_metacall = 0x7fee4c809afa <QgsSettings::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)>, relatedMetaObjects = 0x0, extradata = 0x0}}, mUserSettings = 0x562f4ed34e90, mGlobalSettings = 0x562f4eca9f60, mUsingGlobalArray = false}
2020-12-16T18:28:34.720          libPaths = {<QList<QString>> = {<QListSpecialMethods<QString>> = {<No data fields>}, {p = {static shared_null = {ref = {atomic = {_q_value = {<std::__atomic_base<int>> = {static _S_alignment = 4, _M_i = -1}, <No data fields>}}}, alloc = 0, begin = 0, end = 0, array = {0x0}}, d = 0x562f4eeb67a0}, d = 0x562f4eeb67a0}}, <No data fields>}
2020-12-16T18:28:34.720          relLibPath = {static null = {<No data fields>}, d = 0x562f4f060cc0}
2020-12-16T18:28:34.720          customizationsettings = 0x562f4f23a3b0
2020-12-16T18:28:34.720          systemEnvVars = {d = 0x562f4edf0ae0}
2020-12-16T18:28:34.720          useCustomVars = false
2020-12-16T18:28:34.720          desiredStyle = {static null = {<No data fields>}, d = 0x562f4f2ca110}
2020-12-16T18:28:34.720          theme = {static null = {<No data fields>}, d = 0x562f4f2bab20}
2020-12-16T18:28:34.720          activeStyleName = {static null = {<No data fields>}, d = 0x562f4f831630}
2020-12-16T18:28:34.720          mySplashPath = {static null = {<No data fields>}, d = 0x7fee4d8e8660 <QgsApplication::splashPath()::{lambda()#1}::operator()() const::qstring_literal>}
2020-12-16T18:28:34.720          myPixmap = <incomplete type>
2020-12-16T18:28:34.720          w = 600
2020-12-16T18:28:34.720          h = 300
2020-12-16T18:28:34.720          mypSplash = 0x562f4ed2cce0
2020-12-16T18:28:34.720          qgis = 0x562f4f91fdb0
2020-12-16T18:28:34.720          sigwatch = {<QObject> = {<No data fields>}, static staticMetaObject = {d = {superdata = {direct = 0x7fee4ea07c40 <QObject::staticMetaObject>}, stringdata = 0x562f4ce9a3c0 <qt_meta_stringdata_UnixSignalWatcher>, data = 0x562f4ce9a480 <qt_meta_data_UnixSignalWatcher>, static_metacall = 0x562f4ce54ec0 <UnixSignalWatcher::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)>, relatedMetaObjects = 0x0, extradata = 0x0}}, d_ptr = 0x562f4f49c390}
2020-12-16T18:28:34.720          retval = 1290379520
2020-12-16T18:28:34.720  [Inferior 1 (process 834657) detached]
2020-12-16T18:28:34.838  gdb returned 0
2020-12-16T18:28:34.958  ORA-24550: signal received: [si_signo=6] [si_errno=0] [si_code=-6] [si_int=0] [si_ptr=(nil)] [si_addr=0x3e8000cbc61]
2020-12-16T18:28:35.025  kpedbg_dmp_stack()+394<-kpeDbgCrash()+204<-kpeDbgSignalHandler()+113<-skgesig_sigactionHandler()+258<-__sighandler()<-gsignal()+321<-__sighandler()<-_ZN6QMutex4lockEv()+7<-_ZN20QgsProxyProgressTask8finalizeEb()+44<-_ZN23QgsOracleConnectionItem14threadFinishedEv()+37<-_ZN9QtPrivate11FunctorCallINS_11IndexesListIJEEENS_4ListIJEEEvM23QgsOracleConnectionItemFvvEE4callES7_PS5_PPv()+107<-_ZN9QtPrivate15FunctionPointerIM23QgsOracleConnectionItemFvvEE4callINS_4ListIJEEEvEEvS3_PS1_PPv()+66<-_ZN9QtPrivate11QSlotObjectIM23QgsOracleConnectionItemFvvENS_4ListIJEEEvE4implEiPNS_15QSlotObjectBaseEP7QObjectPPvPb()+119<-_ZN7QObject5eventEP6QEvent()+697<-_ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent()+127<-0x00007FEE1002B410<-_ZN23QgsOracleConnectionItem11qt_metacastEPKc()<-0xF8458B48F87D89482020-12-16T18:28:35.025
```

**Comment by gioman** [comment]
>  Could someone replace the feedback label with a crash one please?

done

**Comment by Pedro-Murteira** [comment]
@uclaros Hello, is the crash still reproducible?

**Comment by uclaros** [comment]
Yes, still reproducible. It needs to be done via *right click* as in the original instructions, not via the refresh button.
