### ISSUE TITLE
crssync.exe - System Error

### ISSUE THREAD

**Issue by Saijin-Naib** [qgis/QGIS#37330]
**Describe the bug**
![image](https://user-images.githubusercontent.com/19295950/85226439-75781080-b3a5-11ea-9e4d-958438f8b15c.png)
After using OSGeo4W to upgrade my 3.12 install to 3.14
![image](https://user-images.githubusercontent.com/19295950/85226462-93457580-b3a5-11ea-92c4-36995f4ac531.png)

**How to Reproduce**
Use OSGeo4W to upgrade using Advanced and default selections.

**QGIS and OS versions**
Broken 3.14
**Additional context**
![image](https://user-images.githubusercontent.com/19295950/85226484-ad7f5380-b3a5-11ea-90f4-fc1f6675c6c7.png)
Website indicates that 3.14 is still in packaging and not released, so I guess what is occurring is OSGeo4W is applying a partial update and breaking the install.

**Comment by agiudiceandrea** [comment]
@Saijin-Naib I think the protobuf library is missing among the qgis package dependencies:

```
@ qgis
sdesc: "QGIS Desktop"
ldesc: "QGIS Desktop"
category: Desktop
requires: qgis-common python3-core pyqt5 python3-gdal gpsbabel python3-psycopg2 python3-qscintilla python3-jinja2 python3-markupsafe python3-pygments python3-python-dateutil python3-pytz python3-future python3-requests python3-pyproj python3-pyyaml python3-plotly python3-owslib python3-httplib2 python3-nose2 python3-mock qt5-qml exiv2 qt5-tools
version: 3.14.0-1
install: x86_64/release/qgis/qgis/qgis-3.14.0-1.tar.bz2 48899074 5f445c1a8dd166f578e54ef57d855dcb
```

The same problem occurs with the standalone installer for 3.14 available at https://qgis.org/downloads/?C=M;O=D

I've filed a bug report on osgeo4w issue tracker: https://trac.osgeo.org/osgeo4w/ticket/634

**Comment by agiudiceandrea** [comment]
The bug was instantly fixed by @jef-n . The protobuf library was added as dependency of the qgis-common package.

https://trac.osgeo.org/osgeo4w/ticket/634#comment:1

> #634: Protobuf dependency missing for QGIS 3.14 (both network and standalone
> installer): installation aborts or QGIS doesn't start
> ------------------------+----------------------------
> Reporter:  andreaerdna  |       Owner:  osgeo4w-dev@…
>     Type:  defect       |      Status:  closed
> Priority:  critical     |   Component:  Installer
>  Version:               |  Resolution:  fixed
> Keywords:               |
> ------------------------+----------------------------
> Changes (by jef):
> 
>  * status:  new => closed
>  * resolution:   => fixed


It is now possible to correctly install QGIS 3.14 via the OSGeo4W network installer.

The standalone installer was removed from server, waiting to upload a new fixed version.

**Comment by Saijin-Naib** [comment]
Thanks so much to you both!

**Comment by TofuSandwich** [comment]
This issue is still happening. Is there a clean way to solve? I had problems trying to add SAGA, so I uninstalled everything and try to reinstall.
