### ISSUE TITLE
Embedding layers with same name from different projects not possible

### ISSUE THREAD

**Issue by kingemir** [qgis/QGIS#38423]
**Describe the bug**

Embedding layers with same name from different projects not possible

**How to Reproduce**

1. In project A, create layer _X_. 
2. In project B, create layer _X_. 
2. In project C, go to Layer -> "Embed Layers and Groups" and embed the layer X from project A. It works.
5. In project C, go to Layer -> "Embed Layers and Groups" and embed the layer X from project B. It's not loaded. Observed behaviour happens when the layer names are the same (in this case: "X").

**QGIS and OS versions**

QGIS version | 3.14.15-Pi | QGIS code revision | d5114d2cfa
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Windows 10 (10.0)
Active python plugins | GroupStats; QgisModelBaker; quick_map_services; slyr; SpreadsheetLayers; db_manager; MetaSearch; processing

**Additional context**

**Comment by Pedro-Murteira** [comment]
This issue is still valid on QGIS 3.16.15 and 3.22.2.

**Comment by alexbruy** [comment]
Seems fixed in the latest master (f344919474)

**Comment by jbogdani** [comment]
I can confirm that this issue still persists in 3.40.5-Bratislava
