### ISSUE TITLE
GDAL fails in the MacOS LTR (_iconv)

### ISSUE THREAD

**Issue by mapninja** [qgis/QGIS#38918]
Fresh install of LTR, after deleting Profiles and reinstalling. 

```
QGIS version: 3.10.10-A Coruña
QGIS code revision: 1869829378
Qt version: 5.12.3
GDAL version: 2.4.1
GEOS version: 3.7.2-CAPI-1.11.2 b55d2125
PROJ version: Rel. 5.2.0, September 15th, 2018
Processing algorithm…
Algorithm 'Clip raster by extent' starting…
Input parameters:
{ 'DATA_TYPE' : 0, 'EXTRA' : '', 'INPUT' : '/Users/maples/Dropbox/Fundamentals/data/n37_w123_1arc_v3.tif', 'NODATA' : None, 'OPTIONS' : '', 'OUTPUT' : 'TEMPORARY_OUTPUT', 'PROJWIN' : '-122.2595875365627,-122.13930135243736,37.36903396820149,37.43874230148546 [EPSG:4326]' }

GDAL command:
gdal_translate -projwin -122.2595875365627 37.43874230148546 -122.13930135243736 37.36903396820149 -of GTiff /Users/maples/Dropbox/Fundamentals/data/n37_w123_1arc_v3.tif /private/var/folders/f3/0prmkq7962795yfpwsmvh2100000gq/T/processing_f2457a8fee14434f8c38dbe259f9f374/298bac00ed934dac93ac2de34296c8de/OUTPUT.tif
GDAL command output:
dyld: Symbol not found: _iconv

Referenced from: /usr/lib/libarchive.2.dylib

Expected in: /Applications/QGIS3.10.app/Contents/MacOS/lib/libiconv.2.dylib

in /usr/lib/libarchive.2.dylib

Execution completed in 0.13 seconds
Results:
{'OUTPUT': '/private/var/folders/f3/0prmkq7962795yfpwsmvh2100000gq/T/processing_f2457a8fee14434f8c38dbe259f9f374/298bac00ed934dac93ac2de34296c8de/OUTPUT.tif'}

Loading resulting layers
The following layers were not correctly generated.<ul><li>/private/var/folders/f3/0prmkq7962795yfpwsmvh2100000gq/T/processing_f2457a8fee14434f8c38dbe259f9f374/298bac00ed934dac93ac2de34296c8de/OUTPUT.tif</li></ul>You can check the 'Log Messages Panel' in QGIS main window to find more information about the execution of the algorithm.
```

**Comment by PeterPetrik** [comment]
duplicate of https://github.com/qgis/QGIS-Mac-Packager/issues/28

see https://github.com/qgis/QGIS-Mac-Packager/issues/28#issuecomment-591678808 for workaround. 

This `_iconv` problem was one of the reason why to switch to new system with nightly2 packages, not based on homebrew, which does not have this problem. QGIS 3.16 should not be affected by this.

**Comment by apenngrace** [comment]
I just ran into this issue today with 3.14.16 installed via homebrew.  What is the URL of the nightly2 packages so that I can update `qgis.rb` on homebrew's repo.

**Comment by PeterPetrik** [comment]
@apenngrace try https://qgis.org/downloads/macos/nightly2/qgis_nightly2_master_20200922_013400.dmg

**Comment by apenngrace** [comment]
The homebrew formula is just downloading from https://qgis.org/downloads/macos/qgis-macos-pr.dmg.  I'm assuming **pr** means production release.  It makes sense for that homebrew formula to link to the production version, since it would change less frequently and should have less surprises than a nightly release.  

Wouldn't this be a show stopping bug for a lot of people using Macs?  I encountered this issue using 3.14.16 while taking a University course (trying to use a raster terrain analysis function).  Many GIS students are not software engineers, so this is major inconvenience for them.

**Comment by PeterPetrik** [comment]
we have LTR and PR (point release). This is indeed major inconvenience, but hopefully in less than month time the QGIS 3.16 will be PR and it is solved there. It would take considerable time to fix this in LTR, due to completeely different packaging mechanism.

**Comment by pierre-ligen** [comment]
> @apenngrace try https://qgis.org/downloads/macos/nightly2/qgis_nightly2_master_20200922_013400.dmg
If this error is correctly related to this,
still not working for a Raster -> Extraction -> Clip Raster by Mask Layer under macOS 10.15.7

**Comment by pierre-ligen** [comment]
@PeterPetrik even with qgis_nightly2_master_20200922_013400 I can't clip a raster correctly. My current workaround is to use SAGA wich sometimes works (but not for all). 
So for me it's not a "closed" topic. 
Best regards and thank you for your involvement in QGIS development 👍

**Comment by PeterPetrik** [comment]
@pierre-ligen can you try with the last qgis nighty (not nightly2)?

**Comment by pierre-ligen** [comment]
@PeterPetrik I tried and I'm still getting the following error: 
`The following layers were not correctly generated.
• /private/var/folders/wh/8qv9_tf907xctr_sl2tqvbsc0000gp/T/processing_EHwoAD/c6ddf489d0d94d1fb9dc842fe5b2672c/OUTPUT.tif
You can check the 'Log Messages Panel' in QGIS main window to find more information about the execution of the algorithm.`

**Comment by PeterPetrik** [comment]
@pierre-ligen ok, I can try to fix it , but it is not relevant to this ticket, which is about missing _iconv. Can you please create new ticket, with the reproduce steps, example project? thanks  a lot.
