### ISSUE TITLE
Symbol in layers panel is offset same as symbol in map

### ISSUE THREAD

**Issue by Ellebjerg** [qgis/QGIS#39034]
I am not certain whether this is actually a bug or intended behaviour, but it is certainly not appropriate.

When I offset a point symbol - I expect that it goes for any symbol - in the map, the symbol is offset equally in the layers panel. This  causes the individual posts in the layers panel to be shown with considerably more spacing that when the symbols are not offset.

I am using QGIS 3.14.

Best regards,
Lars

**Comment by roya0045** [comment]
can you provide an image to showcase how this is an issue?

**Comment by pjshelton** [comment]
It also does this for lines.

![image](https://user-images.githubusercontent.com/39154868/103476326-4c2e4780-4e00-11eb-9b7e-ea2da553e005.png)

I thing this should be a feature request. 

in the image above, I have four symbology for the lines layer. and the first and third symbology have offsets.  and are rendered with much more space than the other two symbologys.  The requester would like the layers window to keep a more even spacing for lines and points.

@gioman, can this be labeled as a feature request.

**Comment by roya0045** [comment]
@pjshelton I'm pretty sure this is now addressed thanks to Mathieu, though I think its only in master and eventually 3.18. see #39777

**Comment by pjshelton** [comment]
have not been able to test this yet.

**Comment by Ellebjerg** [comment]
Let us wait and see in 3.18. The issue is still there in 3.16.3.

**Comment by gioman** [comment]
> Let us wait and see in 3.18. The issue is still there in 3.16.3.

@Ellebjerg have you tested on 3.18?

**Comment by colliera** [comment]
For anyone coming along later, this is still an issue in 3.22.16 and 3.28.12
![image](https://github.com/qgis/QGIS/assets/7872057/e5b47d35-1cbb-4b37-9868-117ab442591b)
The fix in: https://github.com/qgis/QGIS/pull/39777 seems to be for geometry generated symbols only, not offset ones.
