### ISSUE TITLE
Cannot add delimited text layers on master

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#39968]
Try adding https://github.com/qgis/QGIS/files/5524518/test.txt

works fine on 3.16. Tested on Windows.
`
2020-11-11T09:40:57     CRITICAL    Layer is not valid : The layer file:///C:/Users/qgis/Desktop/test.csv?type=csv&maxFields=10000&detectTypes=yes&geomType=none&subsetIndex=no&watchFile=no is not a valid layer and can not be added to the map. Reason: `

**Comment by roya0045** [comment]
Does it work ok with gdal/ogr on its own?

**Comment by jgrocha** [comment]
It works on Linux. It continues to be just a Windows related problem, right?

**Comment by gioman** [comment]
> Does it work ok with gdal/ogr on its own?

it does.

**Comment by gioman** [comment]
> It continues to be just a Windows related problem, right?

maybe, I can't test master on Linux right now, if you say it works then is a platform specific issue.

**Comment by jgrocha** [comment]
Import without issues on Linux, current master, gdal 3.3.0dev.

The layer is valid, according to PyQGIS. The console print screen is attached.

![cvs layer test](https://user-images.githubusercontent.com/163681/98941491-9839cb80-24e4-11eb-8739-e8f8c1eb5bcf.png)

I think it is a platform specific problem, but more tests should confirm this.

**Comment by gioman** [comment]
Confirmed, it works on master on Linux.

**Comment by agiudiceandrea** [comment]
The CSV import functionality **works well with qgis-dev 3.15.0-83** (QGIS 3.15.0-Master code revision 12a44c7829 - GDAL/OGR 3.2.0dev) on Windows (OSGeo4W network installer)
A debug log excerpt follows:
```
[12884] ..\..\..\src\providers\delimitedtext\qgsdelimitedtextsourceselect.cpp(415) : (QgsDelimitedTextSourceSelect::updateFieldLists) [69838ms] Updating field lists
[12884] ..\..\..\src\app\qgisapp.cpp(12757) : (QgisApp::addVectorLayerPrivate) [18392ms] Creating new vector layer using file:///C:/Users/[user]/Downloads/test.txt?type=csv&maxFields=10000&detectTypes=yes&geomType=none&subsetIndex=no&watchFile=no with baseName of test and providerKey of delimitedtext
[12884] ..\..\..\src\providers\delimitedtext\qgsdelimitedtextprovider.cpp(79) : (QgsDelimitedTextProvider::QgsDelimitedTextProvider) [2ms] Delimited text file uri is file:///C:/Users/[user]/Downloads/test.txt?type=csv&maxFields=10000&detectTypes=yes&geomType=none&subsetIndex=no&watchFile=no
[12884] ..\..\..\src\providers\delimitedtext\qgsdelimitedtextfile.cpp(218) : (QgsDelimitedTextFile::setFromUrl) [0ms] Delimited text file is: C:/Users/[user]/Downloads/test.txt
[12884] ..\..\..\src\providers\delimitedtext\qgsdelimitedtextfile.cpp(219) : (QgsDelimitedTextFile::setFromUrl) [0ms] Encoding is: UTF-8
[12884] ..\..\..\src\providers\delimitedtext\qgsdelimitedtextfile.cpp(220) : (QgsDelimitedTextFile::setFromUrl) [0ms] Delimited file type is: csv
[12884] ..\..\..\src\providers\delimitedtext\qgsdelimitedtextfile.cpp(221) : (QgsDelimitedTextFile::setFromUrl) [0ms] Delimiter is: [,]
[12884] ..\..\..\src\providers\delimitedtext\qgsdelimitedtextfile.cpp(222) : (QgsDelimitedTextFile::setFromUrl) [0ms] Quote character is: ["]
[12884] ..\..\..\src\providers\delimitedtext\qgsdelimitedtextfile.cpp(223) : (QgsDelimitedTextFile::setFromUrl) [0ms] Escape character is: ["]
[12884] ..\..\..\src\providers\delimitedtext\qgsdelimitedtextfile.cpp(224) : (QgsDelimitedTextFile::setFromUrl) [0ms] Skip lines: 0
[12884] ..\..\..\src\providers\delimitedtext\qgsdelimitedtextfile.cpp(225) : (QgsDelimitedTextFile::setFromUrl) [0ms] Maximum number of fields in record: 10000
[12884] ..\..\..\src\providers\delimitedtext\qgsdelimitedtextfile.cpp(226) : (QgsDelimitedTextFile::setFromUrl) [0ms] Use headers: Yes
[12884] ..\..\..\src\providers\delimitedtext\qgsdelimitedtextfile.cpp(227) : (QgsDelimitedTextFile::setFromUrl) [0ms] Discard empty fields: No
[12884] ..\..\..\src\providers\delimitedtext\qgsdelimitedtextfile.cpp(228) : (QgsDelimitedTextFile::setFromUrl) [0ms] Trim fields: No
[12884] ..\..\..\src\providers\delimitedtext\qgsdelimitedtextprovider.cpp(784) : (QgsDelimitedTextProvider::scanFile) [1ms] Field count for the delimited text file is 3
[12884] ..\..\..\src\providers\delimitedtext\qgsdelimitedtextprovider.cpp(785) : (QgsDelimitedTextProvider::scanFile) [0ms] geometry type is: 100
[12884] ..\..\..\src\providers\delimitedtext\qgsdelimitedtextprovider.cpp(786) : (QgsDelimitedTextProvider::scanFile) [0ms] feature count is: 13
[12884] ..\..\..\src\core\qgsvectorlayer.cpp(1769) : (QgsVectorLayer::setDataProvider) [0ms] Instantiated the data provider plugin
[12884] ..\..\..\src\app\qgisapp.cpp(12785) : (QgisApp::addVectorLayerPrivate) [1ms] got valid layer with 0 sublayers
[12884] ..\..\..\src\core\qgsmaplayer.cpp(165) : (QgsMapLayer::name) [130ms] returning name 'test'
[12884] ..\..\..\src\core\qgsmaplayer.cpp(165) : (QgsMapLayer::name) [10ms] returning name 'test'
[12884] ..\..\..\src\core\qgsmaplayer.cpp(165) : (QgsMapLayer::name) [39ms] returning name 'test'
[12884] ..\..\..\src\core\qgsmaplayer.cpp(165) : (QgsMapLayer::name) [30ms] returning name 'test'
[12884] ..\..\..\src\core\qgsmaplayer.cpp(165) : (QgsMapLayer::name) [62ms] returning name 'test'
[12884] ..\..\..\src\core\qgsmaplayer.cpp(165) : (QgsMapLayer::name) [0ms] returning name 'test'
...
```

It **doesn't works with the latest qgis-dev 3.17.0-11** (QGIS 3.17.0-Master code revision ccdff23dbe - GDAL/OGR 3.3.0dev) on Windows (OSGeo4W network installer)

The Log Messages panel reports:
```
Messages
CRITICAL    Layer is not valid : The layer file:///C:/Users/giudiceandrea/Downloads/test.txt?type=csv&maxFields=10000&detectTypes=yes&geomType=none&subsetIndex=no&watchFile=no is not a valid layer and can not be added to the map. Reason: 
```
```
DelimitedText
WARNING    Errors in file //c/Users/giudiceandrea/Downloads/test.txt
WARNING    File cannot be opened or delimiter parameters are not valid
```

A debug log excerpt follows:
```
[18000] ..\..\..\src\providers\delimitedtext\qgsdelimitedtextsourceselect.cpp(415) : (QgsDelimitedTextSourceSelect::updateFieldLists) [18635ms] Updating field lists
[18000] ..\..\..\src\app\qgisapp.cpp(12961) : (QgisApp::addVectorLayerPrivate) [16139ms] Creating new vector layer using file:///C:/Users/[user]/Downloads/test.txt?type=csv&maxFields=10000&detectTypes=yes&geomType=none&subsetIndex=no&watchFile=no with baseName of test and providerKey of delimitedtext
[18000] ..\..\..\src\providers\delimitedtext\qgsdelimitedtextprovider.cpp(79) : (QgsDelimitedTextProvider::QgsDelimitedTextProvider) [2ms] Delimited text file uri is file://C:/Users/[user]/Downloads/test.txt
[18000] ..\..\..\src\providers\delimitedtext\qgsdelimitedtextfile.cpp(218) : (QgsDelimitedTextFile::setFromUrl) [0ms] Delimited text file is: //c/Users/[user]/Downloads/test.txt
[18000] ..\..\..\src\providers\delimitedtext\qgsdelimitedtextfile.cpp(219) : (QgsDelimitedTextFile::setFromUrl) [0ms] Encoding is: UTF-8
[18000] ..\..\..\src\providers\delimitedtext\qgsdelimitedtextfile.cpp(220) : (QgsDelimitedTextFile::setFromUrl) [0ms] Delimited file type is: csv
[18000] ..\..\..\src\providers\delimitedtext\qgsdelimitedtextfile.cpp(221) : (QgsDelimitedTextFile::setFromUrl) [0ms] Delimiter is: [,]
[18000] ..\..\..\src\providers\delimitedtext\qgsdelimitedtextfile.cpp(222) : (QgsDelimitedTextFile::setFromUrl) [0ms] Quote character is: ["]
[18000] ..\..\..\src\providers\delimitedtext\qgsdelimitedtextfile.cpp(223) : (QgsDelimitedTextFile::setFromUrl) [0ms] Escape character is: ["]
[18000] ..\..\..\src\providers\delimitedtext\qgsdelimitedtextfile.cpp(224) : (QgsDelimitedTextFile::setFromUrl) [0ms] Skip lines: 0
[18000] ..\..\..\src\providers\delimitedtext\qgsdelimitedtextfile.cpp(225) : (QgsDelimitedTextFile::setFromUrl) [0ms] Maximum number of fields in record: 0
[18000] ..\..\..\src\providers\delimitedtext\qgsdelimitedtextfile.cpp(226) : (QgsDelimitedTextFile::setFromUrl) [0ms] Use headers: Yes
[18000] ..\..\..\src\providers\delimitedtext\qgsdelimitedtextfile.cpp(227) : (QgsDelimitedTextFile::setFromUrl) [0ms] Discard empty fields: No
[18000] ..\..\..\src\providers\delimitedtext\qgsdelimitedtextfile.cpp(228) : (QgsDelimitedTextFile::setFromUrl) [0ms] Trim fields: No
[18000] ..\..\..\src\core\qgsmessagelog.cpp(29) : (QgsMessageLog::logMessage) [27ms] 2020-11-13T22:41:38 DelimitedText[1] Errors in file //c/Users/[user]/Downloads/test.txt
[18000] ..\..\..\src\core\qgsmessagelog.cpp(29) : (QgsMessageLog::logMessage) [6ms] 2020-11-13T22:41:38 DelimitedText[1] File cannot be opened or delimiter parameters are not valid
[18000] ..\..\..\src\providers\delimitedtext\qgsdelimitedtextprovider.cpp(334) : (QgsDelimitedTextProvider::scanFile) [2ms] Delimited text source invalid - filename or delimiter parameters
[18000] ..\..\..\src\core\qgsvectorlayer.cpp(1769) : (QgsVectorLayer::setDataProvider) [0ms] Instantiated the data provider plugin
[18000] ..\..\..\src\core\qgsvectorlayer.cpp(1774) : (QgsVectorLayer::setDataProvider) [0ms] Invalid provider plugin file://C:/Users/[user]/Downloads/test.txt
[18000] ..\..\..\src\core\qgsmessagelog.cpp(29) : (QgsMessageLog::logMessage) [15ms] 2020-11-13T22:41:38 Messages[2] Layer is not valid : The layer file:///C:/Users/[user]/Downloads/test.txt?type=csv&maxFields=10000&detectTypes=yes&geomType=none&subsetIndex=no&watchFile=no is not a valid layer and can not be added to the map. Reason: 
[18000] ..\..\..\src\gui\qgsmapcanvas.cpp(529) : (QgsMapCanvas::refresh) [10ms] CANVAS refresh - invalid settings -> nothing to do
[18000] ..\..\..\src\gui\qgsmapcanvas.cpp(529) : (QgsMapCanvas::refresh) [0ms] CANVAS refresh - invalid settings -> nothing to do
[18000] ..\..\..\src\gui\qgsmapcanvas.cpp(529) : (QgsMapCanvas::refresh) [0ms] CANVAS refresh - invalid settings -> nothing to do
[18000] ..\..\..\src\gui\qgsmapcanvas.cpp(529) : (QgsMapCanvas::refresh) [0ms] CANVAS refresh - invalid settings -> nothing to do
[18000] ..\..\..\src\providers\delimitedtext\qgsdelimitedtextsourceselect.cpp(415) : (QgsDelimitedTextSourceSelect::updateFieldLists) [5ms] Updating field lists
[18000] ..\..\..\src\gui\qgsmapcanvas.cpp(529) : (QgsMapCanvas::refresh) [2929ms] CANVAS refresh - invalid settings -> nothing to do
```

The CSV file is correctly opened by both OGR versions 3.2.0 dev and 3.3.0 dev:

```
C:\>ogrinfo --version
GDAL 3.2.0dev, released 2020/99/99

C:\>ogrinfo CSV:C:\Users\[user]\Downloads\test.txt test
INFO: Open of `CSV:C:\Users\[user]\Downloads\test.txt'
      using driver `CSV' successful.

Layer name: test
Geometry: None
Feature Count: 13
Layer SRS WKT:
(unknown)
id: String (0.0)
name: String (0.0)
age: String (0.0)
...
```

```
C:\>ogrinfo --version
GDAL 3.3.0dev, released 2021/99/99

C:\>ogrinfo CSV:C:\Users\[user]\Downloads\test.txt test
INFO: Open of `CSV:C:\Users\[user]\Downloads\test.txt'
      using driver `CSV' successful.

Layer name: test
Geometry: None
Feature Count: 13
Layer SRS WKT:
(unknown)
id: String (0.0)
name: String (0.0)
age: String (0.0)
...
```

**Comment by nyalldawson** [comment]
The underlying issue is an incomplete encodeUri/decodeUri implementation for this provider. It doesn't provide a lossless round trip. Also same cause for the other ticket about changing the data source of a CSV results in a broken layer.

**Comment by jef-n** [comment]
Renamed to .csv or also prefixed with CSV: the file is addable.

**Comment by agiudiceandrea** [comment]
> ogrinfo also fails if you drop the CSV: prefix.

This anyway happens with both 3.2.0dev and 3.3.0dev
```
C:\>ogrinfo --version
GDAL 3.2.0dev, released 2020/99/99
C:\>ogrinfo C:\Users\giudiceandrea\Downloads\test.txt
FAILURE:
Unable to open datasource `C:\Users\giudiceandrea\Downloads\test.txt' with the following drivers.

C:\>ogrinfo --version
GDAL 3.3.0dev, released 2021/99/99
C:\>ogrinfo C:\Users\giudiceandrea\Downloads\test.txt
FAILURE:
Unable to open datasource `C:\Users\giudiceandrea\Downloads\test.txt' with the following drivers.
```

**Comment by agiudiceandrea** [comment]
> Renamed to .csv or also prefixed with CSV: the file is addable

This only works adding the file using "Data Source Manager | Vector". It doesn't works using "Data Source Manager | Delimited Text".

**Comment by agiudiceandrea** [comment]
Hi @nyalldawson, it seems to me this issue is related to https://github.com/qgis/QGIS/issues/39847 and was introduced with https://github.com/qgis/QGIS/commit/1132494fcb679e814857d5cf7fa4f1712b52f5e1 which modified QgisApp::addVectorLayerPrivate

It seems confirmed testing the Windows MXE builds: last working build is at cfbb292bad0652057629afe31e977c1456593e4e, first non working build is at 1132494fcb679e814857d5cf7fa4f1712b52f5e1

**Comment by nyalldawson** [comment]
It is -- the delimited text provider's implementation of encode/decodeuri need to be made lossless. That will fix this and other related issues.

**Comment by nirvn** [comment]
Fixed.

**Comment by agiudiceandrea** [comment]
The issue https://github.com/qgis/QGIS/issues/39968 is still present with QGIS 3.17.0-Master (code revision c54c2ee353) installed on Windows via OSGeo4W (qgis-dev 3.17.0-12):

`CRITICAL    Layer is not valid : The layer file:///C:/Users/[user]/Downloads/test.txt?type=csv&maxFields=10000&detectTypes=yes&geomType=none&subsetIndex=no&watchFile=no is not a valid layer and can not be added to the map. Reason: `
```
WARNING    Errors in file //c/Users/[user]/Downloads/test.txt
WARNING    File cannot be opened or delimiter parameters are not valid
```

**Comment by agiudiceandrea** [comment]
Fixed now also on Windows with 61c9a9d8a65ffaceb06375b7e720d2078349e7a0 (https://github.com/qgis/QGIS/pull/40089).
