### ISSUE TITLE
Multi-edit attribute tool is very slow when using PostGIS data source

### ISSUE THREAD

**Issue by SrNetoChan** [qgis/QGIS#40040]
**Describe the bug**

The ![](https://user-images.githubusercontent.com/3607161/99137218-2f0ba280-2621-11eb-8715-e22d1157e603.png) *Modify attributes of all selected features simultaneously* (AKA multi-edit attribute tool) is very slow when the data source is PostGIS, even on local databases.

**How to Reproduce**

1. Load a table from a local PostGIS database with at least a few hundred features, and preferably with at least 10 columns
2. Start editing
3. Select all features
4. Click the ![](https://user-images.githubusercontent.com/3607161/99137218-2f0ba280-2621-11eb-8715-e22d1157e603.png) *Modify attributes of all selected features simultaneously* button
5. Wait...
6. If not done already, enable the offline editing, and use it to make the layer offline
7. Repeat steps 2-4 and see how it's much faster using the geopackage source

**QGIS and OS versions**

QGIS version | 3.16.0-Hannover | QGIS code revision | 43b64b13f3
-- | -- | -- | --
Compiled against Qt | 5.12.8 | Running against Qt | 5.12.8
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.31.1 | Running against SQLite | 3.31.1
PostgreSQL Client Version | 12.4 (Ubuntu 12.4-0ubuntu0.20.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 6.3.1 | Running against PROJ | Rel. 6.3.1, February 10th, 2020
OS Version | Ubuntu 20.04.1 LTS
Active python plugins | db_manager; processing; MetaSearch

Also tested on 3.10.11, same behavior

**Additional context**

I have compared several PostGIS instances, some local, other remote.

**Comment by SrNetoChan** [comment]
As an example, in my tests:
PostGIS : 55 secs
Geopackage : 8 secs

**Comment by gioman** [comment]
By the way, with PostGIS layers the multi-edit tools is super slow to open  even if just **one** feature is selected.

**Comment by gioman** [comment]
Fixed by https://github.com/qgis/QGIS/pull/41382

**Comment by SrNetoChan** [comment]
@gioman this ticket was related to the multi-edit tool outside the attribute table. And While I see great improvements inside the attribute table it does not solve this one.

**Comment by gioman** [comment]
@SrNetoChan yes, that patch also solved the multi-edit tool slowness.

**Comment by SrNetoChan** [comment]
I have just tried... even two feature takes forever to open if the layer is postgis.

**Comment by gioman** [comment]
> I have just tried... even two feature takes forever to open if the layer is postgis.

@SrNetoChan you sure you have a build with the patch? I tested the patch and in my case (thousands of selected features on a remote server) it worked ok.

**Comment by gioman** [comment]
@SrNetoChan this was my ticket https://github.com/qgis/QGIS/issues/36863
