### ISSUE TITLE
Errors while adding a feature with a polymorphic relation

### ISSUE THREAD

**Issue by troopa81** [qgis/QGIS#41962]
**Describe the bug**

I meet several errors when I try to add a feature with a polymorphic relation defined. I try to setup 2 relations N:M between *pipe* and *manhole* objet on one side and the attached docs on the other side. *obj2doc* is the association table.

**How to Reproduce**

1. Create a dabatase and initialize it with the following instructions
```sql
create extension postgis;

create table docs ( id serial primary key , filepath  varchar ); 

insert into docs (filepath) values ('pipe_photo1.jpg');
insert into docs (filepath) values ('pipe_photo2.jpg');
insert into docs (filepath) values ('pipe_manual.pdf');
insert into docs (filepath) values ('manhole_photo1.jpg');
insert into docs (filepath) values ('manhole_photo2.jpg');
insert into docs (filepath) values ('manhole_manual.pdf');
insert into docs (filepath) values ('manhole_model.dwg');

create table pipe (  id serial primary key, name varchar );
insert into pipe (name) values ('nom d une pipe');
insert into pipe (name) values ('ceci n est pas une pipe');

create table manhole (  id serial primary key, name varchar ); 
insert into manhole (name) values('manhole1');
insert into manhole (name) values('manhole2');

create table obj2doc ( idobj integer, objtable varchar, iddoc integer, 
CONSTRAINT fk_doc  FOREIGN KEY(iddoc) REFERENCES docs(id));

insert into obj2doc values ( 1, 'pipe', 1 );
insert into obj2doc values ( 1, 'pipe', 3 );
insert into obj2doc values ( 2, 'pipe', 2 );
insert into obj2doc values ( 2, 'pipe', 3 );
insert into obj2doc values ( 1, 'manhole', 4 );
insert into obj2doc values ( 1, 'manhole', 6 );
insert into obj2doc values ( 2, 'manhole', 7 );
insert into obj2doc values ( 2, 'manhole', 5 );
insert into obj2doc values ( 2, 'manhole', 6 );
```
2. Load the following project [poly_relations.tar.gz](https://github.com/qgis/QGIS/files/6067219/poly_relations.tar.gz)
3. Enable/Disable "Automatically create transaction groups where possible". I meet different errors according to the value of this parameter.
3. Follow the instruction in the video

**With transaction group**

![with_transaction_group](https://user-images.githubusercontent.com/14358135/109620050-bd0c8a00-7b39-11eb-8d4d-3181456a324d.gif)

The document is not created.

**Without transaction group**

![without_transaction_group](https://user-images.githubusercontent.com/14358135/109620045-bbdb5d00-7b39-11eb-948a-3c4f4037ffc1.gif)

The document is created but the link between *pipe* and *doc* is broken, *objtable* field in *obj2doc* layer is missing and should be *pipe*.

Also, I cannot start editing *docs* from the relation editor, and when I start editing with the mainwindow button, the relation editor button stay greyed while I can create an entry with the new entry button.

**QGIS and OS versions**

Debian bullseye
QGIS a90e3e349a

**Additional context**

**Comment by gioman** [comment]
@troopa81 is this a regression or is just a functionality that never worked as expected?

**Comment by troopa81** [comment]
> @troopa81 is this a regression or is just a functionality that never worked as expected?

More the second, polymorphic relation is a new feature that appears in 3.18 I think

**Comment by gioman** [comment]
@suricactus ping

**Comment by 3nids** [comment]
it's a bit hard from the gif to identify the issues. Could you maybe list them here?

**Comment by domi4484** [comment]
One of the described bugs (layer field not updated) is fixed with #42534

**Comment by 3nids** [comment]
ping @troopa81 
let us know if we can close this one

**Comment by 3nids** [comment]
I'd propose to close this one and re-open with specific bug description if needed.
The polymorphic relations are quite recent and many issues have been fixed lately.

**Comment by troopa81** [comment]
- Creating a child feature of a polymorphic relation WITH transaction group enabled is still failing (first video) 

- Creating a child feature of a polymorphic relation WITHOUT transaction group works, thanks @3nids and @domi4484 

   But the following issues are still exisiting

> Also, I cannot start editing docs from the relation editor, and when I start editing with the mainwindow button, the relation editor button stay greyed while I can create an entry with the new entry button.

**Comment by troopa81** [comment]
> I'd propose to close this one and re-open with specific bug description if needed.
The polymorphic relations are quite recent and many issues have been fixed lately.

OK, I'll do it today

**Comment by 3nids** [comment]
@troopa81 I just tried transaction mode (geopackage) with 1-N and N-M relations without troubles.
do you have more details on what is failing?

**Comment by troopa81** [comment]
- Follow step 1 & 2 in the ticket description
- In *Project properties* > *Data Sources*, check "Automatic create transaction group when possible"
- Open pipe attribute form
- From child relation editor widget, start editing and then create a new document
- Error: the document doesn't appear in widget as a new child
