### ISSUE TITLE
Performance issues with geopackage

### ISSUE THREAD

**Issue by pblottiere** [qgis/QGIS#42177]
**Describe the bug**

Thanks to the nightly [report](http://test.qgis.org/perf_test/graffiti/2021_03_10_01_00/report.html) of the [QGIS Server PerfSuite](https://github.com/qgis/QGIS-Server-PerfSuite), I noticed a regression when a `GetCapabilities` request is executed on a project with layers based on geopackage:

![gpkg](https://user-images.githubusercontent.com/9266424/110607934-07ba8180-818c-11eb-801a-de07251decbd.png)

In this case, the `GetCapabilities` request lasts:

- 115 seconds on master
- 114 seconds on 3.16
- 25 seconds on 3.10

I reproduced the issue locally and by comparing flamegraphs, the issue seems to be coming from `QgsSqliteUtils::uniqueFields` called from `QgsOgrProvider::loadFields`:

![fg](https://user-images.githubusercontent.com/9266424/110608913-fd4cb780-818c-11eb-9aa1-9c5ab44845d9.png)
  
The issue is probably visible on QGIS Desktop too (while not tested).

The culprit seems to be https://github.com/qgis/QGIS/pull/36802. Indeed, I'm testing with GDAL 3.0.4, so I'm entering in the `#if GDAL_VERSION_NUM < GDAL_COMPUTE_VERSION(3, 2, 1)` within `QgsSqliteUtils::uniqueFields` method.

**How to Reproduce**

Project and geopackage: [gpkg.tar.gz](https://github.com/qgis/QGIS/files/6114861/gpkg.tar.gz)

**QGIS and OS versions**

Tested on Debian (the perfsuite on docker) and ArchLinux (local build) with 3.10 and master.

**Additional context**

While I tagged the issue as a bug, it may just be a necessary side effect for a healthier situation. In this case, it may be closed immediately.

**Comment by elpaso** [comment]
It should be fixed by https://github.com/qgis/QGIS/pull/41822

**Comment by elpaso** [comment]
@nyalldawson not without introducing bugs in the unique fields handling for gpkg and OGR-managed spatialite: I would not recommend it.

**Comment by pblottiere** [comment]
> It should be fixed by #41822

This PR has been merged 13 days ago but the issue is still visible with current master so I'm not sure.

**Comment by elpaso** [comment]
Ok, let me have a look.

**Comment by elpaso** [comment]
@pblottiere your GDAL is 3.0.4 so you are hitting the issue. There is no solution that I can't think of unless we want to get back to the original issue  #36468

I think it's better to leave it as it is: the performance issue will eventually go away when GDAL is updated.

**Comment by pblottiere** [comment]
> I think it's better to leave it as it is: the performance issue will eventually go away when GDAL is updated.

OK. The only thing that bothers me is that the perfsuite is based on `qgis/qgis3-build-deps` where we also have GDAL 3.0.4. So we'll have a false alarm in the report until GDAL is updated.

Thanks for having taken a look @elpaso :+1:

**Comment by nyalldawson** [comment]
@elpaso i'm curious why the QGIS specific test would be so slow, yet the test on gdal's side is not a problem. What are we doing differently? Why is the fallback logic so slow to run in this situation?

**Comment by elpaso** [comment]
@nyalldawson I had another look at QGIS's implementation and I couldn't spot any particular difference that might explain the difference in performances (which is not demonstrated btw). 

QGIS is using QT containers in some places instead of `std::` and the other difference is that in GDAL I used some functions that we implemented differently in QGIS (`SQLResultGetValue` vs our sqlite utils for instance ).

Besides that, `QgsOgrProvider::loadFields()` is being called multiple times in some situations (this was **not** introduced by my patch though) and it calls the unique detection logic all the times, and it also invalidates all connections to the resource.

I think there is room for optimizations.

**Comment by elpaso** [comment]
@pblottiere can you check if this patch #42412 halves the calls to `QgsSqliteUtils::uniqueFields` and has an impact on the perf tests?

**Comment by pblottiere** [comment]
@elpaso yes I'll take a look tomorrow :+1:. Thanks for investigating :).

**Comment by pblottiere** [comment]
With the `optimization-ogr-avoid-double-load-fields-call` branch from https://github.com/qgis/QGIS/pull/42412, the response time for the `GetCapabilities` request is ~65 seconds.

On the same branch but without the fixing commit (to compare with the exact same history), the response time for the same request is  ~120 seconds. So it's definitely a good move!

Once merged, we'll be 2x faster than current master (but still 3x slower than 3.10).
