### ISSUE TITLE
Cloud optimized GeoTIFF (COG) layer does not use proxy

### ISSUE THREAD

**Issue by jratike80** [qgis/QGIS#42870]
As discussed on the mailing list https://lists.osgeo.org/pipermail/qgis-user/2021-April/048665.html QGIS does not use the proxy that is configured in general settings when adding a raster file either with "Add raster layer - Protocol - URI" or with "Add raster layer - File - /vsicurl/URI"

Connection through a proxy does succeed if the environment variable `GDAL_HTTP_PROXY ` is set.

Even when the connection works the http requests that are generated are not logged by the development tools.

Issue was found with QGIS 3.18 from OSGeo4W. Test URL:
http://latuviitta.kapsi.fi/data/dem10m/dem10.tif

**Comment by nyalldawson** [comment]
This is already fixed - you just need a build with GDAL 3.2 or later

**Comment by jratike80** [comment]
I tried to use COGs with QGIS 3.24, built with GDAL 3.4.1 (OSGeo4W) and it did not work with our proxy server even the proxy is configured in Options-Network (Proxy Type=DefaultProxy) and connections to WMS/WMTS services are OK with the proxy.

Setting either `https_proxy` or `GDAL_HTTP_PROXY` as an environmental variable before launching QGIS makes COGs to work. Same QGIS version on my home computer that does not need proxy reads COGs out-of-the-box.

The issue, if I understand it right, is that Add Raster layer-Protocol does not get the proxy from the QGIS settings. Two messages from the QGIS log are pasted below. The error message is not very informative, just "HTTP response code: 0" and the development tools do not show any info.
```
2022-03-09T12:59:33     CRITICAL    Unsupported Data Source : /vsicurl/https://oin-hotosm.s3.amazonaws.com/62272fdd1ea0da00077c0c7c/0/62272fdd1ea0da00077c0c7d.tif is not a supported raster data source
             HTTP response code on https://oin-hotosm.s3.amazonaws.com/62272fdd1ea0da00077c0c7c/0/62272fdd1ea0da00077c0c7d.tif: 0
2022-03-09T13:03:43     CRITICAL    Unsupported Data Source : /vsicurl/http://latuviitta.kapsi.fi/data/dem10m/dem10.tif is not a supported raster data source
             HTTP response code on http://latuviitta.kapsi.fi/data/dem10m/dem10.tif: 0  
```

**Comment by pathmapper** [comment]
This is still an issue -> https://github.com/qgis/QGIS/issues/51956#issuecomment-1929232244
