### ISSUE TITLE
GenerateXYZ (MBTiles) multithreading problem

### ISSUE THREAD

**Issue by JKBWP** [qgis/QGIS#47738]
### What is the bug or the crash?

There seems to be a problem with multithreading / threadpool in the processing script to generate MBTiles (see python output below). When generating bigger maps with higher zoom levels (15-16), the script crashes due to a 'database locked' error. When I limit the max. threads to 1 in the settings, it works. But with more than 1 threads, it crashes constantly.

### Steps to reproduce the issue

**Python output:**

Algorithmus XYZ-Kacheln erzeugen (MBTiles) startet…
Eingabeparameter:
{ 'BACKGROUND_COLOR' : QColor(0, 0, 0, 0), 'DPI' : 96, 'EXTENT' : '1151878.987200000,1172386.320600000,6759460.419700000,6776728.410700000 [EPSG:3857]', 'METATILESIZE' : 4, 'OUTPUT_FILE' : 'Y:/basemaps/CLAU_basemap_dop.mbtiles', 'QUALITY' : 75, 'TILE_FORMAT' : 0, 'ZOOM_MAX' : 16, 'ZOOM_MIN' : 14 }

Using 16 CPU Threads:
Generating tiles for zoom level: 14
Generating tiles for zoom level: 15
Generating tiles for zoom level: 16
Traceback (most recent call last):
File "C:\OSGeo4W/apps/qgis-ltr/./python/plugins\processing\algs\qgis\TilesXYZ.py", line 455, in processAlgorithm
self.generate(writer, parameters, context, feedback)
File "C:\OSGeo4W/apps/qgis-ltr/./python/plugins\processing\algs\qgis\TilesXYZ.py", line 316, in generate
for result in threadPool.map(self.renderSingleMetatile, metatiles_by_zoom[zoom]):
File "C:\OSGeo4W\apps\Python39\lib\concurrent\futures\_base.py", line 608, in result_iterator
yield fs.pop().result()
File "C:\OSGeo4W\apps\Python39\lib\concurrent\futures\_base.py", line 438, in result
return self.__get_result()
File "C:\OSGeo4W\apps\Python39\lib\concurrent\futures\_base.py", line 390, in __get_result
raise self._exception
File "C:\OSGeo4W\apps\Python39\lib\concurrent\futures\thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "C:\OSGeo4W/apps/qgis-ltr/./python/plugins\processing\algs\qgis\TilesXYZ.py", line 230, in renderSingleMetatile
self.writer.write_tile(tile, tileImage)
File "C:\OSGeo4W/apps/qgis-ltr/./python/plugins\processing\algs\qgis\TilesXYZ.py", line 401, in write_tile
self._init_zoom_layer(tile.z)
File "C:\OSGeo4W/apps/qgis-ltr/./python/plugins\processing\algs\qgis\TilesXYZ.py", line 393, in _init_zoom_layer
self._execute_sqlite("UPDATE metadata SET value='{}' WHERE name='bounds'".format(bounds))
File "C:\OSGeo4W/apps/qgis-ltr/./python/plugins\processing\algs\qgis\TilesXYZ.py", line 373, in _execute_sqlite
conn.execute(cmd)
sqlite3.OperationalError: database is locked

Execution failed after 20.14 Sekunden

### Versions

QGIS 3.22.4-Białowieża (LTR)

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by JKBWP** [comment]
Thanks for your answer. I did some further testing and the problem seems to be that the output file is on a network drive. With a local file on the same computer, it works as expected. But if I try to save the map to a network drive (shared folder on a NAS), it crashed whenever more than 1 thread is used.

**Comment by inforithmics** [comment]
I have the same Problem, But the sqlite file is on a local Disk. It crashes roughly after one minute of running with this exception.

With Qgis Version 3.20.3 it works. 
With Qgis Version 3.24.1 it does not work.
With Qgis Version 3.22.5 it does not work.

**Comment by inforithmics** [comment]
in this function the error occurs

  ```
def _execute_sqlite(self, *commands):
        conn = sqlite3.connect(self.filename)
        for cmd in commands:
            conn.execute(cmd)
        conn.commit()
        conn.close()
```

maybe in conn.execute(cmd) a retry logic could be implemented. On lock try again after a certain time. maybe the try again timespans could be increasing 10ms 20ms 50ms 100ms 200ms ...

**Comment by inforithmics** [comment]
StackOverflow article

https://stackoverflow.com/questions/15143871/simplest-way-to-retry-sqlite-query-if-db-is-locked

**Comment by inforithmics** [comment]
Maybe the Timeout needs to be increased. because Databases on network Drives and Bitlocker Drives tend to be slower.

**Comment by inforithmics** [comment]
Maybe I should say that I have 20 Concurrent Threads.

**Comment by JKBWP** [comment]
Since I ran into the some problem again (this time with a local file), I experimented a bit with the python function mentioned above. The default timeout for sqlite3.connect is 5 seconds and simply increasing it to 30 seconds did the trick in my case...
`conn = sqlite3.connect(self.filename, timeout=30)`

**Comment by inforithmics** [comment]
Unfortunatly increasing the timeout didn't help (It crashed roughly after 1m and 30 seconds (30 seconds additional timeout))

**Comment by inforithmics** [comment]
setting the conn.isolation_level = None works for me (Because there are only inserts there is no need for specific Isolation.

```
 def _execute_sqlite(self, *commands):
        conn = sqlite3.connect(self.filename)        
        conn.isolation_level = None                
        for cmd in commands:            
            conn.execute(sql)
        conn.commit()
        conn.close()
```

**Comment by inforithmics** [comment]
I compared the the qgis version where it works and it doesn't work

does not work:

```
for result in threadPool.map(self.renderSingleMetatile, metatiles_by_zoom[zoom]):
                        # re-raise exceptions from threads
                        _ = result
```

works:
` threadPool.map(self.renderSingleMetatile, metatiles_by_zoom[zoom])`

I think the Version where it worked it simply swalled the exceptions and the new Version throws them so they become visible.

**Comment by Etmutt** [comment]
having the same issue here. local file, 4 thread; is their any work around ?

**Comment by inforithmics** [comment]
The workaround I found was using QGis 3.20.3

**Comment by agiudiceandrea** [comment]
> The workaround I found was using QGis 3.20.3

@inforithmics, does restoring the line `threadPool.map(self.renderSingleMetatile, metatiles_by_zoom[zoom])` makes the algorithm work? If so, you could use a newer version of QGIS, like 3.22 or 3.24, and just modify the TilesXYZ.py script accordingly.

The change in the code your reported in https://github.com/qgis/QGIS/issues/47738#issuecomment-1076268487 was introduced with PR https://github.com/qgis/QGIS/pull/47336.

**Comment by nyalldawson** [comment]
> The change in the code your reported in https://github.com/qgis/QGIS/issues/47738#issuecomment-1076268487 was introduced with PR https://github.com/qgis/QGIS/pull/47336.

Well, not introduced by that fix. Prior to that fix the tile just would be silently missing. I'd argue that showing an error is better than silent data loss.

**Comment by Etmutt** [comment]
just tried on 3.22 ; changing the script back does the trick. Otherwise the process systematically fails. Not perfect, but better a few tiles missing than nothing at all

**Comment by agiudiceandrea** [comment]
@Etmutt, good to know. Anyway I agree with @nyalldawson that raise the error is better and fairer for the user than silently miss tiles...

**Comment by davdent** [comment]
I am having the same problem with QGIS 3.22 but am having difficulties understanding the workaround. How exactly would I find and modify the python script? Thank you.

**Comment by rideearthtom** [comment]
I can confirm that the abovementioned fix at least allows the process to complete.

On MacOS the path is `/Applications/QGIS.app/Contents/Resources/python/plugins/processing/algs/qgis/TilesXYZ.py`

Replace lines 316-318 with

`threadPool.map(self.renderSingleMetatile, metatiles_by_zoom[zoom])`

**Comment by agiudiceandrea** [comment]
@rideearthtom this issue has been fixed: see https://github.com/qgis/QGIS/pull/49090/files

**Comment by rideearthtom** [comment]
> @rideearthtom this issue has been fixed, probably in a better way: see https://github.com/qgis/QGIS/pull/49090/files.

Ah, thank you!

**Comment by BerndFfm** [comment]
I now have Version 3.26.1-2 and I still have the error "sqlite3.OperationalError: database is locked" when creating mbtiles files. Max threads is set to 16.
Journal mode has changed, I can see the extension of the temp-files has changed.

I have a windows 10 pc with ssd.

#Bernd

**Comment by inforithmics** [comment]
I tested the patch on a Windows 11 PC with ssd and 40 Threads and it worked. So maybe something other is interfering like a Virus Scanner or a Task that hammers the ssd. And yesterday I created a Mbtile with Version 1.26.1-2 in worked flawlessly.

Have you checked that you use the right QGis Version, installing a newer Qgis Version does not uninstall the older one. But installs a new one. So when you have Qgis 3.26.0 installed installing 3.26.1 you have two Qgis Versions installed. 3.26.1 and 3.26.0

**Comment by inforithmics** [comment]
I read about Journaling modes of SQLite and I think journaling mode memory could help because it has less IO.

**Comment by mvdovare** [comment]
Hi All,
Please could you take a look at the snapshot below? QGIS **3.26.3**
I am trying to run the Batch Process of generating MBTiles based on imported json settings.
I am trying a different number of extents and every time the process stops at different levels of completeness, e.g. 5%, 16%, etc.
![image](https://user-images.githubusercontent.com/80451333/191767855-c5eccafe-d909-4752-a170-1804c34ba306.png)

If try with few inputs (several row) - works correctly, but I think the problem not in the amount of inputs.
Also, I tried with a different number of threads and used cores. Nothing helps (
Thank you in advance.

**Comment by MatthewHerbst** [comment]
> @rideearthtom this issue has been fixed, probably in a better way: see https://github.com/qgis/QGIS/pull/49090/files.

I am running into this same issue on QGIS 3.26.3, and I verified that the changes in the mentioned PR are present on my system (a 2021 MacBook Pro with an M1 Pro chip, 32gb RAM, 1tb storage space). I am running the MBTiles generation on an extract (eastern Australia) of the [Open Street Map water polygon dataset](https://osmdata.openstreetmap.de/data/water-polygons.html). I have tried everything from 100 down to 40 threads, and consistently run into the error once I get to zoom levels 14/15.

This issue is not fixed.

**Comment by MatthewHerbst** [comment]
> I can confirm that the abovementioned fix at least allows the process to complete.
> 
> On MacOS the path is `/Applications/QGIS.app/Contents/Resources/python/plugins/processing/algs/qgis/TilesXYZ.py`
> 
> Replace lines 316-318 with
> 
> `threadPool.map(self.renderSingleMetatile, metatiles_by_zoom[zoom])`

Using the fix above I was able to run a three day job recently on a Mac M1 using 500 threads without issue
