### ISSUE TITLE
3.22.4 Geometry Generator: 'collect' missing symbology in legend

### ISSUE THREAD

**Issue by JamesHowsam** [qgis/QGIS#48672]
### What is the bug or the crash?

When using the 'collect' function as a geometry generator in symbology, the symbology displays as blank in the legend symbol of a layout.

### Steps to reproduce the issue

1) Create a polygon layer. Set the symbology as a geometry generator with the most basic 'collect' function [ 
  collect($geometry)   ] assign desired symbology

2) Create a layout, add legend, enable that layer. Symbol will be blank (Error)

3) either adjust symbology to remove 'collect' function or set custom symbol in legend that does not include 'collect' function. Symbology will now display.

### Versions

3.22.4 

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nyalldawson** [comment]
I can't reproduce this on 3.24 or later -- can you confirm that the issue is fixed?

**Comment by JamesHowsam** [comment]
I am using version 3.22.4-Białowieża

The problem is still occurring on 3.22.4

James Howsam MCIEEM
Senior Ecologist
Ecology by Design Ltd
[signature_38284627]
phone: 01865 893347
mob: 07930 411368

www.ecologybydesign.co.uk<http://www.ecologybydesign.co.uk/>

Please click here to leave us feedback<https://www.ecologybydesign.co.uk/feedback-form>

[signature_835488789]            [signature_665853444] <https://www.ecologybydesign.co.uk/careers>

Ecology by Design Ltd registered in England & Wales, registration number: 9318075. This email is intended for the above mentioned recipient only and may contain privileged or confidential information. Any use of, or taking of any action in reliance upon, this information by parties other than the intended recipient is prohibited. If you have received this in error, please notify the sender, delete it and do not use or disclose any of the information contained in it. The contents of an attachment to this e-mail may contain software viruses which could damage your own computer system. While Ecology by Design Limited has taken every reasonable precaution to minimise this risk, we cannot accept liability for any damage which you sustain as a result of software viruses. You should carry out your own virus checks before opening the attachment.


From: Nyall Dawson ***@***.***>
Reply to: qgis/QGIS ***@***.***>
Date: Friday, 3 June 2022 at 05:44
To: qgis/QGIS ***@***.***>
Cc: James Howsam ***@***.***>, Author ***@***.***>
Subject: Re: [qgis/QGIS] 3.22.4 Geometry Generator: 'collect' missing symbology in legend (Issue #48672)


I can't reproduce this on 3.24 or later -- can you confirm that the issue is fixed?

**Comment by nyalldawson** [comment]
If it's working on 3.24 or master then it's unlikely to be fixed for 3.22 - the changes are too extreme to backport

**Comment by JamesHowsam** [comment]
Thanks, have updated to 3.22.7-Białowieża and that seems to have fixed the issue.

Best wishes,

James Howsam MCIEEM
Senior Ecologist
Ecology by Design Ltd
[signature_570837025]
phone: 01865 893347
mob: 07930 411368

www.ecologybydesign.co.uk<http://www.ecologybydesign.co.uk/>

Please click here to leave us feedback<https://www.ecologybydesign.co.uk/feedback-form>

[signature_835488789]            [signature_1168969459] <https://www.ecologybydesign.co.uk/careers>

Ecology by Design Ltd registered in England & Wales, registration number: 9318075. This email is intended for the above mentioned recipient only and may contain privileged or confidential information. Any use of, or taking of any action in reliance upon, this information by parties other than the intended recipient is prohibited. If you have received this in error, please notify the sender, delete it and do not use or disclose any of the information contained in it. The contents of an attachment to this e-mail may contain software viruses which could damage your own computer system. While Ecology by Design Limited has taken every reasonable precaution to minimise this risk, we cannot accept liability for any damage which you sustain as a result of software viruses. You should carry out your own virus checks before opening the attachment.


From: Nyall Dawson ***@***.***>
Reply to: qgis/QGIS ***@***.***>
Date: Monday, 6 June 2022 at 11:06
To: qgis/QGIS ***@***.***>
Cc: James Howsam ***@***.***>, Author ***@***.***>
Subject: Re: [qgis/QGIS] 3.22.4 Geometry Generator: 'collect' missing symbology in legend (Issue #48672)


If it's working on 3.24 or master then it's unlikely to be fixed for 3.22 - the changes are too extreme to backport
