### ISSUE TITLE
CityGML Import not working with LoD2 files

### ISSUE THREAD

**Issue by 3DComputerGraphics** [qgis/QGIS#51647]
### What is the bug or the crash?

Dear madams or sirs,

Using QGIS 3.28.2, importing a CityGML file (LoD2) a vector layer is being made, but the geometry (spatial expansion) does not show up. Similar issues are metioned here: https://gis.stackexchange.com/questions/444849/visualizing-german-alkis-lod2-citygml-data-in-3d-map-view-qgis-3-22 and https://gis.stackexchange.com/questions/379755/how-to-convert-citygml-lod2-to-digital-surface-model. Any ideas? Thanks in advance!

Best regards
who

### Steps to reproduce the issue

Open QGIS Desktop 3.28.2
Add Vector Layer
Source (*.gml)

### Versions

QGIS-Version | 3.28.2-Firenze | QGIS-Codeversion | b47e00ba601
Qt-Version | 5.15.3
Python-Version | 3.9.5
GDAL-Version | 3.6.1
PROJ-Version | 9.1.1
EPSG-Registraturdatenbankversion | v10.076 (2022-08-31)
GEOS-Version | 3.11.1-CAPI-1.17.1
SQLite-Version | 3.39.4
PDAL-Version | 2.4.3
PostgreSQL-Client-Version | unknown
SpatiaLite-Version | 5.0.1
QWT-Version | 6.1.6
QScintilla2-Version | 2.13.1
BS-Version | Windows 10 Version 2009

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by coefficient1900** [comment]
Look at this, https://gis.stackexchange.com/questions/449517/reading-gml-data-in-qgis
same problem here.

**Comment by rouault** [comment]
Will be fixed in GDAL 3.7.0 (to be released in may 2023) per https://github.com/OSGeo/gdal/pull/7168

**Comment by dawgermany** [comment]
> Will be fixed in GDAL 3.7.0 (to be released in may 2023) per [OSGeo/gdal#7168](https://github.com/OSGeo/gdal/pull/7168)

Will this also be fixed in the mac os version? the latest release build still has GDAL 3.3.2
see https://github.com/qgis/QGIS-Mac-Packager/issues/153

**Comment by mls3000** [comment]
Importing a LoD2-CityGML file from the city of Hamburg (https://daten-hamburg.de/opendata/3d_stadtmodell_lod2/LoD2-DE_HH_2023-04-01.zip), no 3D buildings or roofs are being imported. The building footprints are being properly imported.
This occurs under both macOS and Windows using QGIS version 3.32.2.

**Comment by mls3000** [comment]
Problem persists with v3.38.0.
Importing the same GML in FZKViewer shows that the geometry is indeed intact with full 3d buildings.

**Comment by JuanBreva** [comment]
In QGIS 3.38.3-Grenoble, running under MacOS, the problem persists.

**Comment by agiudiceandrea** [comment]
> Importing a LoD2-CityGML file from the city of Hamburg (https://daten-hamburg.de/opendata/3d_stadtmodell_lod2/LoD2-DE_HH_2023-04-01.zip), no 3D buildings or roofs are being imported. The building footprints are being properly imported. This occurs under both macOS and Windows using QGIS version 3.32.2.

@rouault is the issue actually fixed or is there a missing functionality in GDAL/OGR - QGIS?

**Comment by mls3000** [comment]
Still does not work in 3.44.7-Solothurn.
