### ISSUE TITLE
drag&drop from a .gdb to a .gdb will damage field assignment

### ISSUE THREAD

**Issue by coefficient1900** [qgis/QGIS#52017]
### What is the bug or the crash?

The "drag and drop" feature to add a layer to a existing .gdb can cause severe issues with the fields of that layer, if the source is a .gdb too.

In other words, export a layer from a .gdb to another .gdb by drag&drop will mess up the field assignment in the attribute table.

(test data for the steps described below:)
[data.zip](https://github.com/qgis/QGIS/files/10824215/data.zip)

### Steps to reproduce the issue

1. You can start with a simple shape file and export this data to a new ESRI File Geodatabase by "export" -> "save feature as" ->"gdb"
![shape](https://user-images.githubusercontent.com/86417466/221183415-7a50d19f-533f-4ab1-adb3-112a27b96653.JPG)

2. The generated .gdb contains the data from the shapefile with a new first column OBJECTID.
![gdb1](https://user-images.githubusercontent.com/86417466/221183680-b95e7ccd-0733-46d4-b859-93f6890b7df1.JPG)

3. Take the result from "2." and do a drag&drop operation with it to another .gdb. There an additional new column named OBJECTID_ with zeros is generated and the field assignment for all following fields is busted.
![gdb2](https://user-images.githubusercontent.com/86417466/221184569-41a89e4d-e9b3-402a-b930-52afc5ca5da1.JPG)

Here the comparison between the two .gdb layers:
![comparison](https://user-images.githubusercontent.com/86417466/221184698-214aff7d-6e17-4dff-b94d-515921d4ce4c.JPG)

The "export" -> "save feature as" -> "gdb" feature is not affected by this incidence. There the fields are exported always correctly.

(Checked with a Windows machine.)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.28.3-Firenze | QGIS code revision | c12bcb2f76c
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.6.2
PROJ version | 9.1.1
EPSG Registry database version | v10.076 (2022-08-31)
GEOS version | 3.11.1-CAPI-1.17.1
SQLite version | 3.39.4
PDAL version | 2.4.3
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
qfieldsync | v4.2.0
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>QGIS version
3.28.3-Firenze
QGIS code revision
[c12bcb2f76c](https://github.com/qgis/QGIS/commit/c12bcb2f76c)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.6.2
PROJ version
9.1.1
EPSG Registry database version
v10.076 (2022-08-31)
GEOS version
3.11.1-CAPI-1.17.1
SQLite version
3.39.4
PDAL version
2.4.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
qfieldsync
v4.2.0
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
@coefficient1900, could you please check if you are experiencing the same bug already reported at https://github.com/qgis/QGIS/issues/51435?

**Comment by coefficient1900** [comment]
@agiudiceandrea seems to be pretty much the same issue. Thanks a lot.

**Comment by agiudiceandrea** [comment]
Thanks for reporting. The issue has been already fixed with https://github.com/qgis/QGIS/pull/51634 and the fix will be incorporated in the next upcoming QGIS versions 3.28.4 and 3.30.0.

**Comment by coefficient1900** [comment]
@agiudiceandrea this should be reopened. With 3.30 which should adress this bug,it is not resolved completely.

The issue with the inserted seconed OBJECTID_ column is fixed. But the last column is still empty.

![filegdb](https://user-images.githubusercontent.com/86417466/223108284-5e128621-5cef-48ed-9d2f-323b9c041a12.JPG)

**Comment by nyalldawson** [comment]
@coefficient1900 can you confirm the gdal version from the qgis about screen one?

**Comment by coefficient1900** [comment]
@nyalldawson I tested it with the current versions 3.30.1 and 3.28.5 and both of them are built with GDAL 3.6.3. There the issue seems to be solved completely.
The behaviour described above only occured with 3.30.0 which has GDAL 3.6.2.

**Comment by agiudiceandrea** [comment]
@nyalldawson so this means the bug may still occur on the upcoming Ubuntu Lunar Lobster 23.04 in which the GDAL version is currently 3.6.2.
