### ISSUE TITLE
Layer Properties panel hangs when changing symbol but Layer Style panel doesn't

### ISSUE THREAD

**Issue by unacomn** [qgis/QGIS#53618]
### What is the bug or the crash?

This is a follow-up to issues #51233 and  #50209 
While the slow loading problem still seems to happen, I've noticed a stranger behavior when changing symbols.

In a project with a lot of print layouts that all have legends, when using the Layer Properties window (from double clicking a layer) and changing the symbol of a layer, QGIS will hang for a considerable amount of time. It will stop responding.
However, when changing the symbol from the Layer Style Panel, there is no delay. The symbols change instantly as they used to do in versions before QGIS 3.22 regardless of how many print layouts existed.

The video below should help exemplify things. I have also attached a dataset with dummy data to provide an example.

### Steps to reproduce the issue
https://github.com/qgis/QGIS/assets/26759956/dc3bb02d-5374-4b5b-a18a-fda342bf57b3

[Issue.zip](https://github.com/qgis/QGIS/files/11886071/Issue.zip)

### Versions

QGIS version
3.32.0-Lima
QGIS code revision
311a8cb8a6
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.0
PROJ version
9.2.1
EPSG Registry database version
v10.088 (2023-05-13)
GEOS version
3.11.2-CAPI-1.17.2
SQLite version
3.41.1
PDAL version
2.5.3
PostgreSQL client version
15.2
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
azimuth_distance_measurement
0.4
contour
2.0.12
coordinates_converter
1.0
deactivate_active_labels
0.5
FreehandRasterGeoreferencer
0.8.3
GeometryShapes
0.7
GroupPointsWithinDistance
0.0.2
HCMGIS
23.2.1
inspireatomclient
0.8.1
joinmultiplelines
Version 0.4.1
kmltools
3.1.29
latlontools
3.6.10
pickLayer
3.9.4.post0
postgisQueryBuilder
2.0.1
profiletool
4.2.6
qfieldsync
v4.5.0
Qgis2threejs
2.7.1
qgis_hats
1.8
SelectWithin
0.4
StreetView
3.2
turbo_volume
0.1
volume_calculation_tool
0.4
wnt
1.3.6
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
otbprovider
2.12.99
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by kitzberdo** [comment]
I can also reproduce this phenomenon. I tried this with my own project and QGIS version 3.32..

**Comment by agiudiceandrea** [comment]
@unacomn thanks for reporting. Have you actually checked if the issue does occur also using a brand new QGIS user profile (it seems not, judging from the long list of external plugin installed in the used QGIS user profile)? Does the issue only occur using QGIS 3.32 or also using QGIS LTR 3.28?

**Comment by unacomn** [comment]
@agiudiceandrea I have tested with a new profile and on different machines, with AMD and Intel CPUs. Note that this is a Windows specific issue. It does not occur on Linux. It actually dawned on me recently that the Layer Properties Window is slightly different on Linux, the buttons aren't in the same order and maybe since 3.22 the Layer Style Panel and the Layer Properties Window use different paths to achieve the same goal.
I've also tested it on 3.28 LTR.

**Comment by CharlesGag** [comment]
Hello,

Same thing is happening to me, it takes a really long time to change the symbologie now. I wanted to report that and found your thread. I was not aware that this was not happening through the layer style panel and I can confirm that this is definitly a thing. 


QGIS version
3.32.1-Lima
QGIS code revision
4a078ecf63
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.1
PROJ version
9.2.1
EPSG Registry database version
v10.088 (2023-05-13)
GEOS version
3.12.0-CAPI-1.18.0
SQLite version
3.41.1
PDAL version
2.5.5
PostgreSQL client version
15.2
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009




Active Python plugins
CalculateGeometry
0.6.8
easy_raster_splitter
2.0
geetimeseriesexplorer
2.0
GeoCoding
2.19
geometric_attributes
0.4
Mergin
2023.2.1
mmqgis
2021.9.10
profiletool
4.2.6
ProjectPackager
0.7.2
qchainage
3.0.1
qgis-maptiler-plugin
3.2
qgis_resource_sharing
1.0.0
QuickOSM
2.2.2
quick_map_services
0.19.33
StreetView
3.2
Submission
0.7
valuetool
3.0.15
VectorBender
0.2.1
volume_calculation_tool
0.4
wbt_for_qgis
1.0.9
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
otbprovider
2.12.99
processing
2.12.99

**Comment by unacomn** [comment]
This issue seems to have been resolved in QGIS 3.34. I'm not sure what particular changed fixed this, but there is no more hanging when changing symbology from that particular style window even in a project that contains 100+ print layouts.

**Comment by CharlesGag** [comment]
I still have the same issue. This is from a project created in 3.32 but now converted to 3.34 not sure if it matters. Still no problem using the Layer style panel, even with a blank user.  Is there anyone who still can recreate this ?

**Comment by agiudiceandrea** [comment]
@CharlesGag, thanks for reporting. Could you please provide a simple project and layer(s) with which the issue does occur?

**Comment by CharlesGag** [comment]
I cannot share this specific projet unfortunately but I will try to work on something. I think it's better than in 3.32, but still way slower than changing the symbology in the Layer Style panel or directly modifying the color of a symbol in your layer list. 

I made a few test and its definitly related to the # of layouts (I have a lot in this project). If I delete them all, it seems to fix the problem. Thanks.
