### ISSUE TITLE
[MSSQL] Add Ring throw SQL Error while saving edits

### ISSUE THREAD

**Issue by j-lippmann** [qgis/QGIS#53698]
### What is the bug or the crash?

Can't Save edits after add ring oder fill ring on a MSSQL MultiPolygon Layer

![grafik](https://github.com/qgis/QGIS/assets/32189541/8968c838-abe6-4648-8cff-2006a25c370d)

### Steps to reproduce the issue

1.     You need a MSSQL Multipolygon Layer
2.     You have a Multipolygon or add a new one
3.     Add a ring to this Multipolygon (see screenshot) or Button "Fill Ring" produce same error
4.     click save edits
5.     error appear

### Versions

QGIS 3.28.8
MSSQL Provider

there are no issues with PostgreSQL

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by j-lippmann** [comment]
the problem also occurs with version 3.26

**Comment by j-lippmann** [comment]
there are no issues with QGIS Version 3.22.13

**Comment by j-lippmann** [comment]
i have attached a mssql database backup (SQL express 2022) with a multipolygon layer to follow along
[qgis_add_ring_bug.zip](https://github.com/qgis/QGIS/files/12013033/qgis_add_ring_bug.zip)

**Comment by j-lippmann** [comment]
the problem also occurs with version 3.30 and 3.32 and actual master

**Comment by j-lippmann** [comment]
the problem still occurs with 3.28.10 and 3.32.2 and master https://github.com/qgis/QGIS/commit/faa7a13373
it would be nice if one of the developers could debug, i can't find the code place with the the bug, thank you very much

**Comment by paul-dorsetcouncil** [comment]
@j-lippmann we also have this issue so I'm also now monitoring to see if there is a solution. It looks like I'll need a work around as there doesn't seem to be much progress on this issue to date.

**Comment by elpaso** [comment]
I had a look to the issue, there are no errors with the SQL syntax. Apparently the SQL server does not accept what seems (to my limited knowledge) to be valid WKT:

```sql
UPDATE [qgis_test].[gh_53698] SET [geom]=geometry::STGeomFromText('MultiPolygon (((-0.17037259615384581 0.32055288461538467, -0.52878605769230747 -0.03028846153846154, 0.17037259615384648 -0.35336538461538458, 0.53383413461538476 -0.18425480769230762, 0.47830528846153886 0.38112980769230775, -0.17037259615384581 0.32055288461538467),CompoundCurve ((-0.07698317307692282 0.08581730769230766, 0.16532451923076952 0.1287259615384615, 0.08203125000000022 -0.06310096153846145, -0.14008413461538427 -0.03281249999999991, -0.07698317307692282 0.08581730769230766))))',4326).MakeValid() WHERE [qgs_fid]=1
```


The problem is with `CompoundCurve`, I am no expert on SQL server and I've done a quick and unsuccessful google search to find out why that is not accepted.

While I could probably write some code to examine the geometries and replace the compound curve if it is a LINESTRING like in this particular case, I would prefer that someone more expert than me on SQL server would explain 

1. why SQL server does not accept what seems perfectly valid WKT
2. what should we do to please SQL server and convince it that the geometry is actually a valid MULTIPOLYGON

I believe that this issue is not strictly related to MULTIPOLYGON.

**Comment by elpaso** [comment]
ok, I stand corrected: that is NOT valid WKT the problem is depper inside QGIS WKT conversion.

**Comment by j-lippmann** [comment]
@elpaso thanks for fixing the add ring issue. i have tested it with actual master, it works now. fill ring is still a problem as i have read.

**Comment by elpaso** [comment]
> @elpaso thanks for fixing the add ring issue. i have tested it with actual master, it works now. fill ring is still a problem as i have read.

Yes, the fill ring part is fixed by https://github.com/qgis/QGIS/pull/55588 which is still stuck in the review process.

**Comment by j-lippmann** [comment]
Hello @elpaso the issue is still present in QGIS 3.34.5 LTR. There are no problems with 3.36.1 and actual master. It's possible to backport the fix to 3.34 LTR?
grazie mille
