### ISSUE TITLE
Some tools incorretly handle curve geometry and segmentize it, even for layers that supports curved geometry.

### ISSUE THREAD

**Issue by Kamzarr** [qgis/QGIS#54386]
### What is the bug or the crash?

It seems that curves are not correctly handled in some tools from Advanced Digitizing Toolbar. For example:

Issue 1: When layer have gometry type of CurvePolygon but feature have simple polygon geometry, then adding ring with curve automatically segmentize this curve into lines. For feature that have geometry with curve this adding curved ring works correctly.

Issue 2: Using "Reshape Feature" and "Offet Curve" also segmentize existing geometry into lines but other tools seems to work ok (vertex tool, move, rotate, scale, trim/extend).

### Steps to reproduce the issue

Issue 1:
1. Create temporary or gpkg layer with geometry type CurvePolygon or MultiSurface
2. Add two polygons: First (A) without any curve, second (B) with curve

![image](https://github.com/qgis/QGIS/assets/75135894/75784166-ee31-4c6b-9b60-d49581eed082)

3. Using "Add Ring" tool, add rings containing curve to both features
4. For feature A ring was segmentized, for feature B ring was not semgmentized because it had curve originally

![image](https://github.com/qgis/QGIS/assets/75135894/84409fb8-6009-4e88-af84-84efef3b9c7f)

Issue 2:
1. Create temporary or gpkg layer with any of curve geometry (CompoundCurve, MultiCurve, CurvePolygon or MultiSurface)
2. Add feature containing curve

![image](https://github.com/qgis/QGIS/assets/75135894/99e37008-84af-42c9-84e3-ef7b6e16175c)

3. Edit feature using "Reshape Feature" tool
4. Curve in feature geometry is automatically segmentized 

Edit 1:
![image](https://github.com/qgis/QGIS/assets/75135894/5e0c3207-f3a6-48e4-8514-6755e6d6ed15)

Edit 2:
![image](https://github.com/qgis/QGIS/assets/75135894/43954ca7-936b-47db-9e8f-de8686269bf0)

Using "OffsetCurve" also segmentize features

### Versions

checked on 3.24.2 and 3.32.1

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by gisuser0** [comment]
Same issue with other tools.
Create a curvepolygon layer (geopackage, postgis or temporary layer) and draw a polygon with at least one curve.
Open the "Processing Toolbox" and run the "Fix geometries" (it doesn't matter if the geometry is correct or not).
In the resulting polygon the curve is converted into segments.
Thx

**Comment by Kamzarr** [comment]
I found another issue, this time in Check Validity tool. For geometries with curve type, checking validity using QGIS method, does not work correctly.
For CurvePolygon and CompoundCurve:
1. Create layer with geometry CurvePolygon or CompoundCurve
2. On this layer draw 2 invalid features (self intesecting): first without curve segment, second with curve
![image](https://github.com/qgis/QGIS/assets/75135894/bfbadb6a-c9da-4e54-8927-bca84c0e6ab8)
3. Perform Check Validity with QGIS method
4. For first feature error was found, but in second error wasn't foud
![image](https://github.com/qgis/QGIS/assets/75135894/9161a217-afe3-466f-b943-1dcaafcc5e4c)

For multi curve geometries:
1. Create MultiCurve or MultiSurface layer
2. Draw any invalid features you like (with self intesection)
I have example with two feautres: one with 3 parts (indluding one part with curve), second with one part and without curves:
![image](https://github.com/qgis/QGIS/assets/75135894/55f5d0ad-6a65-4c2f-ae56-0f9a94794dd5)
3. Perform Check Validity with QGIS method
4. None errors were found
![image](https://github.com/qgis/QGIS/assets/75135894/54ef1479-c47e-4957-bd24-7a567aafae86)

It looks like it doesn't work for any geometry of curve type. 
In case of signle geometries output geometry depends on what you draw, my first example of drawing feature on CompoundCurve layer:
![image](https://github.com/qgis/QGIS/assets/75135894/b4e7bc7e-a500-4dbb-a914-4501a5c8ea39)
so checking validity will work for this geometries without curves

but in multi geometry layers it doesn't matter what you draw, you always will get curve geometry as output (my example):
![image](https://github.com/qgis/QGIS/assets/75135894/5d39d28c-af94-43af-bf50-72804e622e2f)
so checking validity in multi curve geometry layers never work

**Comment by Djedouas** [comment]
@agiudiceandrea @Kamzarr 

> Issue 1: When layer have gometry type of CurvePolygon but feature have simple polygon geometry, then adding ring with curve automatically segmentize this curve into lines. For feature that have geometry with curve this adding curved ring works correctly.

This issue is fixed with #53895

Ping @lbartoletti for discussion, to maybe see if some behaviors described here with tools and processings are like this on purpose or not...

**Comment by alexbruy** [comment]
Fixed in the latest master (ae45e662c6a6f6ad61b3297a3f34efde8a63eec0). Please reopen if necessary.

**Comment by AlisterH** [comment]
> I found another issue, this time in Check Validity tool. For geometries with curve type, checking validity using QGIS method, does not work correctly. For CurvePolygon and CompoundCurve:
> 
> 1. Create layer with geometry CurvePolygon or CompoundCurve
> 2. On this layer draw 2 invalid features (self intesecting): first without curve segment, second with curve
>    ![image](https://private-user-images.githubusercontent.com/75135894/264620506-bfbadb6a-c9da-4e54-8927-bca84c0e6ab8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3NjE1NTIsIm5iZiI6MTcwNDc2MTI1MiwicGF0aCI6Ii83NTEzNTg5NC8yNjQ2MjA1MDYtYmZiYWRiNmEtYzlkYS00ZTU0LTg5MjctYmNhODRjMGU2YWI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDAwNDczMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxM2Q4OGYxOTFkODMwMTFhYzc1MjJjNjU4ZWRmMDk2YWUxNDE2YjlhMzMwNzk4Y2M4ZDRkNDY5MmQzYjg1ZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2sO9gy_Otio4cdZKrSFNoPGfsrU8x-IpYlUfW9Wxc4I)
> 3. Perform Check Validity with QGIS method
> 4. For first feature error was found, but in second error wasn't foud
>    ![image](https://private-user-images.githubusercontent.com/75135894/264621140-9161a217-afe3-466f-b943-1dcaafcc5e4c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3NjE1NTIsIm5iZiI6MTcwNDc2MTI1MiwicGF0aCI6Ii83NTEzNTg5NC8yNjQ2MjExNDAtOTE2MWEyMTctYWZlMy00NjZmLWI5NDMtMWRjYWFmY2M1ZTRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDAwNDczMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiZDY3Yzc1NWViZWNiN2Q0MTM0MzNiM2E2MzQxNWZhYWFkNWVkYzhlYTNhZTU5NDRkZjlkYTU2ZGRlNzE5NWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rmJkrfPxPMTnCsose6OWOJPoCoihMGiVD6-FrpY7Nho)

Do we need to file another ticket for this problem?  It is still present in 3.34.1 (sorry, can't test 3.34.2 right now).

**Comment by bencahill** [comment]
> Issue 2:
> 
> 1. Create temporary or gpkg layer with any of curve geometry (CompoundCurve, MultiCurve, CurvePolygon or MultiSurface)
> 2. Add feature containing curve
> 3. Edit feature using "Reshape Feature" tool
> 4. Curve in feature geometry is automatically segmentized

It doesn't look like Issue 2 was ever solved (specifically, the Reshape Feature bug). I can reproduce it on 3.40.2.

Can this issue be reopened, or does another ticket need to be filed? I can reproduce with the exact steps in the first post.

Thank you.

**Comment by agiudiceandrea** [comment]
I think it would be more effective to open a new issue.

**Comment by agiudiceandrea** [comment]
@Djedouas @AlisterH @Kamzarr see new issue report about the "Issue 2", not yet fixed, at https://github.com/qgis/QGIS/issues/60065.

**Comment by m-kuhn** [comment]
This is a problem in geos which requires a larger undertaking to be fixed. If someone wants to support this initiative, please get in touch.

**Comment by m-kuhn** [comment]
> Fixed in the latest master ([ae45e66](https://github.com/qgis/QGIS/commit/ae45e662c6a6f6ad61b3297a3f34efde8a63eec0)). Please reopen if necessary.

Looks unrelated

**Comment by agiudiceandrea** [comment]
@m-kuhn this issue report contain actually 2 reported issue and a Thor one in a comment. While the 1st issue has been allegedly fixed, the 2nd (and the 3rd) one still occur.
