### ISSUE TITLE
No module named '_gdal' 

### ISSUE THREAD

**Issue by ACalleros** [qgis/QGIS#55519]
### What is the bug or the crash?

I am running Arch linux and updated qgis to the latest release. Since, it hasn't been able to locate gdal. It's the first time I have this kind of problem, what can I do?

`Couldn't load plugin 'processing' 

ModuleNotFoundError: No module named '_gdal' 
Traceback (most recent call last):
  File "/home/adrian/.local/lib/python3.11/site-packages/osgeo/__init__.py", line 30, in swig_import_helper
    return importlib.import_module(mname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "", line 1204, in _gcd_import
  File "", line 1176, in _find_and_load
  File "", line 1147, in _find_and_load_unlocked
  File "", line 676, in _load_unlocked
  File "", line 573, in module_from_spec
  File "", line 1233, in create_module
  File "", line 241, in _call_with_frames_removed
ImportError: libgdal.so.33: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/qgis/utils.py", line 401, in loadPlugin
    __import__(packageName)
  File "/usr/lib/python3.11/site-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/qgis/python/plugins/processing/__init__.py", line 24, in 
    from processing.tools.general import *  # NOQA
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/qgis/python/plugins/processing/tools/general.py", line 30, in 
    from processing.core.Processing import Processing
  File "/usr/lib/python3.11/site-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/qgis/python/plugins/processing/core/Processing.py", line 55, in 
    from processing.algs.qgis.QgisAlgorithmProvider import QgisAlgorithmProvider  # NOQA
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/qgis/python/plugins/processing/algs/qgis/QgisAlgorithmProvider.py", line 45, in 
    from .HypsometricCurves import HypsometricCurves
  File "/usr/lib/python3.11/site-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/qgis/python/plugins/processing/algs/qgis/HypsometricCurves.py", line 25, in 
    from osgeo import gdal, ogr, osr
  File "/usr/lib/python3.11/site-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/adrian/.local/lib/python3.11/site-packages/osgeo/__init__.py", line 35, in 
    _gdal = swig_import_helper()
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/adrian/.local/lib/python3.11/site-packages/osgeo/__init__.py", line 32, in swig_import_helper
    return importlib.import_module('_gdal')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named '_gdal'

Python version: 3.11.6 (main, Nov 14 2023, 09:36:21) [GCC 13.2.1 20230801] 
QGIS version: 3.34.1-Prizren Prizren, exported 

Python Path:
/usr/share/qgis/python
/home/adrian/.local/share/QGIS/QGIS3/profiles/default/python
/home/adrian/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python311.zip
/usr/lib/python3.11
/usr/lib/python3.11/lib-dynload
/home/adrian/.local/lib/python3.11/site-packages
/usr/lib/python3.11/site-packages
/home/adrian/.local/share/QGIS/QGIS3/profiles/default/python`

### Steps to reproduce the issue

1. Open QGIS
2. Open log messages 
3. Click on python errors

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.34.1-Prizren | QGIS code branch | Release 3.34
-- | -- | -- | --
Qt version | 5.15.11
Python version | 3.11.6
Compiled against GDAL/OGR | 3.8.0 | Running against GDAL/OGR | 3.8.1
Compiled against PROJ | 9.3.0 | Running against PROJ | 9.3.1
EPSG Registry database version | v10.098 (2023-11-24)
GEOS version | 3.12.0-CAPI-1.18.0
SQLite version | 3.44.2
PDAL version | 2.6.1
PostgreSQL client version | 16.1
SpatiaLite version | 5.1.0
QWT version | 6.2.0
QScintilla2 version | 2.14.1
OS version | EndeavourOS
  |   |   |  
Active Python plugins
db_manager | 0.1.20

</body></html>QGIS version
3.34.1-Prizren
QGIS code branch
[Release 3.34](https://github.com/qgis/QGIS/tree/release-3_34)
Qt version
5.15.11
Python version
3.11.6
Compiled against GDAL/OGR
3.8.0
Running against GDAL/OGR
3.8.1
Compiled against PROJ
9.3.0
Running against PROJ
9.3.1
EPSG Registry database version
v10.098 (2023-11-24)
GEOS version
3.12.0-CAPI-1.18.0
SQLite version
3.44.2
PDAL version
2.6.1
PostgreSQL client version
16.1
SpatiaLite version
5.1.0
QWT version
6.2.0
QScintilla2 version
2.14.1
OS version
EndeavourOS

Active Python plugins
db_manager
0.1.20

### Supported QGIS version

- [x] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by ACalleros** [comment]
Also tried using a flatpak with the same error

**Comment by DelazJ** [comment]
> `Couldn't load plugin 'processing'

Out of curiosity, have you enabled the Processing plugin (in Plugins Manager)?

**Comment by agiudiceandrea** [comment]
It looks like a packaging issue for Arch Linux / EndevourOS: please https://gitlab.archlinux.org/archlinux/packaging/packages/qgis/-/issues/1

**Comment by dangarciahe** [comment]
I had this issue in my Manjaro install. The steps to fix it in my case was installing the [arrow](https://arrow.apache.org/) package and its dependencies. See https://github.com/OSGeo/gdal/issues/6281.

To verify it is fixed, try running `gdalinfo --version` on console:

`$ gdalinfo --version`
`GDAL 3.8.4, released 2024/02/08`

If you still see errors on the form `ERROR 1: libarrow.so.1500: cannot open shared object file: No such file or directory` then I can't help further, but that's your path to fixing the error and finding extra info on the internet (or at least it **greatly** helped me).

A final note is that QGIS works perfectly fine even if the output from `$ gdalinfo --version` is `ERROR 1: libpodofo.so.2: cannot open shared object file: No such file or directory`.

**Comment by ACalleros** [comment]
> I had this issue in my Manjaro install. The steps to fix it in my case was installing the [arrow](https://arrow.apache.org/) package and its dependencies. See [OSGeo/gdal#6281](https://github.com/OSGeo/gdal/issues/6281).
> 
> To verify it is fixed, try running `gdalinfo --version` on console:
> 
> `$ gdalinfo --version` `GDAL 3.8.4, released 2024/02/08`
> 
> If you still see errors on the form `ERROR 1: libarrow.so.1500: cannot open shared object file: No such file or directory` then I can't help further, but that's your path to fixing the error and finding extra info on the internet (or at least it **greatly** helped me).
> 
> A final note is that QGIS opens fine even if the output from `$ gdalinfo --version` is `ERROR 1: libpodofo.so.2: cannot open shared object file: No such file or directory`, but you'll see some features not working. To fix that error, I installed [podofo](https://github.com/podofo/podofo).

I tried installing the missing files, in my case mariadb and libheif, but I am still getting No module named gdal

**Comment by dangarciahe** [comment]
Sorry, I don't remember having that issue. Try checking [gdal](https://gdal.org/) in your repos. 

As a last resort work-around, you can try installing QGIS using Conda. The dependencies are handled in a different way in Conda, which solved some of the issues I had.
