### ISSUE TITLE
Layer reprojection not occuring during Export feature in QGIS 3.36.0

### ISSUE THREAD

**Issue by lgouzin** [qgis/QGIS#56826]
### What is the bug or the crash?

When Saving features from a vector layer in one CRS to another CRS, the new exported features do not get reprojected. This happened only in 3.36. This did not occuer in 3.34. 
Tested on a gpkg and shp. Tested with only selected feature, on same gpkg, on existing layername. The layer always get saved ignoring the different CRS inputed in the Save Feature dialog. 
In this case, the input CRS is 7844 and the wanted CRS output is 7855 or 7856.  

### Steps to reproduce the issue

1.load gpkg in 7844 (GDA2020, geographic CRS). Set project CRS to the same geographic CRS 7844. 
2.Right click on the layer in layer tree, Save features...
3. Choose another CRS, a projected CRS like 7855. 
4. Load the exported layer and check it's CRS

The project CRS has an influence. The reprojection does work if the selected CRS at Export is the same as the project's CRS. To reproduce the bug, make sure the selected CRS at Export is different than the project's CRS. 

### Versions

3.36.0

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by arnige** [comment]
I was about to report the same bug - happens to mee, too, and same description applies, with different CRSs.

**Comment by TKimber100** [comment]
I was also about to report this same bug. I am also experiencing the same issue. Reverted to 3.34 for the moment.

**Comment by lgouzin** [comment]
This issue seem to have been solved in QGIS 3.36.3

**Comment by jammels** [comment]
I am still getting what i think is essentially the same error on version 3.42.1 (I originally encountered it on 3.34.14 but upgraded and found the same issue). 

I am working on exporting sections of layers from a restAPI server as DXF. If i export a layer as GDA2020 (EPSG:7855) and another as GDA94 (ESPG:28355) the output files are identical (both are GDA94). 

Same result if i export a single point to a CSV files using the AS_YX geometry.
