### ISSUE TITLE
Python Erros or Start-up Mac OS

### ISSUE THREAD

**Issue by AndrewLindsay** [qgis/QGIS#59321]
### What is the bug or the crash?

QGIS Startup Errors

Couldn't create run_startup_script.

Traceback (most recent call last):
  File "", line 2, in 
  File "QgsPythonUtilsImpl::checkSystemImports [run_startup_script]", line 2, in 
  File "QgsPythonUtilsImpl::checkSystemImports [run_startup_script]", line 7, in StartupScriptRunner
TypeError: unsupported operand type(s) for |: 'type' and 'type'

Python version: 3.9.5 (default, Sep 10 2021, 16:18:19)  [Clang 12.0.5 (clang-1205.0.22.11)]  QGIS version: 3.40.0-Bratislava 'Bratislava', 1d561ad8ad9  Python path: ['/Applications/QGIS.app/Contents/MacOS/lib/python39.zip', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/lib-dynload', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/pyproj-3.2.0-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numpy-1.20.1-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/Rtree-0.9.7-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/cftime-1.2.1-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/GDAL-3.3.2-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/pandas-1.3.3-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/patsy-0.5.1-py3.9.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/Pillow-7.2.0-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/Fiona-1.8.13.post1-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/matplotlib-3.3.0-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/netCDF4-1.5.4-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/rasterio-1.1.5-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/scipy-1.5.1-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/opencv_contrib_python-4.3.0.36-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/statsmodels-0.11.1-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/geopandas-0.8.1-py3.9.egg']

An error occurred during execution of following code: is_startup_script_executed = _ssr.run_startup_script(pyqgstart)

Traceback (most recent call last):
  File "", line 1, in 
NameError: name '_ssr' is not defined

Python version: 3.9.5 (default, Sep 10 2021, 16:18:19)  [Clang 12.0.5 (clang-1205.0.22.11)]  QGIS version: 3.40.0-Bratislava 'Bratislava', 1d561ad8ad9  Python path: ['/Applications/QGIS.app/Contents/MacOS/lib/python39.zip', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/lib-dynload', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/pyproj-3.2.0-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numpy-1.20.1-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/Rtree-0.9.7-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/cftime-1.2.1-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/GDAL-3.3.2-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/pandas-1.3.3-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/patsy-0.5.1-py3.9.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/Pillow-7.2.0-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/Fiona-1.8.13.post1-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/matplotlib-3.3.0-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/netCDF4-1.5.4-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/rasterio-1.1.5-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/scipy-1.5.1-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/opencv_contrib_python-4.3.0.36-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/statsmodels-0.11.1-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/geopandas-0.8.1-py3.9.egg']

An error occurred during execution of following code: _ssr.log_messages()

Traceback (most recent call last):
  File "", line 1, in 
NameError: name '_ssr' is not defined

Python version: 3.9.5 (default, Sep 10 2021, 16:18:19)  [Clang 12.0.5 (clang-1205.0.22.11)]  QGIS version: 3.40.0-Bratislava 'Bratislava', 1d561ad8ad9  Python path: ['/Applications/QGIS.app/Contents/MacOS/../Resources/python', '/Users/andrewlindsay/Library/Application Support/QGIS/QGIS3/profiles/default/python', '/Users/andrewlindsay/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins', '/Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins', '/Applications/QGIS.app/Contents/MacOS/lib/python39.zip', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/lib-dynload', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/pyproj-3.2.0-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numpy-1.20.1-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/Rtree-0.9.7-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/cftime-1.2.1-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/GDAL-3.3.2-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/pandas-1.3.3-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/patsy-0.5.1-py3.9.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/Pillow-7.2.0-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/Fiona-1.8.13.post1-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/matplotlib-3.3.0-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/netCDF4-1.5.4-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/rasterio-1.1.5-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/scipy-1.5.1-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/opencv_contrib_python-4.3.0.36-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/statsmodels-0.11.1-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/geopandas-0.8.1-py3.9.egg']

### Steps to reproduce the issue

Start Application - All errors during start-up of app.

### Versions

<table width='100%' align='center'><tr><td>QGIS version</td><td>3.40.0-Bratislava</td></tr><tr><td>QGIS code revision</td><td><a href="https://github.com/qgis/QGIS/commit/1d561ad8ad9">1d561ad8ad9</a></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Libraries</b></td></tr><tr><td>Qt version</td><td>5.15.2</td></tr><tr><td>Python version</td><td>3.9.5</td></tr><tr><td>GDAL/OGR version</td><td>3.3.2</td></tr><tr><td>PROJ version</td><td>8.1.1</td></tr><tr><td>EPSG Registry database version</td><td>v10.028 (2021-07-07)</td></tr><tr><td>GEOS version</td><td>3.9.1-CAPI-1.14.2</td></tr><tr><td>SQLite version</td><td>3.35.2</td></tr><tr><td>PDAL version</td><td>2.3.0</td></tr><tr><td>PostgreSQL client version</td><td>unknown</td></tr><tr><td>SpatiaLite version</td><td>5.0.1</td></td></tr><tr><td>QWT version</td><td>6.1.6</td></tr><tr><td>QScintilla2 version</td><td>2.11.5</td></tr><tr><td>OS version</td><td>macOS 15.0</td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Active Python plugins</b></td></tr><tr><td>FreehandRasterGeoreferencer</td><td>0.8.3</td></tr><tr><td>SpreadsheetLayers</td><td>2.1.2</td></tr><tr><td>profiletool</td><td>4.2.6</td></tr><tr><td>quick_map_services</td><td>0.19.34</td></tr><tr><td>Multi_Ring_Buffer</td><td>1.1</td></tr><tr><td>HCMGIS</td><td>24.10.20</td></tr><tr><td>latlontools</td><td>3.7.2</td></tr><tr><td>xyz_3d</td><td>0.1</td></tr><tr><td>ProjectSetup</td><td>0.8</td></tr><tr><td>valuetool</td><td>3.0.19</td></tr><tr><td>ProjectPackager</td><td>0.7.4</td></tr><tr><td>processing</td><td>2.12.99</td></tr><tr><td>grassprovider</td><td>2.12.99</td></tr><tr><td>db_manager</td><td>0.1.20</td></tr><tr><td>MetaSearch</td><td>0.3.6</td></tr></table>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by TroyPudney** [comment]
Same issue and error, MacOS 15.1 Mac mini M2 Pro

**Comment by sfc-gh-obielov** [comment]
Same issue:
QGIS version | 3.40.0-Bratislava
QGIS code revision | 1d561ad8ad9
 
Libraries
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.2
PROJ version | 8.1.1
EPSG Registry database version | v10.028 (2021-07-07)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.11.5
OS version | macOS 14.7
 
Active Python plugins
qgis-snowflake-connector | 0.8.2
processing | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.6

**Comment by corrosive4354** [comment]
The QGIS version you are currently using is 3.40.0. Check if there is a newer version of QGIS available. The newer version may fix known bugs.

In addition, seeing that you are using homebrew, I would like to recommend [Servbay](servbay.com) to you, which is more professional and easier to use on Mac than Docker and homebrew.

**Comment by sfc-gh-obielov** [comment]
@corrosive4354 3.40.0 is the latest available version for Mac: https://qgis.org/download/

**Comment by ThomasR128** [comment]
Same issue here.

M1 Max MacBook Air:
QGIS version | 3.40.0-Bratislava

Unable to post more information on libraries and plugins because, well, Qgis would have to start for me to obtain it …

**Comment by JuanBreva** [comment]
I'm having exactly the same issue.

QGIS version: 3.40.0-Bratislava.

Running on Mac OS Monterey.

**Comment by belceli** [comment]
I'm having exactly the same issue.

QGIS version: 3.40.0-Bratislava.

Running on MacOS Monterey.

**Comment by abuabara** [comment]
Me too. Tried to reinstall the version posted yesterday (https://download.qgis.org/downloads/macos/pr/qgis_pr_final-3_40_0_20241102_172144.dmg 2024-11-03 00:46) but still problematic.

**Comment by pbfi** [comment]
This is happening for me.  I get 3 errors in a row.  

Couldn't create run_startup_script.
An error occurred during execution of following code: is_start_up_sxriupt_executed = _ssr.run_startup_script (pywgstart)
An error occurred during excecution of following code:_ssr.log_messages()

After clicking through these my map project loads up ok.  I've not done too much else yet to know if there are other down stream effects of the errors. 

QGIS version: 3.40.0-Bratislava.

MacBook Pro
2.3 GHz Quad-Core Intel Core i7
Sequoia 15.1

**Comment by agiudiceandrea** [comment]
@AndrewLindsay, thanks for reporting. Does the issue prevent QGIS to start and run? What is the last QGIS version that the issue didn't occur with?

**Comment by kommen** [comment]
This error is related to this recent change: https://github.com/qgis/QGIS/commit/02236e6b9966cda997c9b71f6deb63234989c0a4

**Comment by AndrewLindsay** [comment]
> @AndrewLindsay, thanks for reporting. Does the issue completely prevent QGIS to start and run? What is the last QGIS version that the issue didn't occur with?

It does not stop start-up, and I have not seen any issues once running.

**Comment by ostr00000** [comment]
It seems there is syntax error in this expression:
```python
def run_startup_script(self, script_path: pathlib.Path | str | None) -> bool:
    ...
```
This error only appears when python<=3.9 is used (union for types was introduced in python==3.10 in https://peps.python.org/pep-0604/ )

It should be easy to fix. I am going to create PR later today.

**Comment by ThomasR128** [comment]
There are easy fixes, and there are good fixes.

Python 3.9 is more than three years old. People, including those working on QGIS, will since have been accustomed to newer versions (3.13 is current) – and no-one will remember what was not yet supported in 2021. IMHO, the good fix would be to use an up-to-date Python version.

**Comment by agiudiceandrea** [comment]
@ThomasR128, on macOS you can use QGIS also e.g. either from [MacPorts](https://www.qgis.org/resources/installation-guide/#macports) or form [conda-forge](https://aneto.pt/posts/tutorials/2019-05-29-using-qgis-from-conda/) which use more recent version of Python.

**Comment by ThomasR128** [comment]
@agiudiceandrea Yes, I certainly could, although I use Homebrew and I’m not sure if Homebrew and Mac-ports can co-exist. But that’s beside the point. 

If MacPorts/conda-forge use newer versions of Python, and if @ostr00000 is right, this would just mean that the error does not manifest there. It is still there.

Your suggestion doesn’t stop QGIS delevoppers using functionality that was introduced after 3.9 because no-one can be expected to remember the Python revision history. And if MacPorts/conda-forge are able to bundle newer Python versions, why isn’t the official release?

**Comment by sfc-gh-obielov** [comment]
@ThomasR128 While many GIS experts are very familiar with GIS tools, they might have limited experience with SQL and Python. They may only have a MacBook Pro with the default version of Python, on which they install QGIS, and updating Python could be a barrier.

**Comment by palikao** [comment]
Same here, macOS 14.7.1 on M1 pro

**Comment by KristofBostoen** [comment]
Similar problem on Mac OS 14.4 (23E214) M2 Home-Brew Install using Rosetta 2.
Received 3 errors at startup which seem all Python related., but got to the start-up screen. Not sure what is affected.
Installed QGIS for in preparation for a course.
Looked online for a solution which got me here.
Thanks in advance for any help.
Kindly
Kristof

**Couldn't create run_startup_script.**
Traceback (most recent call last):
  File "", line 2, in 
  File "QgsPythonUtilsImpl::checkSystemImports [run_startup_script]", line 2, in 
  File "QgsPythonUtilsImpl::checkSystemImports [run_startup_script]", line 7, in StartupScriptRunner
TypeError: unsupported operand type(s) for |: 'type' and 'type'


Python version:
3.9.5 (default, Sep 10 2021, 16:18:19) 
[Clang 12.0.5 (clang-1205.0.22.11)]

QGIS version:
3.40.0-Bratislava 'Bratislava', 1d561ad8ad9

Python path:
['/Applications/QGIS.app/Contents/MacOS/lib/python39.zip', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/lib-dynload', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/pyproj-3.2.0-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numpy-1.20.1-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/Rtree-0.9.7-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/cftime-1.2.1-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/GDAL-3.3.2-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/pandas-1.3.3-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/patsy-0.5.1-py3.9.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/Pillow-7.2.0-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/Fiona-1.8.13.post1-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/matplotlib-3.3.0-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/netCDF4-1.5.4-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/rasterio-1.1.5-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/scipy-1.5.1-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/opencv_contrib_python-4.3.0.36-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/statsmodels-0.11.1-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/geopandas-0.8.1-py3.9.egg']

**An error occurred during execution of following code:
is_startup_script_executed = _ssr.run_startup_script(pyqgstart)**


Traceback (most recent call last):
  File "", line 1, in 
NameError: name '_ssr' is not defined


Python version:
3.9.5 (default, Sep 10 2021, 16:18:19) 
[Clang 12.0.5 (clang-1205.0.22.11)]

QGIS version:
3.40.0-Bratislava 'Bratislava', 1d561ad8ad9

Python path:
['/Applications/QGIS.app/Contents/MacOS/lib/python39.zip', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/lib-dynload', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/pyproj-3.2.0-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numpy-1.20.1-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/Rtree-0.9.7-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/cftime-1.2.1-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/GDAL-3.3.2-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/pandas-1.3.3-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/patsy-0.5.1-py3.9.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/Pillow-7.2.0-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/Fiona-1.8.13.post1-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/matplotlib-3.3.0-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/netCDF4-1.5.4-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/rasterio-1.1.5-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/scipy-1.5.1-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/opencv_contrib_python-4.3.0.36-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/statsmodels-0.11.1-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/geopandas-0.8.1-py3.9.egg']

**An error occurred during execution of following code:
_ssr.log_messages()**


Traceback (most recent call last):
  File "", line 1, in 
NameError: name '_ssr' is not defined


Python version:
3.9.5 (default, Sep 10 2021, 16:18:19) 
[Clang 12.0.5 (clang-1205.0.22.11)]

QGIS version:
3.40.0-Bratislava 'Bratislava', 1d561ad8ad9

Python path:
['/Applications/QGIS.app/Contents/MacOS/../Resources/python', '/Users/kb/Library/Application Support/QGIS/QGIS3/profiles/default/python', '/Users/kb/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins', '/Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins', '/Applications/QGIS.app/Contents/MacOS/lib/python39.zip', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/lib-dynload', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/pyproj-3.2.0-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numpy-1.20.1-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/Rtree-0.9.7-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/cftime-1.2.1-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/GDAL-3.3.2-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/pandas-1.3.3-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/patsy-0.5.1-py3.9.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/Pillow-7.2.0-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/Fiona-1.8.13.post1-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/matplotlib-3.3.0-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/netCDF4-1.5.4-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/rasterio-1.1.5-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/scipy-1.5.1-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/opencv_contrib_python-4.3.0.36-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/statsmodels-0.11.1-py3.9-macosx-10.13.0-x86_64.egg', '/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/geopandas-0.8.1-py3.9.egg']

**Comment by agiudiceandrea** [comment]
@KristofBostoen, the issue has been already fixed. The fix will be available in QGIS >= 3.34.1.

**Comment by Jachimo** [comment]
I am still getting the three errors on startup, using QGIS 3.40.0-Bratislava (1d561ad8ad9).

On the About page, QGIS reports that it is using Python 3.9.5.  I presume (??) this is the version that's embedded inside QGIS.app, but I'm not entirely sure.

**Comment by agiudiceandrea** [comment]
@jachimo, have you read the previous comments? The issue will be fixed in QGIS 3.34.1 and later versions.

**Comment by agiudiceandrea** [comment]
@Jachimo , the issue occurs only using QGIS 3.40.0 and will be fixed in QGIS 3.40.1 and later versions.

**Comment by kasra-keshavarz** [comment]
Is there a link to the older version for Mac that can be downloaded while the new version is being prepared? I tried to search for one but couldn't find any.

**Comment by drf5n** [comment]
> Is there a link to the older version for Mac (3.38.3?) that can be downloaded while the new version is being prepared? I tried to search for one but couldn't find any.

https://download.qgis.org/downloads/macos/pr/

https://download.qgis.org/downloads/macos/pr/qgis_pr_final-3_38_3_20240913_122840.dmg

And you can see the intervals between publishing releases.

**Comment by sabinz** [comment]
I've had these problems for a while. I cannot change the Python version in QGIS no matter what I try. It seems to be bundled with 3.9, but everyone says the syntax that it relies upon needs 3.10+... Hopefully this can be fixed.

**Comment by drf5n** [comment]
The 3.40.2-Bratislava does indeed boot without the error messages.  It is still using Python 3.9.5:

<table width='100%' align='center'><tr><td>QGIS version</td><td>3.40.2-Bratislava</td></tr><tr><td>QGIS code revision</td><td><a href="https://github.com/qgis/QGIS/commit/14826ca1e4a">14826ca1e4a</a></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Libraries</b></td></tr><tr><td>Qt version</td><td>5.15.2</td></tr><tr><td>Python version</td><td>3.9.5</td></tr><tr><td>GDAL/OGR version</td><td>3.3.2</td></tr><tr><td>PROJ version</td><td>8.1.1</td></tr><tr><td>EPSG Registry database version</td><td>v10.028 (2021-07-07)</td></tr><tr><td>GEOS version</td><td>3.9.1-CAPI-1.14.2</td></tr><tr><td>SQLite version</td><td>3.35.2</td></tr><tr><td>PDAL version</td><td>2.3.0</td></tr><tr><td>PostgreSQL client version</td><td>unknown</td></tr><tr><td>SpatiaLite version</td><td>5.0.1</td></td></tr><tr><td>QWT version</td><td>6.1.6</td></tr><tr><td>QScintilla2 version</td><td>2.11.5</td></tr><tr><td>OS version</td><td>macOS 14.5</td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Active Python plugins</b></td></tr><tr><td>FreehandRasterGeoreferencer</td><td>0.8.3</td></tr><tr><td>quick_map_services</td><td>0.19.37</td></tr><tr><td>MagneticDeclination</td><td>2.4.4</td></tr><tr><td>DEMto3D</td><td>3.51</td></tr><tr><td>LAStools</td><td>2.1.1</td></tr><tr><td>GeoCoding</td><td>2.19</td></tr><tr><td>latlontools</td><td>3.7.2</td></tr><tr><td>timezone_expressions</td><td>v0.2</td></tr><tr><td>crayfish</td><td>3.6.0</td></tr><tr><td>processing</td><td>2.12.99</td></tr><tr><td>grassprovider</td><td>2.12.99</td></tr><tr><td>db_manager</td><td>0.1.20</td></tr><tr><td>MetaSearch</td><td>0.3.6</td></tr></table>
