### ISSUE TITLE
STAC browser - relative urls not supported: Protocol "" is uknown

### ISSUE THREAD

**Issue by ttomasz** [qgis/QGIS#59406]
### What is the bug or the crash?

When STAC catalog has relative URLs to its children then the browser throws error Protocol "" is unknown.

I also see in debugging tools (F12) that it tries to make request to the URL exactly as it's presented i.e. without trying to resolve the relative URL based on URL from connection.

### Steps to reproduce the issue

1. Add connection to STAC catalog that has relative URLs e.g.: `https://pub-a8cc9feb8bdc4fdf9cbf37078dc21b8e.r2.dev/catalog.json`.
2. Try to open the collection by clicking the little arrow

### Versions

<table width='100%' align='center'><tr><td>QGIS version</td><td>3.40.0-Bratislava</td></tr><tr><td>QGIS code branch</td><td><a href="https://github.com/qgis/QGIS/tree/release-3_40">Release 3.40</a></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Libraries</b></td></tr><tr><td>Qt version</td><td>5.15.10</td></tr><tr><td>Python version</td><td>3.11.9</td></tr><tr><td>GDAL/OGR version</td><td>3.10.0</td></tr><tr><td>PROJ version</td><td>9.5.0</td></tr><tr><td>EPSG Registry database version</td><td>v11.016 (2024-08-31)</td></tr><tr><td>GEOS version</td><td>3.13.0-CAPI-1.19.0</td></tr><tr><td>SQLite version</td><td>3.47.0</td></tr><tr><td>PDAL version</td><td>2.8.1</td></tr><tr><td>PostgreSQL client version</td><td>unknown</td></tr><tr><td>SpatiaLite version</td><td>5.1.0</td></td></tr><tr><td>QWT version</td><td>6.1.5</td></tr><tr><td>QScintilla2 version</td><td>2.14.1</td></tr><tr><td>OS version</td><td>KDE Flatpak runtime</td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Active Python plugins</b></td></tr><tr><td>QuickOSM</td><td>2.2.3</td></tr><tr><td>cartogram3</td><td>3.1.5</td></tr><tr><td>felt</td><td>3.1.5</td></tr><tr><td>qgis_stac</td><td>1.1.2</td></tr><tr><td>AnotherDXF2Shape</td><td>1.3.2</td></tr><tr><td>GTFS_Loader</td><td>1.0.0</td></tr><tr><td>zoom_level</td><td>0.3.1</td></tr><tr><td>qgis-maptiler-plugin</td><td>3.3.2</td></tr><tr><td>AnimateOsm</td><td>0.3.0</td></tr><tr><td>processing</td><td>2.12.99</td></tr><tr><td>db_manager</td><td>0.1.20</td></tr><tr><td>grassprovider</td><td>2.12.99</td></tr><tr><td>MetaSearch</td><td>0.3.6</td></tr></table>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

Relative URLs may not be recommended but they are allowed according to the specification and work in STAC Web Browser: https://radiantearth.github.io/stac-browser/#/external/pub-a8cc9feb8bdc4fdf9cbf37078dc21b8e.r2.dev/catalog.json

**Comment by wonder-sk** [comment]
Can you try with the nightly builds please? It should be already fixed by https://github.com/qgis/QGIS/pull/59199

**Comment by uclaros** [comment]
Automatic backporting to 3.40 failed though, I'll do a manual back port

**Comment by dwsilk** [comment]
@uclaros I am on QGIS 3.40.2 released late December and this is still an issue, was the manual backport to 3.40 not completed?

**Comment by uclaros** [comment]
> [@uclaros](https://github.com/uclaros) I am on QGIS 3.40.2 released late December and this is still an issue, was the manual backport to 3.40 not completed?

Unfortunately I neglected to do the backport on time. Here's the PR for a backport to 3.40.4 hopefully :) #60469
