### ISSUE TITLE
New Connections to OGC Services Hang in Profiles with PostGIS Connections

### ISSUE THREAD

**Issue by pigreco** [qgis/QGIS#60335]
### What is the bug or the crash?

Every time I create a new connection or modify it to an OGC service (for example WMS, WFS) QGIS hangs, the message (Not responding) appears and I have to force close.
This problem is present if I have connections to PostGIS in the user profile, **_in clean profiles (i.e. without connections to PostGIS) the problem does not occur_**.

![Image](https://github.com/user-attachments/assets/ce93e06a-ab79-4b85-a424-67381f68078a)

### Steps to reproduce the issue

1. open QGIS
2. create a connection to PostGIS
3. restart QGIS
4. create a new connection to an OGC service
5. QGIS hangs after OK

### Versions

<table width='100%' align='center'><tr><td>Versione di QGIS</td><td>3.40.3-Bratislava</td></tr><tr><td>Revisione codice QGIS</td><td><a href="https://github.com/qgis/QGIS/commit/2a274ab7">2a274ab7</a></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Librerie</b></td></tr><tr><td>Versione Qt</td><td>5.15.13</td></tr><tr><td>Versione Python</td><td>3.12.8</td></tr><tr><td>Versione GDAL/OGR</td><td>3.10.1</td></tr><tr><td>Versione PROJ</td><td>9.5.1</td></tr><tr><td>Versione database del Registro EPSG</td><td>v11.022 (2024-11-05)</td></tr><tr><td>Versione GEOS</td><td>3.13.0-CAPI-1.19.0</td></tr><tr><td>Versione SQLite</td><td>3.46.1</td></tr><tr><td>Versione PDAL</td><td>2.8.3</td></tr><tr><td>Versione client PostgreSQL</td><td>unknown</td></tr><tr><td>Versione SpatiaLite</td><td>5.1.0</td></td></tr><tr><td>Versione QWT</td><td>6.3.0</td></tr><tr><td>Versione QScintilla2</td><td>2.14.1</td></tr><tr><td>Versione SO</td><td>Windows 11 Version 2009</td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Plugins Python attivi</b></td></tr><tr><td>DataPlotly</td><td>4.2.0</td></tr><tr><td>filtra_selecionados</td><td>1.2</td></tr><tr><td>gensimplot</td><td>2.1</td></tr><tr><td>gimpselectionfeature_plugin</td><td>1.6</td></tr><tr><td>GroupStats</td><td>2.2.7</td></tr><tr><td>latlontools</td><td>3.7.2</td></tr><tr><td>nominatim_locator_filter</td><td>0.3.2</td></tr><tr><td>pointsamplingtool</td><td>0.5.4</td></tr><tr><td>profile-manager</td><td>0.31</td></tr><tr><td>qconsolidate</td><td>1.1.0</td></tr><tr><td>qduckdb</td><td>1.2.1</td></tr><tr><td>qgis_plugin_gpq_downloader</td><td>0.3.4</td></tr><tr><td>QuickOSM</td><td>2.3.2</td></tr><tr><td>quick_map_services</td><td>0.19.37</td></tr><tr><td>Split-Lines-By-Points-main</td><td>1.0</td></tr><tr><td>ViewshedAnalysis</td><td>1.9.1</td></tr><tr><td>db_manager</td><td>0.1.20</td></tr><tr><td>MetaSearch</td><td>0.3.6</td></tr><tr><td>processing</td><td>2.12.99</td></tr></table>

### Supported QGIS version

- [x] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [x] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

tested on QGIS 3.34.15, QGIS 3.40.3 and master
on old and new user profiles

**Comment by elpaso** [comment]
It smells like https://github.com/qgis/QGIS/issues/60018 , can you check if this is already solved in the nightly build?

**Comment by pigreco** [comment]
@elpaso 
> can you check if this is already solved in the nightly build?

I just updated the master: see animated gif

unfortunately it still crashes

![Image](https://github.com/user-attachments/assets/51edbe6e-a1d3-49cf-80f2-e2a19ed324a3)

**Comment by elpaso** [comment]
I cannot reproduce on linux / master.

**Comment by pigreco** [comment]
> I cannot reproduce on linux / master.

Unfortunately I use Windows machines :-)

**Comment by pigreco** [comment]
@elpaso @agiudiceandrea 

Hi Alessandro, I recorded a demo video ((IT):
1. with test on QGIS 3.34.15
2. with test on master 3.41

the problem occurs when I start a new session on a profile in which there are connections to PostgreSQL, if I insert the credentials to the postgresql connections the problem does not occur.

https://youtu.be/uVzs-_eOR-M

**Comment by agiudiceandrea** [comment]
@elpaso, I can also replicate the issue on Windows 10 (OSGeo4W). It seems to me the issue occurs when a PostgreSQL connection has the option "Allow saving/loading QGIS layer metadata in the database" active.

To replicate the issue:
1. use the Browser to add a new PostgreSQL connection:
   - enter the connection info, check the "Allow saving/loading QGIS layer metadata in the database" checkbox
   - press OK
   - press Cancel to the popped up "Enter Credentials" dialog window
2. open the Data Source Manager
3. add a WMS connection -> QGIS hangs indefinitely

The following are the debugging messages since when the WMS connection is added and until QGIS hangs.
It looks like the Data Source Manager refreshes all the connections (the PostgreSQL one included, although I was adding a WMS connection) and then tries to open the Enter Credential dialog window (see the last line: `QgsCredentialDialog::request) [0ms] [thread:0x2001a3c6370] emitting signal`) but the dialog window doesn't actually open so QGIS gets stuck probably waiting for the dialog windows to return something...


```
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\gui\qgsbrowserwidget.cpp(300) : (QgsBrowserWidget::refreshModel) [16439ms] invalid item
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(280) : (QgsDataItem::depopulate) [0ms] mPath = home:C:/Users/Andrea
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(557) : (QgsDataItem::setState) [0ms] item home:C:/Users/Andrea set state NotPopulated -> NotPopulated
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\gui\qgsbrowserwidget.cpp(296) : (QgsBrowserWidget::refreshModel) [0ms] path = favorites:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsbrowsermodel.cpp(755) : (QgsBrowserModel::refresh) [0ms] Refresh favorites:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(297) : (QgsDataItem::refresh) [0ms] mPath = favorites:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(332) : (QgsDataItem::refresh) [1ms] mPath = favorites:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(557) : (QgsDataItem::setState) [0ms] item favorites: set state Populated -> Populated
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(280) : (QgsDataItem::depopulate) [0ms] mPath = C:/
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(557) : (QgsDataItem::setState) [0ms] item C:/ set state NotPopulated -> NotPopulated
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\gui\qgsbrowserwidget.cpp(296) : (QgsBrowserWidget::refreshModel) [0ms] path = gpkg:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsbrowsermodel.cpp(755) : (QgsBrowserModel::refresh) [0ms] Refresh gpkg:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(297) : (QgsDataItem::refresh) [0ms] mPath = gpkg:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(332) : (QgsDataItem::refresh) [0ms] mPath = gpkg:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(557) : (QgsDataItem::setState) [0ms] item gpkg: set state Populated -> Populated
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(280) : (QgsDataItem::depopulate) [0ms] mPath = mssql:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(557) : (QgsDataItem::setState) [0ms] item mssql: set state Populated -> NotPopulated
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsbrowsermodel.cpp(632) : (QgsBrowserModel::itemStateChanged) [0ms] item mssql: state changed Populated -> NotPopulated
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(280) : (QgsDataItem::depopulate) [0ms] mPath = oracle:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(557) : (QgsDataItem::setState) [0ms] item oracle: set state Populated -> NotPopulated
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsbrowsermodel.cpp(632) : (QgsBrowserModel::itemStateChanged) [0ms] item oracle: state changed Populated -> NotPopulated
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\gui\qgsbrowserwidget.cpp(296) : (QgsBrowserWidget::refreshModel) [0ms] path = pg:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsbrowsermodel.cpp(755) : (QgsBrowserModel::refresh) [0ms] Refresh pg:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(297) : (QgsDataItem::refresh) [0ms] mPath = pg:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(332) : (QgsDataItem::refresh) [0ms] mPath = pg:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(492) : (QgsDataItem::findItem) [0ms] 0 : pg:/testpostgres x pg:/testpostgres
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(492) : (QgsDataItem::findItem) [0ms] 0 : pg:/testpostgres x pg:/testpostgres
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(109) : (QgsDataItem::deleteLater) [0ms] path = pg:/testpostgres
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(557) : (QgsDataItem::setState) [0ms] item pg: set state Populated -> Populated
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(280) : (QgsDataItem::depopulate) [0ms] mPath = pg:/testpostgres
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(557) : (QgsDataItem::setState) [0ms] item pg:/testpostgres set state NotPopulated -> NotPopulated
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\gui\qgsbrowserwidget.cpp(296) : (QgsBrowserWidget::refreshModel) [0ms] path = hana:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsbrowsermodel.cpp(755) : (QgsBrowserModel::refresh) [0ms] Refresh hana:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(297) : (QgsDataItem::refresh) [0ms] mPath = hana:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(332) : (QgsDataItem::refresh) [0ms] mPath = hana:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(557) : (QgsDataItem::setState) [0ms] item hana: set state Populated -> Populated
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\gui\qgsbrowserwidget.cpp(296) : (QgsBrowserWidget::refreshModel) [0ms] path = bookmarks:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\gui\qgsbrowserwidget.cpp(296) : (QgsBrowserWidget::refreshModel) [0ms] path = bookmarks:project bookmarks
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\gui\qgsbrowserwidget.cpp(296) : (QgsBrowserWidget::refreshModel) [0ms] path = bookmarks:user bookmarks
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\gui\qgsbrowserwidget.cpp(296) : (QgsBrowserWidget::refreshModel) [0ms] path = spatialite:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsbrowsermodel.cpp(755) : (QgsBrowserModel::refresh) [0ms] Refresh spatialite:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(297) : (QgsDataItem::refresh) [0ms] mPath = spatialite:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(332) : (QgsDataItem::refresh) [0ms] mPath = spatialite:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(557) : (QgsDataItem::setState) [0ms] item spatialite: set state Populated -> Populated
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\gui\qgsbrowserwidget.cpp(296) : (QgsBrowserWidget::refreshModel) [0ms] path = arcgisfeatureserver:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsbrowsermodel.cpp(755) : (QgsBrowserModel::refresh) [0ms] Refresh arcgisfeatureserver:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(297) : (QgsDataItem::refresh) [0ms] mPath = arcgisfeatureserver:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(332) : (QgsDataItem::refresh) [0ms] mPath = arcgisfeatureserver:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(557) : (QgsDataItem::setState) [0ms] item arcgisfeatureserver: set state Populated -> Populated
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\gui\qgsbrowserwidget.cpp(296) : (QgsBrowserWidget::refreshModel) [0ms] path = cloud:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsbrowsermodel.cpp(755) : (QgsBrowserModel::refresh) [0ms] Refresh cloud:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(297) : (QgsDataItem::refresh) [0ms] mPath = cloud:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(332) : (QgsDataItem::refresh) [0ms] mPath = cloud:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(557) : (QgsDataItem::setState) [0ms] item cloud: set state Populated -> Populated
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\gui\qgsbrowserwidget.cpp(296) : (QgsBrowserWidget::refreshModel) [0ms] path = tiled-scene:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsbrowsermodel.cpp(755) : (QgsBrowserModel::refresh) [0ms] Refresh tiled-scene:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(297) : (QgsDataItem::refresh) [0ms] mPath = tiled-scene:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(332) : (QgsDataItem::refresh) [0ms] mPath = tiled-scene:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(557) : (QgsDataItem::setState) [0ms] item tiled-scene: set state Populated -> Populated
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\gui\qgsbrowserwidget.cpp(296) : (QgsBrowserWidget::refreshModel) [0ms] path = sensorthings:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsbrowsermodel.cpp(755) : (QgsBrowserModel::refresh) [0ms] Refresh sensorthings:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(297) : (QgsDataItem::refresh) [0ms] mPath = sensorthings:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(332) : (QgsDataItem::refresh) [0ms] mPath = sensorthings:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(557) : (QgsDataItem::setState) [0ms] item sensorthings: set state Populated -> Populated
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\gui\qgsbrowserwidget.cpp(296) : (QgsBrowserWidget::refreshModel) [0ms] path = stac:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsbrowsermodel.cpp(755) : (QgsBrowserModel::refresh) [0ms] Refresh stac:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(297) : (QgsDataItem::refresh) [0ms] mPath = stac:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(332) : (QgsDataItem::refresh) [0ms] mPath = stac:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(557) : (QgsDataItem::setState) [0ms] item stac: set state Populated -> Populated
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\gui\qgsbrowserwidget.cpp(296) : (QgsBrowserWidget::refreshModel) [0ms] path = vectortile:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsbrowsermodel.cpp(755) : (QgsBrowserModel::refresh) [0ms] Refresh vectortile:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(297) : (QgsDataItem::refresh) [0ms] mPath = vectortile:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(332) : (QgsDataItem::refresh) [0ms] mPath = vectortile:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(557) : (QgsDataItem::setState) [0ms] item vectortile: set state Populated -> Populated
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\gui\qgsbrowserwidget.cpp(296) : (QgsBrowserWidget::refreshModel) [0ms] path = wcs:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsbrowsermodel.cpp(755) : (QgsBrowserModel::refresh) [0ms] Refresh wcs:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(297) : (QgsDataItem::refresh) [0ms] mPath = wcs:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(332) : (QgsDataItem::refresh) [0ms] mPath = wcs:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(557) : (QgsDataItem::setState) [0ms] item wcs: set state Populated -> Populated
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\gui\qgsbrowserwidget.cpp(296) : (QgsBrowserWidget::refreshModel) [0ms] path = wfs:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsbrowsermodel.cpp(755) : (QgsBrowserModel::refresh) [0ms] Refresh wfs:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(297) : (QgsDataItem::refresh) [0ms] mPath = wfs:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(332) : (QgsDataItem::refresh) [0ms] mPath = wfs:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(557) : (QgsDataItem::setState) [0ms] item wfs: set state Populated -> Populated
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\gui\qgsbrowserwidget.cpp(296) : (QgsBrowserWidget::refreshModel) [0ms] path = wms:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsbrowsermodel.cpp(755) : (QgsBrowserModel::refresh) [0ms] Refresh wms:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(297) : (QgsDataItem::refresh) [0ms] mPath = wms:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\qgsowsconnection.cpp(84) : (QgsOwsConnection::QgsOwsConnection) [0ms] theConnName = IGM_25000
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\qgsowsconnection.cpp(125) : (QgsOwsConnection::QgsOwsConnection) [11ms] encoded uri: 'dpiMode=7&featureCount=10&tilePixelRatio=0&url=http://wms.pcn.minambiente.it/ogc?map%3D/ms_ogc/WMS_v1.3/raster/IGM_25000.map'.
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(332) : (QgsDataItem::refresh) [0ms] mPath = wms:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(426) : (QgsDataItem::addChildItem) [0ms] path = wms: add child #0 - IGM_25000 - Collection
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsbrowsermodel.cpp(591) : (QgsBrowserModel::beginInsertItems) [0ms] parent mPath = wms:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsbrowsermodel.cpp(595) : (QgsBrowserModel::beginInsertItems) [0ms] valid
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsbrowsermodel.cpp(597) : (QgsBrowserModel::beginInsertItems) [0ms] end
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsbrowsermodel.cpp(601) : (QgsBrowserModel::endInsertItems) [0ms] Entered
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\gui\qgsbrowsertreeview.cpp(337) : (QgsBrowserTreeView::rowsInserted) [0ms] mExpandPaths = favorites:,wms:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\gui\qgsbrowsertreeview.cpp(340) : (QgsBrowserTreeView::rowsInserted) [0ms] parentPath = wms:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\gui\qgsbrowsertreeview.cpp(363) : (QgsBrowserTreeView::rowsInserted) [0ms] childPath = wms:/IGM_25000 escapedChildPath = wms\:\/IGM_25000
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(557) : (QgsDataItem::setState) [0ms] item wms: set state Populated -> Populated
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(280) : (QgsDataItem::depopulate) [0ms] mPath = wms:/IGM_25000
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(557) : (QgsDataItem::setState) [0ms] item wms:/IGM_25000 set state NotPopulated -> NotPopulated
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\gui\qgsbrowserwidget.cpp(296) : (QgsBrowserWidget::refreshModel) [0ms] path = xyz:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsbrowsermodel.cpp(755) : (QgsBrowserModel::refresh) [0ms] Refresh xyz:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(297) : (QgsDataItem::refresh) [0ms] mPath = xyz:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(557) : (QgsDataItem::setState) [9ms] item xyz:/Mapzen Global Terrain set state NotPopulated -> Populated
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(557) : (QgsDataItem::setState) [6ms] item xyz:/OpenStreetMap set state NotPopulated -> Populated
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(332) : (QgsDataItem::refresh) [0ms] mPath = xyz:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(492) : (QgsDataItem::findItem) [0ms] 0 : xyz:/Mapzen Global Terrain x xyz:/Mapzen Global Terrain
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(492) : (QgsDataItem::findItem) [0ms] 0 : xyz:/Mapzen Global Terrain x xyz:/OpenStreetMap
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(492) : (QgsDataItem::findItem) [0ms] 1 : xyz:/OpenStreetMap x xyz:/OpenStreetMap
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(492) : (QgsDataItem::findItem) [0ms] 0 : xyz:/Mapzen Global Terrain x xyz:/Mapzen Global Terrain
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(332) : (QgsDataItem::refresh) [0ms] mPath = xyz:/Mapzen Global Terrain
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(557) : (QgsDataItem::setState) [0ms] item xyz:/Mapzen Global Terrain set state Populated -> Populated
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(109) : (QgsDataItem::deleteLater) [0ms] path = xyz:/Mapzen Global Terrain
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(492) : (QgsDataItem::findItem) [0ms] 0 : xyz:/Mapzen Global Terrain x xyz:/OpenStreetMap
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(492) : (QgsDataItem::findItem) [0ms] 1 : xyz:/OpenStreetMap x xyz:/OpenStreetMap
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(332) : (QgsDataItem::refresh) [0ms] mPath = xyz:/OpenStreetMap
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(557) : (QgsDataItem::setState) [0ms] item xyz:/OpenStreetMap set state Populated -> Populated
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(109) : (QgsDataItem::deleteLater) [0ms] path = xyz:/OpenStreetMap
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(557) : (QgsDataItem::setState) [0ms] item xyz: set state Populated -> Populated
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\providers\wms\qgswmssourceselect.cpp(160) : (QgsWMSSourceSelect::refresh) [9ms] Refreshing WMS connections ...
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\gui\qgsbrowserwidget.cpp(300) : (QgsBrowserWidget::refreshModel) [6ms] invalid item
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(280) : (QgsDataItem::depopulate) [0ms] mPath = home:C:/Users/Andrea
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(557) : (QgsDataItem::setState) [0ms] item home:C:/Users/Andrea set state NotPopulated -> NotPopulated
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\gui\qgsbrowserwidget.cpp(296) : (QgsBrowserWidget::refreshModel) [0ms] path = favorites:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsbrowsermodel.cpp(755) : (QgsBrowserModel::refresh) [0ms] Refresh favorites:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(297) : (QgsDataItem::refresh) [0ms] mPath = favorites:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(332) : (QgsDataItem::refresh) [1ms] mPath = favorites:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\providers\postgres\qgspostgresconn.cpp(2700) : (QgsPostgresConn::connUri) [0ms] [thread:0x2001a3c6370] theConnName = testpostgres
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(557) : (QgsDataItem::setState) [0ms] item favorites: set state Populated -> Populated
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(280) : (QgsDataItem::depopulate) [0ms] mPath = C:/
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(557) : (QgsDataItem::setState) [0ms] item C:/ set state NotPopulated -> NotPopulated
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\gui\qgsbrowserwidget.cpp(296) : (QgsBrowserWidget::refreshModel) [0ms] path = gpkg:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsbrowsermodel.cpp(755) : (QgsBrowserModel::refresh) [0ms] Refresh gpkg:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(297) : (QgsDataItem::refresh) [0ms] mPath = gpkg:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(332) : (QgsDataItem::refresh) [0ms] mPath = gpkg:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(557) : (QgsDataItem::setState) [0ms] item gpkg: set state Populated -> Populated
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(280) : (QgsDataItem::depopulate) [0ms] mPath = mssql:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(557) : (QgsDataItem::setState) [0ms] item mssql: set state NotPopulated -> NotPopulated
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(280) : (QgsDataItem::depopulate) [0ms] mPath = oracle:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(557) : (QgsDataItem::setState) [0ms] item oracle: set state NotPopulated -> NotPopulated
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\gui\qgsbrowserwidget.cpp(296) : (QgsBrowserWidget::refreshModel) [0ms] path = pg:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsbrowsermodel.cpp(755) : (QgsBrowserModel::refresh) [0ms] Refresh pg:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(297) : (QgsDataItem::refresh) [0ms] mPath = pg:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\providers\postgres\qgspostgresconn.cpp(185) : (QgsPostgresConn::connectDb) [0ms] [thread:0x2001a3c6370] refusing to use shared connection as we are not the main thread
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\providers\postgres\qgspostgresconn.cpp(329) : (QgsPostgresConn::QgsPostgresConn) [0ms] [thread:0x2001a3c6370] New PostgreSQL connection for dbname='TEST' host=localhost port=5432
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(332) : (QgsDataItem::refresh) [0ms] mPath = pg:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(492) : (QgsDataItem::findItem) [0ms] 0 : pg:/testpostgres x pg:/testpostgres
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(492) : (QgsDataItem::findItem) [0ms] 0 : pg:/testpostgres x pg:/testpostgres
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(109) : (QgsDataItem::deleteLater) [0ms] path = pg:/testpostgres
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(557) : (QgsDataItem::setState) [0ms] item pg: set state Populated -> Populated
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(280) : (QgsDataItem::depopulate) [0ms] mPath = pg:/testpostgres
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(557) : (QgsDataItem::setState) [0ms] item pg:/testpostgres set state NotPopulated -> NotPopulated
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\gui\qgsbrowserwidget.cpp(296) : (QgsBrowserWidget::refreshModel) [0ms] path = hana:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsbrowsermodel.cpp(755) : (QgsBrowserModel::refresh) [0ms] Refresh hana:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(297) : (QgsDataItem::refresh) [0ms] mPath = hana:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(332) : (QgsDataItem::refresh) [0ms] mPath = hana:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(557) : (QgsDataItem::setState) [0ms] item hana: set state Populated -> Populated
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\gui\qgsbrowserwidget.cpp(296) : (QgsBrowserWidget::refreshModel) [0ms] path = bookmarks:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\gui\qgsbrowserwidget.cpp(296) : (QgsBrowserWidget::refreshModel) [0ms] path = bookmarks:project bookmarks
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\gui\qgsbrowserwidget.cpp(296) : (QgsBrowserWidget::refreshModel) [0ms] path = bookmarks:user bookmarks
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\gui\qgsbrowserwidget.cpp(296) : (QgsBrowserWidget::refreshModel) [0ms] path = spatialite:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsbrowsermodel.cpp(755) : (QgsBrowserModel::refresh) [0ms] Refresh spatialite:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(297) : (QgsDataItem::refresh) [0ms] mPath = spatialite:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(332) : (QgsDataItem::refresh) [0ms] mPath = spatialite:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(557) : (QgsDataItem::setState) [0ms] item spatialite: set state Populated -> Populated
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\gui\qgsbrowserwidget.cpp(296) : (QgsBrowserWidget::refreshModel) [0ms] path = arcgisfeatureserver:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsbrowsermodel.cpp(755) : (QgsBrowserModel::refresh) [0ms] Refresh arcgisfeatureserver:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(297) : (QgsDataItem::refresh) [0ms] mPath = arcgisfeatureserver:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(332) : (QgsDataItem::refresh) [0ms] mPath = arcgisfeatureserver:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(557) : (QgsDataItem::setState) [0ms] item arcgisfeatureserver: set state Populated -> Populated
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\gui\qgsbrowserwidget.cpp(296) : (QgsBrowserWidget::refreshModel) [0ms] path = cloud:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsbrowsermodel.cpp(755) : (QgsBrowserModel::refresh) [0ms] Refresh cloud:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(297) : (QgsDataItem::refresh) [0ms] mPath = cloud:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(332) : (QgsDataItem::refresh) [0ms] mPath = cloud:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(557) : (QgsDataItem::setState) [0ms] item cloud: set state Populated -> Populated
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\gui\qgsbrowserwidget.cpp(296) : (QgsBrowserWidget::refreshModel) [0ms] path = tiled-scene:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsbrowsermodel.cpp(755) : (QgsBrowserModel::refresh) [0ms] Refresh tiled-scene:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(297) : (QgsDataItem::refresh) [0ms] mPath = tiled-scene:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(332) : (QgsDataItem::refresh) [0ms] mPath = tiled-scene:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(557) : (QgsDataItem::setState) [0ms] item tiled-scene: set state Populated -> Populated
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\gui\qgsbrowserwidget.cpp(296) : (QgsBrowserWidget::refreshModel) [0ms] path = sensorthings:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsbrowsermodel.cpp(755) : (QgsBrowserModel::refresh) [0ms] Refresh sensorthings:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(297) : (QgsDataItem::refresh) [0ms] mPath = sensorthings:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(332) : (QgsDataItem::refresh) [0ms] mPath = sensorthings:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(557) : (QgsDataItem::setState) [0ms] item sensorthings: set state Populated -> Populated
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\gui\qgsbrowserwidget.cpp(296) : (QgsBrowserWidget::refreshModel) [0ms] path = stac:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsbrowsermodel.cpp(755) : (QgsBrowserModel::refresh) [0ms] Refresh stac:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(297) : (QgsDataItem::refresh) [0ms] mPath = stac:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(332) : (QgsDataItem::refresh) [0ms] mPath = stac:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(557) : (QgsDataItem::setState) [0ms] item stac: set state Populated -> Populated
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\gui\qgsbrowserwidget.cpp(296) : (QgsBrowserWidget::refreshModel) [0ms] path = vectortile:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsbrowsermodel.cpp(755) : (QgsBrowserModel::refresh) [0ms] Refresh vectortile:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(297) : (QgsDataItem::refresh) [0ms] mPath = vectortile:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(332) : (QgsDataItem::refresh) [0ms] mPath = vectortile:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(557) : (QgsDataItem::setState) [0ms] item vectortile: set state Populated -> Populated
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\gui\qgsbrowserwidget.cpp(296) : (QgsBrowserWidget::refreshModel) [0ms] path = wcs:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsbrowsermodel.cpp(755) : (QgsBrowserModel::refresh) [0ms] Refresh wcs:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(297) : (QgsDataItem::refresh) [0ms] mPath = wcs:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(332) : (QgsDataItem::refresh) [0ms] mPath = wcs:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(557) : (QgsDataItem::setState) [0ms] item wcs: set state Populated -> Populated
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\gui\qgsbrowserwidget.cpp(296) : (QgsBrowserWidget::refreshModel) [0ms] path = wfs:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsbrowsermodel.cpp(755) : (QgsBrowserModel::refresh) [3ms] Refresh wfs:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(297) : (QgsDataItem::refresh) [0ms] mPath = wfs:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(332) : (QgsDataItem::refresh) [0ms] mPath = wfs:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(557) : (QgsDataItem::setState) [0ms] item wfs: set state Populated -> Populated
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\gui\qgsbrowserwidget.cpp(296) : (QgsBrowserWidget::refreshModel) [0ms] path = wms:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsbrowsermodel.cpp(755) : (QgsBrowserModel::refresh) [0ms] Refresh wms:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(297) : (QgsDataItem::refresh) [0ms] mPath = wms:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\qgsowsconnection.cpp(84) : (QgsOwsConnection::QgsOwsConnection) [0ms] theConnName = IGM_25000
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\qgsowsconnection.cpp(125) : (QgsOwsConnection::QgsOwsConnection) [13ms] encoded uri: 'dpiMode=7&featureCount=10&tilePixelRatio=0&url=http://wms.pcn.minambiente.it/ogc?map%3D/ms_ogc/WMS_v1.3/raster/IGM_25000.map'.
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(332) : (QgsDataItem::refresh) [0ms] mPath = wms:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(492) : (QgsDataItem::findItem) [0ms] 0 : wms:/IGM_25000 x wms:/IGM_25000
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(492) : (QgsDataItem::findItem) [0ms] 0 : wms:/IGM_25000 x wms:/IGM_25000
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(109) : (QgsDataItem::deleteLater) [0ms] path = wms:/IGM_25000
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(557) : (QgsDataItem::setState) [0ms] item wms: set state Populated -> Populated
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(280) : (QgsDataItem::depopulate) [0ms] mPath = wms:/IGM_25000
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(557) : (QgsDataItem::setState) [0ms] item wms:/IGM_25000 set state NotPopulated -> NotPopulated
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\gui\qgsbrowserwidget.cpp(296) : (QgsBrowserWidget::refreshModel) [0ms] path = xyz:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsbrowsermodel.cpp(755) : (QgsBrowserModel::refresh) [0ms] Refresh xyz:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(297) : (QgsDataItem::refresh) [0ms] mPath = xyz:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(557) : (QgsDataItem::setState) [9ms] item xyz:/Mapzen Global Terrain set state NotPopulated -> Populated
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(557) : (QgsDataItem::setState) [6ms] item xyz:/OpenStreetMap set state NotPopulated -> Populated
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(332) : (QgsDataItem::refresh) [0ms] mPath = xyz:
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(492) : (QgsDataItem::findItem) [0ms] 0 : xyz:/Mapzen Global Terrain x xyz:/Mapzen Global Terrain
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(492) : (QgsDataItem::findItem) [0ms] 0 : xyz:/Mapzen Global Terrain x xyz:/OpenStreetMap
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(492) : (QgsDataItem::findItem) [0ms] 1 : xyz:/OpenStreetMap x xyz:/OpenStreetMap
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(492) : (QgsDataItem::findItem) [0ms] 0 : xyz:/Mapzen Global Terrain x xyz:/Mapzen Global Terrain
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(332) : (QgsDataItem::refresh) [0ms] mPath = xyz:/Mapzen Global Terrain
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(557) : (QgsDataItem::setState) [0ms] item xyz:/Mapzen Global Terrain set state Populated -> Populated
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(109) : (QgsDataItem::deleteLater) [0ms] path = xyz:/Mapzen Global Terrain
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(492) : (QgsDataItem::findItem) [0ms] 0 : xyz:/Mapzen Global Terrain x xyz:/OpenStreetMap
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(492) : (QgsDataItem::findItem) [0ms] 1 : xyz:/OpenStreetMap x xyz:/OpenStreetMap
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(332) : (QgsDataItem::refresh) [0ms] mPath = xyz:/OpenStreetMap
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(557) : (QgsDataItem::setState) [0ms] item xyz:/OpenStreetMap set state Populated -> Populated
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(109) : (QgsDataItem::deleteLater) [0ms] path = xyz:/OpenStreetMap
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\browser\qgsdataitem.cpp(557) : (QgsDataItem::setState) [0ms] item xyz: set state Populated -> Populated
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\providers\wms\qgswmssourceselect.cpp(160) : (QgsWMSSourceSelect::refresh) [9ms] Refreshing WMS connections ...
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\qgsdatasourceuri.cpp(172) : (QgsDataSourceUri::QgsDataSourceUri) [13ms] [thread:0x2001a3c6370] connection timeout ignored
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\core\qgsdatasourceuri.cpp(227) : (QgsDataSourceUri::QgsDataSourceUri) [0ms] [thread:0x2001a3c6370] parameter "client_encoding":"UTF-8" added
[13664] C:\src\osgeo4w\src\qgis-dev\qgis\src\gui\qgscredentialdialog.cpp(118) : (QgsCredentialDialog::request) [0ms] [thread:0x2001a3c6370] emitting signal
```

**Comment by agiudiceandrea** [comment]
The issue occurs even without adding the WMS connection after the PostgreSQL connection: it occurs just adding the PostgreSQL connection using the Data Source Manager.

1. Open the Data Source Manager
2. add a new PostgreSQL connection:
   - enter the connection info, check the "Allow saving/loading QGIS layer metadata in the database" checkbox
   - press OK
   - press Cancel to the popped up "Enter Credentials" dialog window -> QGIS hangs indefinitely

**Comment by agiudiceandrea** [comment]
The issue occurs also on Ubuntu 22.04.1 running QGIS 3.41.0-Master.

**Comment by elpaso** [comment]
I can reproduce it now.

**Comment by pigreco** [comment]
The problem occurs again, both on 3.40, 3.44 and master cc @agiudiceandrea

**Comment by agiudiceandrea** [comment]
@pigreco, I've tried to reproduce the issue in various ways (https://github.com/qgis/QGIS/issues/60335#issuecomment-2639909620, https://github.com/qgis/QGIS/issues/60335#issuecomment-2639932107) running QGIS 3.44.5 using a new user profile on my Windows 10 system, but I was unable to reproduce the issue.

Since the bug described in this issue report was fixed and the fix was confirmed (https://github.com/qgis/QGIS/pull/60495#issuecomment-2642582466), then I guess the issue experienced by you could be due to a different underlying bug. I suggest you to open an issue report describing in details, with step-by-step detailed instructions, how to reproduce the issue starting from a new QGIS user profile.
