### ISSUE TITLE
crash when exporting distance/elevation table

### ISSUE THREAD

**Issue by martin-s42** [qgis/QGIS#60772]
### What is the bug or the crash?

When using the Elevation Profile -> Export Results -> Export Distance/Elevation Table... qgis crashes with a segmentation fault. When running under gdb I see the following message:
Thread 76 "Thread (pooled)" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff5dff46c0 (LWP 354565)]
QgsAbstractProfileSurfaceResults::asFeatures (this=0x7fff18001780, 
    type=<optimized out>, feedback=0x7ffe58000d70)
    at /usr/src/debug/qgis-3.40.3/src/core/elevation/qgsabstractprofilesurfacegenerator.cpp:158
158             if ( point->is3D() )
The bug happens with version 3.40; with 3.38 the problem does not occur. The problem is specific to a few CRS: It happens with EPSG:3157 or EPSG:6653, but not with EPSG:3395 or EPSG:22810. 

[dbg.csv](https://github.com/user-attachments/files/18998910/dbg.csv)

### Steps to reproduce the issue

1. rename the attached project file to, e.g., dbg.qgz
2. open the project file with qgis-3.40
3. go to View -> Elevation Profile
4. in the Elevation Profile window use Capture Curve From Feature to select the track
5. use Export Results -> Export Distance/Elevation Table.., enter a filename and click Save. qgis crashes.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.40.3-Bratislava
-- | --
QGIS code branch | Release 3.40
 
Libraries
Qt version | 5.15.16
Python version | 3.11.11
GDAL/OGR version | 3.10.2
PROJ version | 9.5.1
EPSG Registry database version | v11.022 (2024-11-05)
GEOS version | 3.13.0-CAPI-1.19.0
SQLite version | 3.49.1
PDAL version | 2.8.3
PostgreSQL client version | 16.8
SpatiaLite version | 5.1.0
QWT version | 6.3.0
QScintilla2 version | 2.14.1
OS version | openSUSE Tumbleweed
This copy of QGIS writes debugging output.
 
Active Python plugins
pointsamplingtool | 0.5.4
profiletool | 4.2.6
processing_saga_nextgen | 1.0.0
trail_elevation_stats | 0.2
processing_trajectory | 2.4
quick_map_services | 0.20.0
TerrainShading | 0.9.7
MetaSearch | 0.3.6
db_manager | 0.1.20
processing | 2.12.99
grassprovider | 2.12.99

</body></html>QGIS version
3.40.3-Bratislava
QGIS code branch
[Release 3.40](https://github.com/qgis/QGIS/tree/release-3_40)
 
Libraries
Qt version
5.15.16
Python version
3.11.11
GDAL/OGR version
3.10.2
PROJ version
9.5.1
EPSG Registry database version
v11.022 (2024-11-05)
GEOS version
3.13.0-CAPI-1.19.0
SQLite version
3.49.1
PDAL version
2.8.3
PostgreSQL client version
16.8
SpatiaLite version
5.1.0
QWT version
6.3.0
QScintilla2 version
2.14.1
OS version
openSUSE Tumbleweed
This copy of QGIS writes debugging output.
 
Active Python plugins
pointsamplingtool
0.5.4
profiletool
4.2.6
processing_saga_nextgen
1.0.0
trail_elevation_stats
0.2
processing_trajectory
2.4
quick_map_services
0.20.0
TerrainShading
0.9.7
MetaSearch
0.3.6
db_manager
0.1.20
processing
2.12.99
grassprovider
2.12.99

### Supported QGIS version

- [x] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [x] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

The problems does not occurs with all GPS tracks (gpx files). E.g., when the last track point (<trkpt>...</trkpt>) in the gpx file used in this example is removed, the crash does not happen.

**Comment by nicogodet** [comment]
Both layers in debug project are missing.
Could you share them ?

**Comment by agiudiceandrea** [comment]
@martin-s42, I cannot replicate the issue on Windows 10 running QGIS 3.40.6 (OSGeo4W):

https://github.com/user-attachments/assets/488b5fa6-8da4-407f-9e10-cd6924d3934e

May you please check if the issue still occurs running the latest available QGIS versions or provide more detailed steps?

**Comment by martin-s42** [comment]
I have never run QGIS under Windows. Nevertheless I installed QGIS 3.40.7 (OSGeo4W) under Windows 11 and can confirm that the crash did not happen.
Under Linux the crash happens with QGIS-3.40.7 and QGIS-3.42.3 with a new user profile.

**Comment by martin-s42** [comment]
I made some progress narrowing down where the segmentation fault occurs. I installed qgis-3.40.7 that I compiled from source with  -DCMAKE_BUILD_TYPE='Debug'. I run this version under gdb. I am attaching a log of the runs.
In part 1 I just let the program run into the segfault. This shows that the segfault occurs when the function interpolatePoint at qgis-3.40.7/src/core/elevation/qgsabstractprofilesurfacegenerator.cpp:157 returns a null pointer.
In part 2 I set a breakpoint at that point, but ignore it 1230 times: it turns out that the segfault happens at the last point of the track. I then set another breakpoint at qgis-3.40.7/src/core/geometry/qgslinestring.cpp:1542 inside the function visitPointsByRegularDistance, which is called by the interpolatePoint function. Line 1542 is inside a for loop over all points. Again the problem happens in the last iteration, i=1234. At the last iteration it appears to me that the condition nextPointDistance < distanceTraversed + segmentLength || qgsDoubleNear( nextPointDistance, distanceTraversed + segmentLength ) ought to be true: nextPointDistance=16386.976699329294, distanceTraversed=16383.972644594498, segmentLength=3.0040547347937645, i.e., distanceTraversed + segmentLength=16386.976699329292. But qgsDoubleNear actually returns false. qgsDoubleNear(a, b, epsilon) basically calculates the difference a-b and if that is smaller than epsilon the function returns true. epsilon is set to 8.9e-16. I am wondering whether this is meaningful: the function will never return true for a and b being significantly larger than 1, in this case a-b = 16386.976699329294 - 16386.976699329292 = 2e-12, which is basically machine accuracy: basically 16 digits for double precision numbers. Shouldn't qgsDoubleNear be calculation something like 2*abs((a-b)/(a+b)) and compare that to epsilon? 2*abs((a-b)/(a+b)) = 1.2e-16 in this case.

[dbg-log-3.40.7.txt](https://github.com/user-attachments/files/20428092/dbg-log-3.40.7.txt)

**Comment by martin-s42** [comment]
The least intrusive way may be to scale epsilon with the size of the numbers to be compare, see the attached patch. With that patch the crash no longer happens (tested for qgis-3.40.7).

[qgis-3.40.7-visitPointsByRegularDistance.patch.txt](https://github.com/user-attachments/files/20446013/qgis-3.40.7-visitPointsByRegularDistance.patch.txt)

**Comment by nicogodet** [comment]
@martin-s42 could you open a PR ?

**Comment by nicogodet** [comment]
https://github.com/qgis/QGIS/blob/master/CONTRIBUTING.md

**Comment by lbartoletti** [comment]
fixed by https://github.com/qgis/QGIS/pull/62052

**Comment by agiudiceandrea** [comment]
Is seems a crash still occurs even running QGIS LTR 3.40.11 on Windows: please see https://github.com/qgis/QGIS/issues/63608.
