### ISSUE TITLE
Can't save project

### ISSUE THREAD

**Issue by antoniolocandro** [qgis/QGIS#61560]
### What is the bug or the crash?

![Image](https://github.com/user-attachments/assets/ca7bae7d-334b-4baf-8bea-6ec8ac003d5e)

### Steps to reproduce the issue

Added two raster layers and tried to save, name seems to be included in project but then the pop up window shows up.

### Versions

QGIS version
3.43.0-Master
QGIS code revision
7996e1b587
 
Libraries
Qt version
6.8.1
Python version
3.12.10
GDAL version
3.11.0beta1 — Eganville
PROJ version
9.6.0
EPSG Registry database version
v12.004 (2025-03-02)
GEOS version
3.13.1-CAPI-1.19.2
SQLite version
3.46.1
PDAL version
2.8.3
PostgreSQL client version
17.3
SpatiaLite version
5.1.0
QWT version
6.3.0
QScintilla2 version
2.14.1
OS version
Windows 11 Version 24H2
This copy of QGIS writes debugging output.
 
Active Python plugins
quick_map_services
0.21.2
db_manager
0.1.20
processing
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@antoniolocandro, does it only occur using a recent Qt6 based QGIS 3.43.0-Master build or also using a recent Qt5 based one on the same system? Did it also occur using old QGIS 3.43.0-Master builds or not?
The issue has been previously reported at https://github.com/qgis/QGIS/issues/52666.
If the issue only occurs running recent QGIS 3.43.0-Master builds on your system, then I guess it may be related tohttps://github.com/qgis/QGIS/pull/61389.

**Comment by antoniolocandro** [comment]
Happens also with Qt5 now that I tried it today, only after installing Qt6 version though.

**Comment by GISNotWork** [comment]
I also have this exact same issue on 3.42.2-Münster.

**Comment by nicogodet** [comment]
Has been fixed by #61567

**Comment by antoniolocandro** [comment]
Confirm this works, will close now.

**Comment by thbaumann** [comment]
problem still exists. snippet to trigger the error, even in QGIS 3.42.3:


```
from qgis.core import QgsProject
project = QgsProject.instance()

Create or get the path to the attached file
file_path = project.createAttachedFile('metadata.txt')

Now open the file and write to it
with open(file_path, 'w', encoding='utf-8') as f:
    f.write("This is my custom metadata.\nLayer info, processing steps, etc.")
```


open a test-project, run snippet and try to save the project afterwards.

**Comment by Zverik** [comment]
Just got this on QGIS 3.44.2, Fedora Linux. "Unable to save zip" / "Unable to save attachments archive".

<img width="1033" height="495" alt="Image" src="https://github.com/user-attachments/assets/98e2aa02-cf7c-4fa2-94e6-e7385f194035" />

**Comment by baldemarma-lihemevi** [comment]
Possible Windows cause and confirmed workaround/fix for "Unable to perform zip"

I encountered the "Unable to perform zip" error when saving QGIS projects on Windows.

In my particular case, I was able to identify the underlying cause after testing two independent QGIS installations and tracing the file operations with Microsoft Sysinternals Process Monitor.

IMPORTANT:
This may be one possible cause of "Unable to perform zip", not necessarily the cause of every occurrence of this error.

SYSTEM / TEST ENVIRONMENT

- Windows
- QGIS 3.44.13 LTR
- Tested with two independent QGIS installations:
  1. OSGeo4W installation
  2. Clean QGIS 3.44.13 MSI installation

The same problem occurred with both installations.

SYMPTOM

A new QGIS project could be saved successfully the first time.

However, attempting to save the same .qgz project again produced:

"Unable to perform zip"

"Save As" using a different filename worked once, but the next save to that same filename failed again.

Reinstalling QGIS did not solve the problem.

DIAGNOSTIC FINDINGS

1. QGIS successfully created its temporary ZIP file:

%TEMP%\qgis-project-XXXXXX.zip

2. The temporary ZIP was tested independently and was a valid ZIP archive.

For example, it contained:

project_name.qgs
xxxxxxxx_styles.db

Therefore, in this case the problem was not actually ZIP compression itself.

3. Microsoft Sysinternals Process Monitor showed that during the second save QGIS attempted to access the existing .qgz file with DELETE permission.

ProcMon showed:

Process:
qgis-ltr-bin.exe

Operation:
CreateFile

Path:
...\project_name.qgz

Result:
ACCESS DENIED

The event included:

Desired Access: Delete
Disposition: Open
ShareMode: Read, Write, Delete

This explained why the first save worked but the second save failed.

4. The ACL of the generated .qgz file was inspected with:

icacls "C:\path\project_name.qgz"

The problematic file had permissions similar to:

BUILTIN\Administrators:(I)(F)
Everyone:(I)(R,W,DC)

The owner was the correct Windows user.

5. The same ACL was found on QGIS's temporary file:

%TEMP%\qgis-project-XXXXXX.zip

6. The Windows TEMP directory was then inspected:

icacls "$env:TEMP"

In my case, the TEMP directory had unusual permissions similar to:

BUILTIN\Administrators:(F)
Everyone:(R,W,DC)

and files created inside TEMP inherited:

BUILTIN\Administrators:(I)(F)
Everyone:(I)(R,W,DC)

This was important because the temporary QGIS ZIP inherited these permissions, and the resulting .qgz subsequently had the same problematic ACL.

CONTROLLED TEST USING AN ALTERNATIVE TEMP DIRECTORY

Before changing the real Windows TEMP permissions, I created a temporary test directory:

$qt="$env:LOCALAPPDATA\QGIS_TEMP_TEST"
New-Item -ItemType Directory -Path $qt -Force | Out-Null
icacls $qt

The new directory had normal permissions, including Full Control for:

SYSTEM
Administrators
current Windows user

I then CLOSED all QGIS instances.

From a normal (non-administrator) PowerShell window, I launched QGIS explicitly with this alternative TEMP:

$env:TEMP="$env:LOCALAPPDATA\QGIS_TEMP_TEST"
$env:TMP="$env:LOCALAPPDATA\QGIS_TEMP_TEST"

Start-Process "C:\Program Files\QGIS 3.44.13\bin\qgis-ltr-bin.exe"

IMPORTANT:
QGIS must be launched from that same PowerShell session for this test, so that it inherits the modified TEMP and TMP environment variables.

RESULT:

With QGIS using QGIS_TEMP_TEST, repeated saves of the same .qgz project worked correctly.

This A/B test strongly indicated that the normal Windows TEMP directory permissions were the cause in this particular case.

PERMANENT FIX USED ON THIS SYSTEM

WARNING:
Do not blindly copy these commands without understanding Windows ACLs.
Back up the current TEMP ACL first.
Usernames and system configurations differ.

First I backed up the existing ACL.

Example:

New-Item -ItemType Directory -Path "C:\TEMP_ACL_BACKUP" -Force | Out-Null

icacls "$env:LOCALAPPDATA\Temp" /save "C:\TEMP_ACL_BACKUP\TEMP_ACL_BEFORE.txt"

Then the TEMP ACL was corrected so that the current user, SYSTEM, and Administrators had appropriate Full Control and the problematic Everyone rule was removed.

After repair, a newly created file inside:

%LOCALAPPDATA%\Temp

inherited permissions equivalent to:

Administrators: Full Control
SYSTEM: Full Control
current Windows user: Full Control

The problematic:

Everyone:(R,W,DC)

rule was no longer inherited.

FINAL VERIFICATION

After repairing the TEMP ACL:

1. QGIS was closed.
2. QGIS was started normally from the Windows shortcut (NOT from PowerShell).
3. A new project was created.
4. The project was saved as .qgz.
5. The same project was saved repeatedly.

RESULT:

Repeated saves worked correctly.

The "Unable to perform zip" error disappeared.

CONCLUSION

In this case, "Unable to perform zip" was misleading.

QGIS was successfully creating a valid temporary ZIP archive.

The actual failure occurred later, when QGIS attempted to replace the existing .qgz file and Windows returned ACCESS DENIED for the DELETE operation.

The underlying cause was an abnormal ACL on the Windows user TEMP directory. QGIS's temporary ZIP inherited that ACL, and the resulting .qgz file subsequently inherited/carried permissions that prevented QGIS from replacing it during the next save.

Changing QGIS versions or reinstalling QGIS did not solve the problem because both installations used the same Windows TEMP environment.

A useful diagnostic procedure for other Windows users experiencing this error may therefore be:

1. Check %TEMP%.
2. Inspect its ACL with icacls.
3. Inspect qgis-project-XXXXXX.zip.
4. Inspect the resulting .qgz ACL.
5. Use ProcMon to check whether QGIS receives ACCESS DENIED when requesting DELETE.
6. Test QGIS with a clean alternative TEMP directory before changing the real TEMP ACL.

Again, this should be considered one confirmed cause of "Unable to perform zip", not necessarily the explanation for every instance of this QGIS error.
